//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData, NSString;

@interface BITCrashAttachment : NSObject <NSCoding>
{
    NSString *_filename;
    NSData *_attachmentData;
    NSString *_contentType;
}

@property(readonly, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(readonly, nonatomic) NSData *attachmentData; // @synthesize attachmentData=_attachmentData;
@property(readonly, nonatomic) NSString *filename; // @synthesize filename=_filename;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithFilename:(id)arg1 attachmentData:(id)arg2 contentType:(id)arg3;

@end

