//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface CASArgumentDescriptor : NSObject
{
    NSString *_name;
    Class _argumentClass;
    NSDictionary *_valuesByName;
    NSString *_type;
}

+ (id)argWithName:(id)arg1 valuesByName:(id)arg2;
+ (id)argWithValuesByName:(id)arg1;
+ (id)argWithClass:(Class)arg1;
+ (id)argWithType:(id)arg1;
+ (id)argWithObjCType:(const char *)arg1;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSDictionary *valuesByName; // @synthesize valuesByName=_valuesByName;
@property(retain, nonatomic) Class argumentClass; // @synthesize argumentClass=_argumentClass;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned int primitiveType;

@end

