//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CASDeviceSelectorItem.h"

@class NSString;

@interface CASDeviceScreenSizeItem : NSObject <CASDeviceSelectorItem>
{
    float _value;
    int _relation;
    unsigned int _dimension;
}

@property(nonatomic) unsigned int dimension; // @synthesize dimension=_dimension;
@property(nonatomic) int relation; // @synthesize relation=_relation;
@property(nonatomic) float value; // @synthesize value=_value;
- (id)stringValue;
- (BOOL)isValid;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

