//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface CASDeviceSelector : NSObject
{
    NSMutableArray *_items;
}

+ (id)stringFromRelation:(int)arg1;
- (void).cxx_destruct;
- (id)stringValue;
- (BOOL)isValid;
- (int)relationFromExpression:(id)arg1;
- (id)valueFromExpression:(id)arg1;
- (BOOL)addScreenSize:(id)arg1 dimension:(unsigned int)arg2;
- (BOOL)addOSVersion:(id)arg1;
- (void)addDeviceType:(int)arg1;
- (void)addItems:(id)arg1;
@property(readonly, nonatomic) NSArray *items;
- (id)init;

@end

