//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface CASExpressionSolver : NSObject
{
    NSMutableArray *_tokens;
    NSMutableDictionary *_tupleByIndex;
}

+ (id)acceptableExpressionKeywords;
@property(retain, nonatomic) NSMutableDictionary *tupleByIndex; // @synthesize tupleByIndex=_tupleByIndex;
@property(retain, nonatomic) NSMutableArray *tokens; // @synthesize tokens=_tokens;
- (void).cxx_destruct;
- (id)evaluateTokens:(id)arg1 withPlaceholderToken:(id)arg2;
- (BOOL)doesToken:(id)arg1 requireSplitForTokens:(id)arg2;
- (void)extractTuples;
- (id)tokensByReducingTokens:(id)arg1;

@end

