//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSInvocation, NSString;

@interface CASInvocation : NSObject
{
    NSString *_keyPath;
    NSInvocation *_invocation;
}

@property(retain, nonatomic) NSInvocation *invocation; // @synthesize invocation=_invocation;
@property(copy, nonatomic) NSString *keyPath; // @synthesize keyPath=_keyPath;
- (void).cxx_destruct;
- (void)invokeWithTarget:(id)arg1;
- (id)initWithInvocation:(id)arg1 forKeyPath:(id)arg2;

@end

