//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CASToken, NSDictionary, NSError, NSMutableArray, NSMutableString, NSRegularExpression;

@interface CASLexer : NSObject
{
    NSError *_error;
    NSMutableString *_str;
    NSMutableArray *_stash;
    NSMutableArray *_indentStack;
    CASToken *_previousToken;
    NSDictionary *_regexCache;
    NSRegularExpression *_indentRegex;
    int _lineNumber;
}

@property(nonatomic) int lineNumber; // @synthesize lineNumber=_lineNumber;
@property(retain, nonatomic) NSRegularExpression *indentRegex; // @synthesize indentRegex=_indentRegex;
@property(retain, nonatomic) NSDictionary *regexCache; // @synthesize regexCache=_regexCache;
@property(retain, nonatomic) CASToken *previousToken; // @synthesize previousToken=_previousToken;
@property(retain, nonatomic) NSMutableArray *indentStack; // @synthesize indentStack=_indentStack;
@property(retain, nonatomic) NSMutableArray *stash; // @synthesize stash=_stash;
@property(retain, nonatomic) NSMutableString *str; // @synthesize str=_str;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (id)testForTokenType:(int)arg1 tokenClass:(Class)arg2 transformValueBlock:(CDUnknownBlockType)arg3;
- (id)testForTokenType:(int)arg1 transformValueBlock:(CDUnknownBlockType)arg2;
- (id)selector;
- (id)space;
- (id)operation;
- (id)ref;
- (id)boolean;
- (id)unit;
- (id)string;
- (id)color;
- (id)roundBrace;
- (id)curlyBrace;
- (id)squareBrace;
- (id)newline;
- (id)comment;
- (id)carat;
- (id)seperator;
- (id)eos;
- (id)popToken;
- (id)advanceToken;
- (void)skip:(unsigned int)arg1;
- (id)errorWithDescription:(id)arg1 reason:(id)arg2 code:(unsigned int)arg3;
- (void)attachDebugInfoForToken:(id)arg1;
- (id)lookaheadByCount:(unsigned int)arg1;
- (id)nextToken;
- (id)peekToken;
@property(readonly, nonatomic) int length;
- (id)initWithString:(id)arg1;

@end

