//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CASLexer, NSArray, NSError, NSMutableDictionary, NSMutableSet, NSSet, NSString;

@interface CASParser : NSObject
{
    NSMutableSet *_importedFileNames;
    NSArray *_styleNodes;
    CASLexer *_lexer;
    NSMutableDictionary *_styleVars;
    NSError *_error;
    NSString *_filePath;
}

+ (id)parserFromFilePath:(id)arg1 variables:(id)arg2 error:(id *)arg3;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSMutableDictionary *styleVars; // @synthesize styleVars=_styleVars;
@property(retain, nonatomic) CASLexer *lexer; // @synthesize lexer=_lexer;
@property(retain, nonatomic) NSArray *styleNodes; // @synthesize styleNodes=_styleNodes;
- (void).cxx_destruct;
- (id)nextStylePropertyIsParent:(char *)arg1;
- (id)nextStyleNodes;
- (id)nextDeviceQueries;
- (id)nextStyleVar;
- (BOOL)isNestedPropertyAtIndex:(int)arg1;
- (BOOL)consumeTokensMatching:(CDUnknownBlockType)arg1;
- (id)consumeTokenOfType:(int)arg1;
- (id)lookaheadByCount:(unsigned int)arg1;
- (id)nextToken;
- (id)peekToken;
- (id)parseString:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) NSSet *importedFileNames;

@end

