//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol CASStyleableItem <NSObject>
@property(readonly, nonatomic) __weak id <CASStyleableItem> cas_alternativeParent;
@property(readonly, nonatomic) __weak id <CASStyleableItem> cas_parent;
@property(copy, nonatomic) NSString *cas_styleClass;
- (void)cas_setNeedsUpdateStyling;
- (BOOL)cas_needsUpdateStyling;
- (void)cas_updateStyling;
- (void)cas_updateStylingIfNeeded;
- (BOOL)cas_hasStyleClass:(NSString *)arg1;
- (void)cas_removeStyleClass:(NSString *)arg1;
- (void)cas_addStyleClass:(NSString *)arg1;
@end

