//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CASStyleClassUtilities : NSObject
{
}

+ (BOOL)item:(id)arg1 hasStyleClass:(id)arg2;
+ (void)removeStyleClass:(id)arg1 forItem:(id)arg2;
+ (void)addStyleClass:(id)arg1 forItem:(id)arg2;
+ (void)setStyleClasses:(id)arg1 forItem:(id)arg2;
+ (id)styleClassesForItem:(id)arg1;
+ (void)setStyleClass:(id)arg1 forItem:(id)arg2;
+ (id)styleClassForItem:(id)arg1;

@end

