//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CASToken, NSArray, NSDictionary, NSMutableArray, NSString;

@interface CASStyleProperty : NSObject
{
    NSMutableArray *_childStyleProperties;
    NSString *_name;
    NSArray *_values;
    CASToken *_nameToken;
    NSArray *_valueTokens;
    NSDictionary *_arguments;
}

@property(retain, nonatomic) NSDictionary *arguments; // @synthesize arguments=_arguments;
@property(retain, nonatomic) NSArray *valueTokens; // @synthesize valueTokens=_valueTokens;
@property(retain, nonatomic) CASToken *nameToken; // @synthesize nameToken=_nameToken;
@property(retain, nonatomic) NSArray *values; // @synthesize values=_values;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSArray *childStyleProperties; // @synthesize childStyleProperties=_childStyleProperties;
- (void).cxx_destruct;
- (void)addChildStyleProperty:(id)arg1;
- (void)resolveExpressions;
- (BOOL)transformValuesToUIFont:(id *)arg1;
- (BOOL)transformValuesToUIImage:(id *)arg1;
- (BOOL)transformValuesToNSString:(id *)arg1;
- (BOOL)transformValuesToUIColor:(id *)arg1;
- (BOOL)transformValuesToUIOffset:(struct UIOffset *)arg1;
- (BOOL)transformValuesToUIEdgeInsets:(struct UIEdgeInsets *)arg1;
- (BOOL)transformValuesToCGRect:(struct CGRect *)arg1;
- (BOOL)transformValuesToCGPoint:(struct CGPoint *)arg1;
- (BOOL)transformValuesToCGSize:(struct CGSize *)arg1;
- (id)consecutiveValuesOfTokenType:(int)arg1;
- (id)valueOfTokenType:(int)arg1;
- (id)initWithNameToken:(id)arg1 valueTokens:(id)arg2;

@end

