//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CASToken.h"

@class NSString;

@interface CASUnitToken : CASToken
{
    NSString *_suffix;
    NSString *_rawValue;
}

@property(copy, nonatomic) NSString *rawValue; // @synthesize rawValue=_rawValue;
@property(copy, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
- (void).cxx_destruct;
- (id)stringValue;

@end

