//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CRAppRater, CRBreadcrumbs, CRCrashArchive, CRDevice, CRExceptionHandler, CRNetCollector, CRNetCrumbs, CRNetworkMonitor, CRPreferences, CRReachability, NSMutableArray, NSString;

@interface CritterImpl : NSObject
{
    id <CrittercismDelegate> delegate;
    BOOL _loggingCritterError;
    BOOL _isOptedOut;
    unsigned int _sessionNum;
    BOOL _didCrashOnLastLoad;
    BOOL _isRealServer;
    BOOL _isReady;
    NSString *_deviceUUID;
    NSString *_appId;
    NSString *_critterURL;
    NSString *_netDataURL;
    NSString *_LibraryId;
    CRPreferences *_preferences;
    CRDevice *_device;
    CRExceptionHandler *_exceptionHandler;
    CRExceptionHandler *_internalExceptionHandler;
    CRCrashArchive *_crashArchive;
    CRNetworkMonitor *_netMon;
    CRNetCollector *_netCollector;
    CRAppRater *_appRater;
    CRNetCrumbs *_netCrumbs;
    CRBreadcrumbs *_breadcrumbs;
    CRReachability *_hostReach;
    CRReachability *_internetReach;
    CRReachability *_wifiReach;
    NSMutableArray *_detectedClasses;
}

@property(retain) NSMutableArray *detectedClasses; // @synthesize detectedClasses=_detectedClasses;
@property(retain) CRReachability *wifiReach; // @synthesize wifiReach=_wifiReach;
@property(retain) CRReachability *internetReach; // @synthesize internetReach=_internetReach;
@property(retain) CRReachability *hostReach; // @synthesize hostReach=_hostReach;
@property(retain) CRBreadcrumbs *breadcrumbs; // @synthesize breadcrumbs=_breadcrumbs;
@property(retain) CRNetCrumbs *netCrumbs; // @synthesize netCrumbs=_netCrumbs;
@property(retain) CRAppRater *appRater; // @synthesize appRater=_appRater;
@property(retain) CRNetCollector *netCollector; // @synthesize netCollector=_netCollector;
@property(retain) CRNetworkMonitor *netMon; // @synthesize netMon=_netMon;
@property(retain) CRCrashArchive *crashArchive; // @synthesize crashArchive=_crashArchive;
@property(retain) CRExceptionHandler *internalExceptionHandler; // @synthesize internalExceptionHandler=_internalExceptionHandler;
@property(retain) CRExceptionHandler *exceptionHandler; // @synthesize exceptionHandler=_exceptionHandler;
@property(retain) CRDevice *device; // @synthesize device=_device;
@property(retain) CRPreferences *preferences; // @synthesize preferences=_preferences;
@property(retain) NSString *LibraryId; // @synthesize LibraryId=_LibraryId;
@property(retain) NSString *netDataURL; // @synthesize netDataURL=_netDataURL;
@property(retain) NSString *critterURL; // @synthesize critterURL=_critterURL;
@property(copy) NSString *appId; // @synthesize appId=_appId;
@property BOOL isReady; // @synthesize isReady=_isReady;
@property(readonly) BOOL isRealServer; // @synthesize isRealServer=_isRealServer;
@property(readonly, getter=getUserUUID) NSString *deviceUUID; // @synthesize deviceUUID=_deviceUUID;
@property BOOL didCrashOnLastLoad; // @synthesize didCrashOnLastLoad=_didCrashOnLastLoad;
- (void)setupUserVoice;
- (void)logRateMeClickWithButtonIndex:(int)arg1;
- (void)logEndpoint:(id)arg1;
- (void)storeAPMSettings:(BOOL)arg1 withFrequency:(id)arg2;
- (void)configureSampling:(BOOL)arg1 withFrequency:(id)arg2;
- (void)useStoredAPMSettings;
- (void)receivedAPMSettings:(BOOL)arg1 withFrequency:(id)arg2 andKillState:(BOOL)arg3 persistState:(BOOL)arg4;
- (void)setupNetCollectionWithCurrentDevice:(id)arg1;
- (void)setupNetMonitoringWithFilters:(id)arg1;
- (id)setupBreadcrumbs;
- (id)setupNetCrumbs;
- (void)sendUserMetadata;
- (void)handleRateMeAlert:(id)arg1;
- (BOOL)userMetadataCacheIsDirty;
- (void)setUserMetadataCacheIsDirty:(BOOL)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)postJSONtoEndpoint:(id)arg1 withData:(id)arg2;
- (void)postURLEncodedToEndpoint:(id)arg1 withData:(id)arg2 andHandler:(id)arg3;
- (void)appLoadedWithLaunch:(BOOL)arg1;
- (id)buildRequestWithState:(int)arg1 appendUserMetadata:(BOOL)arg2;
- (void)addFullStateDataTo:(id)arg1;
- (id)getStateWithFullState:(BOOL)arg1;
- (id)makeBasicRequest;
@property(retain) id <CrittercismDelegate> delegate;
- (void)leaveBreadcrumb:(id)arg1;
- (void)updateReachability:(id)arg1;
- (void)wifiReachabilityChanged:(id)arg1;
- (void)internetReachabilityChanged:(id)arg1;
- (void)hostReachabilityChanged:(id)arg1;
- (void)setupReachabilityUpdates;
- (void)setupAppRater;
- (void)setupRotationNotifications;
- (void)setupMultiTaskNotifications;
- (void)setupHandledExceptions;
- (void)setupDetectedClasses;
- (void)setupURLs;
- (void)didRotateFromInterfaceOrientation:(int *)arg1;
- (void)handleCrashReportWithStoredDevice:(id)arg1 andStoredPrefs:(id)arg2 andBreadcrumbs:(id)arg3 andEndpoints:(id)arg4;
- (BOOL)logHandledException:(id)arg1;
- (void)logCritterError:(id)arg1;
- (void)updateLocation:(id)arg1;
- (void)addFilter:(id)arg1;
- (unsigned int)maxOfflineCrashReports;
- (void)setMaxOfflineCrashReports:(unsigned int)arg1;
- (BOOL)getOptOutStatus;
- (void)setOptOutStatus:(BOOL)arg1;
- (void)setAsyncBreadcrumbMode:(BOOL)arg1;
- (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2 andURLFilters:(id)arg3 disableInstrumentation:(BOOL)arg4;
- (void)enableFromConfigFile;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)dealloc;
- (id)init;

@end

