//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CritterImpl;

@interface Crittercism : NSObject
{
    CritterImpl *critter_;
}

+ (void)resetSharedCritter;
+ (id)sharedCritter;
+ (BOOL)isRealServer;
+ (BOOL)didCrashOnLastLoad;
+ (void)setDelegate:(id)arg1;
+ (id)delegate;
+ (void)updateLocation:(id)arg1;
+ (void)addFilter:(id)arg1;
+ (void)setValue:(id)arg1 forKey:(id)arg2;
+ (void)setUsername:(id)arg1;
+ (id)getUserUUID;
+ (void)leaveBreadcrumb:(id)arg1;
+ (void)logCritterError:(id)arg1;
+ (BOOL)logHandledException:(id)arg1;
+ (unsigned int)maxOfflineCrashReports;
+ (void)setMaxOfflineCrashReports:(unsigned int)arg1;
+ (BOOL)getOptOutStatus;
+ (void)setOptOutStatus:(BOOL)arg1;
+ (void)setAsyncBreadcrumbMode:(BOOL)arg1;
+ (void)enableFromConfigFile;
+ (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2 andURLFilters:(id)arg3 disableInstrumentation:(BOOL)arg4;
+ (void)enableWithAppID:(id)arg1 andURLFilters:(id)arg2;
+ (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2 andURLFilters:(id)arg3;
+ (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2;
+ (void)enableWithAppID:(id)arg1;
+ (void)load;
@property(nonatomic) CritterImpl *critter; // @synthesize critter=critter_;
- (void)logCritterError:(id)arg1;
- (BOOL)isRealServer;
- (BOOL)didCrashOnLastLoad;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)updateLocation:(id)arg1;
- (void)addFilter:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setUsername:(id)arg1;
- (void)leaveBreadcrumb:(id)arg1;
- (BOOL)logHandledException:(id)arg1;
- (id)getUserUUID;
- (unsigned int)maxOfflineCrashReports;
- (void)setMaxOfflineCrashReports:(unsigned int)arg1;
- (BOOL)getOptOutStatus;
- (void)setOptOutStatus:(BOOL)arg1;
- (void)setAsyncBreadcrumbMode:(BOOL)arg1;
- (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2 andURLFilters:(id)arg3 disableInstrumentation:(BOOL)arg4;
- (void)enableFromConfigFile;
- (id)init;

@end

