//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface DVRRecordings : NSObject
{
    NSArray *_singleprograms;
    NSArray *_series;
}

@property(retain, nonatomic) NSArray *series; // @synthesize series=_series;
@property(retain, nonatomic) NSArray *singleprograms; // @synthesize singleprograms=_singleprograms;
- (void).cxx_destruct;
- (void)clearScheduleRecordings;

@end

