//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "StreamAdapter.h"

@interface MediaPlayerAdapter : NSObject <StreamAdapter>
{
}

- (int)getHeight;
- (int)getWidth;
- (int)getDuration;
- (int)getPosition;
- (id)getMeta;
- (void)dealloc;
- (id)adapter:(id)arg1;

@end

