//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface Meta : NSObject <NSCoding, NSCopying>
{
    NSString *playername;
    NSString *playerversion;
    int screenwidth;
    int screenheight;
}

@property int screenheight; // @synthesize screenheight;
@property int screenwidth; // @synthesize screenwidth;
@property(retain) NSString *playerversion; // @synthesize playerversion;
@property(retain) NSString *playername; // @synthesize playername;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

