//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Downloadable.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface MovieList : NSObject <Downloadable>
{
    NSArray *_genres;
}

+ (id)listWithGenres:(id)arg1;
@property(retain, nonatomic) NSArray *genres; // @synthesize genres=_genres;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
- (id)mainGenreOrCategory;
- (id)genresOrSubCategories;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

