//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "Streamable.h"

@class NSArray, NSDate, NSNumber, NSString, TeaserData;

__attribute__((visibility("hidden")))
@interface Movie : NSObject <NSCopying, Streamable>
{
    NSString *_id;
    NSString *_title;
    NSString *_summary;
    NSString *_urlId;
    NSString *_coverPrefix;
    NSNumber *_year;
    NSNumber *_lengthInMinutes;
    NSNumber *_rentalPeriodInMinutes;
    NSDate *_availableFrom;
    NSDate *_availableTo;
    NSArray *_cast;
    NSArray *_directors;
    NSArray *_decorations;
    NSArray *_genres;
    NSString *_assetType;
    TeaserData *_teaserData;
    NSString *_coverMedium;
    NSString *_coverBig;
}

@property(copy, nonatomic) NSString *coverBig; // @synthesize coverBig=_coverBig;
@property(copy, nonatomic) NSString *coverMedium; // @synthesize coverMedium=_coverMedium;
@property(readonly, copy, nonatomic) TeaserData *teaserData; // @synthesize teaserData=_teaserData;
@property(readonly, copy, nonatomic) NSString *assetType; // @synthesize assetType=_assetType;
@property(readonly, copy, nonatomic) NSArray *genres; // @synthesize genres=_genres;
@property(readonly, copy, nonatomic) NSArray *decorations; // @synthesize decorations=_decorations;
@property(readonly, copy, nonatomic) NSArray *directors; // @synthesize directors=_directors;
@property(readonly, copy, nonatomic) NSArray *cast; // @synthesize cast=_cast;
@property(readonly, nonatomic) NSDate *availableTo; // @synthesize availableTo=_availableTo;
@property(readonly, nonatomic) NSDate *availableFrom; // @synthesize availableFrom=_availableFrom;
@property(readonly, copy, nonatomic) NSNumber *rentalPeriodInMinutes; // @synthesize rentalPeriodInMinutes=_rentalPeriodInMinutes;
@property(readonly, copy, nonatomic) NSNumber *lengthInMinutes; // @synthesize lengthInMinutes=_lengthInMinutes;
@property(readonly, copy, nonatomic) NSNumber *year; // @synthesize year=_year;
@property(readonly, copy, nonatomic) NSString *coverPrefix; // @synthesize coverPrefix=_coverPrefix;
@property(copy, nonatomic) NSString *urlId; // @synthesize urlId=_urlId;
@property(readonly, copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (int)assetScaleType;
- (id)assetScaleId;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
- (BOOL)isEqualToMovie:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)prefixImage:(id)arg1;
- (id)epgId;
- (id)tvShowId;
- (id)teaser;
- (id)releaseYear;
- (id)genresString;
- (id)castString;
- (id)directorsString;
- (id)largeCoverUrl;
- (int)area;
- (BOOL)favoriteSupport;
- (id)favoriteId;
- (int)favoriteType;
- (id)durationHumandReadable;
@property(readonly, nonatomic) BOOL soonNotAvailable;
@property(readonly, nonatomic) int availableLeftInDays;
@property(readonly, nonatomic) double duration;
@property(readonly, copy) NSString *description;
- (id)currentProgram;

// Remaining properties
@property(readonly) Class superclass;

@end

