//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (TDX)
+ (id)dateWithYear:(int)arg1 month:(int)arg2 day:(int)arg3 hour:(int)arg4 minute:(int)arg5 second:(int)arg6;
+ (id)referenceDateWithHour:(int)arg1 minute:(int)arg2;
+ (id)referenceDateWithHour:(int)arg1;
- (id)dayMonthYearFormatted;
- (id)dayMonthHoursMinutesFormatted;
- (id)dayMonthYearHoursMinutesFormatted;
- (id)tvDate;
- (id)dateBySubtractingDays:(int)arg1;
- (id)dateByAddingHours:(int)arg1;
- (id)dateByAddingDays:(int)arg1;
- (id)beginningOfDay;
- (int)second;
- (int)minute;
- (int)hour;
- (int)day;
- (int)month;
- (int)year;
- (id)weekdayStringAbbr;
- (int)weekday;
- (BOOL)isLaterThanDate:(id)arg1;
- (BOOL)isEarlierThanDate:(id)arg1;
- (int)numberOfSecondsUntil:(id)arg1;
- (int)numberOfDaysUntil:(id)arg1;
- (int)daysSinceDate:(id)arg1;
- (id)sameDateEndOfDay;
- (id)sameDateBeginningOfDay;
- (id)sameDate6AM;
- (id)startOfCurrentHour;
- (id)sameTimeNextDay;
- (id)hoursInTVDayBefore;
@end

