//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumber.h"

@interface NSNumber (ThemeNumbers)
+ (id)tdx_synopsisSidebarWidth;
+ (id)tdx_synopsisLeftMargin;
+ (id)tdx_primaryMenuSearchSettingsButtonHeight;
+ (id)tdx_primaryMenuMainButtonHeight;
+ (id)tdx_mainTopBarHeight;
@end

