//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (RXCollection)
+ (id)rx_emptyMutableCollection;
- (id)rx_filterWithBlock:(CDUnknownBlockType)arg1;
- (id)rx_filterIntoCollection:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)rx_mapWithBlock:(CDUnknownBlockType)arg1;
- (id)rx_mapIntoCollection:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)rx_detectWithBlock:(CDUnknownBlockType)arg1;
- (id)rx_foldWithBlock:(CDUnknownBlockType)arg1;
- (id)rx_foldInitialValue:(id)arg1 block:(CDUnknownBlockType)arg2;
@end

