//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (CASAdditions)
- (id)cas_stringByTrimmingLeadingCharactersInSet:(id)arg1;
- (id)cas_stringByCamelCasing;
- (id)cas_stringByTrimmingWhitespace;
- (id)cas_stringByCapitalizingFirstLetter;
@end

