//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSString, Program;

__attribute__((visibility("hidden")))
@interface Package : NSObject <NSCopying>
{
    NSString *_name;
    NSArray *_channels;
    Program *_lastProgram;
}

@property(retain, nonatomic) Program *lastProgram; // @synthesize lastProgram=_lastProgram;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)hash;
- (id)programFromIndexPath:(id)arg1;
- (unsigned int)sectionForChannel:(id)arg1;

@end

