//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "Streamable.h"
#import "TDXImageScaleAsset.h"

@class NSArray, NSDate, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface Program : NSObject <NSCopying, Streamable, TDXImageScaleAsset>
{
    BOOL _isFiller;
    BOOL _allowSeriesRecording;
    BOOL _archive;
    BOOL _canStartOver;
    BOOL _canScrub;
    BOOL _favorite;
    NSNumber *_id;
    NSDate *_begin;
    NSDate *_end;
    NSDate *_expiresFromArchive;
    NSString *_formattedBeginTime;
    NSString *_formattedEndTime;
    NSString *_formattedDate;
    NSString *_title;
    NSString *_programDescription;
    NSString *_seriesInfo;
    NSString *_categoryName;
    NSString *_subCategoryName;
    NSString *_channelName;
    NSNumber *_channelId;
    NSNumber *_totalInArchive;
    NSNumber *_categoryId;
    NSNumber *_subCategoryId;
    NSNumber *_seriesId;
    NSString *_channelLogoPrefix;
    NSString *_imagePrefix;
    NSArray *_decorations;
    NSString *_image169Medium;
    NSString *_image169Large;
    NSString *_channelLogoSmall;
    NSString *_channelLogoLarge;
    NSDate *_date;
}

@property(copy, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *channelLogoLarge; // @synthesize channelLogoLarge=_channelLogoLarge;
@property(copy, nonatomic) NSString *channelLogoSmall; // @synthesize channelLogoSmall=_channelLogoSmall;
@property(copy, nonatomic) NSString *image169Large; // @synthesize image169Large=_image169Large;
@property(copy, nonatomic) NSString *image169Medium; // @synthesize image169Medium=_image169Medium;
@property(copy, nonatomic) NSArray *decorations; // @synthesize decorations=_decorations;
@property(nonatomic) BOOL favorite; // @synthesize favorite=_favorite;
@property(readonly, nonatomic) BOOL canScrub; // @synthesize canScrub=_canScrub;
@property(readonly, nonatomic) BOOL canStartOver; // @synthesize canStartOver=_canStartOver;
@property(copy, nonatomic) NSString *imagePrefix; // @synthesize imagePrefix=_imagePrefix;
@property(readonly, copy, nonatomic) NSString *channelLogoPrefix; // @synthesize channelLogoPrefix=_channelLogoPrefix;
@property(retain, nonatomic) NSNumber *seriesId; // @synthesize seriesId=_seriesId;
@property(retain, nonatomic) NSNumber *subCategoryId; // @synthesize subCategoryId=_subCategoryId;
@property(retain, nonatomic) NSNumber *categoryId; // @synthesize categoryId=_categoryId;
@property(nonatomic) BOOL archive; // @synthesize archive=_archive;
@property(nonatomic) BOOL allowSeriesRecording; // @synthesize allowSeriesRecording=_allowSeriesRecording;
@property(readonly, nonatomic) NSNumber *totalInArchive; // @synthesize totalInArchive=_totalInArchive;
@property(copy, nonatomic) NSNumber *channelId; // @synthesize channelId=_channelId;
@property(readonly, copy, nonatomic) NSString *channelName; // @synthesize channelName=_channelName;
@property(readonly, copy, nonatomic) NSString *subCategoryName; // @synthesize subCategoryName=_subCategoryName;
@property(readonly, copy, nonatomic) NSString *categoryName; // @synthesize categoryName=_categoryName;
@property(readonly, copy, nonatomic) NSString *seriesInfo; // @synthesize seriesInfo=_seriesInfo;
@property(readonly, copy, nonatomic) NSString *programDescription; // @synthesize programDescription=_programDescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) BOOL isFiller; // @synthesize isFiller=_isFiller;
@property(readonly, nonatomic) NSString *formattedDate; // @synthesize formattedDate=_formattedDate;
@property(readonly, nonatomic) NSString *formattedEndTime; // @synthesize formattedEndTime=_formattedEndTime;
@property(readonly, nonatomic) NSString *formattedBeginTime; // @synthesize formattedBeginTime=_formattedBeginTime;
@property(readonly, nonatomic) NSDate *expiresFromArchive; // @synthesize expiresFromArchive=_expiresFromArchive;
@property(retain, nonatomic) NSDate *end; // @synthesize end=_end;
@property(retain, nonatomic) NSDate *begin; // @synthesize begin=_begin;
@property(copy, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)assetScaleId;
- (int)assetScaleType;
- (id)availableTo;
- (id)cast;
- (id)directors;
- (BOOL)isStreamable:(id)arg1;
@property(readonly) unsigned int hash;
- (BOOL)isEqualToProgram:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)prefixLogo:(id)arg1;
- (id)prefixImage:(id)arg1;
@property(readonly, copy, nonatomic) NSString *extendedTitle;
@property(readonly, nonatomic) BOOL soonNotAvailable;
- (id)epgId;
- (id)tvShowId;
- (id)releaseYear;
- (id)genresString;
- (id)castString;
- (id)directorsString;
- (id)summary;
- (id)largeCoverUrl;
- (id)currentProgram;
- (BOOL)favoriteSupport;
- (id)favoriteId;
- (int)favoriteType;
- (int)area;
- (BOOL)date:(id)arg1 isBetweenDate:(id)arg2 andDate:(id)arg3;
- (BOOL)isFutureProgram;
- (BOOL)isPresentProgram;
- (BOOL)isPastProgram;
- (id)lengthInMinutes;
@property(readonly, nonatomic) double duration;
@property(readonly, copy) NSString *description;
- (id)initWithId:(id)arg1 title:(id)arg2 channel:(id)arg3 archive:(BOOL)arg4 imagePrefix:(id)arg5 begin:(id)arg6 end:(id)arg7 image169Medium:(id)arg8 decorations:(id)arg9;
- (id)airTimeString;
- (int)expiresFromArchiveInDays;
- (id)airTime;
- (id)time;
- (id)initWithOffset:(int)arg1 today:(id)arg2 channel:(id)arg3;
@property(readonly, nonatomic) NSString *categoryString;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

