//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Downloadable.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface ProgramList : NSObject <Downloadable>
{
    NSArray *_subCategories;
}

+ (id)listWithSubCategories:(id)arg1;
@property(retain, nonatomic) NSArray *subCategories; // @synthesize subCategories=_subCategories;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
- (id)mainGenreOrCategory;
- (id)genresOrSubCategories;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

