//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RACSequence.h"

@class NSData;

@interface RACIndexSetSequence : RACSequence
{
    NSData *_data;
    const unsigned int *_indexes;
    unsigned int _count;
}

+ (id)sequenceWithIndexSetSequence:(id)arg1 offset:(unsigned int)arg2;
+ (id)sequenceWithIndexSet:(id)arg1;
@property(readonly, nonatomic) unsigned int count; // @synthesize count=_count;
@property(readonly, nonatomic) const unsigned int *indexes; // @synthesize indexes=_indexes;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)tail;
- (id)head;

@end

