//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RKPropertyMapping.h"

@interface RKAttributeMapping : RKPropertyMapping
{
}

+ (id)attributeMappingFromKeyPath:(id)arg1 toKeyPath:(id)arg2;

@end

