//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDateFormatter.h"

@class NSRegularExpression;

@interface RKDotNetDateFormatter : NSDateFormatter
{
    NSRegularExpression *_dotNetExpression;
}

+ (id)dotNetDateFormatterWithTimeZone:(id)arg1;
@property(retain, nonatomic) NSRegularExpression *dotNetExpression; // @synthesize dotNetExpression=_dotNetExpression;
- (void).cxx_destruct;
- (id)millisecondsFromString:(id)arg1;
- (id)init;
- (id)stringForObjectValue:(id)arg1;
- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;
- (id)stringFromDate:(id)arg1;
- (id)dateFromString:(id)arg1;

@end

