//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RKMapping.h"

@class NSArray, NSMutableArray;

@interface RKDynamicMapping : RKMapping
{
    NSMutableArray *_mutableMatchers;
    CDUnknownBlockType _objectMappingForRepresentationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType objectMappingForRepresentationBlock; // @synthesize objectMappingForRepresentationBlock=_objectMappingForRepresentationBlock;
@property(retain, nonatomic) NSMutableArray *mutableMatchers; // @synthesize mutableMatchers=_mutableMatchers;
- (void).cxx_destruct;
- (BOOL)isEqualToMapping:(id)arg1;
- (id)objectMappingForRepresentation:(id)arg1;
- (void)removeMatcher:(id)arg1;
- (void)addMatcher:(id)arg1;
@property(readonly, nonatomic) NSArray *objectMappings;
@property(readonly, nonatomic) NSArray *matchers;
- (id)init;

@end

