//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperation.h"

@class NSError, NSIndexSet, NSSet;

@interface RKHTTPRequestOperation : AFHTTPRequestOperation
{
    NSIndexSet *_acceptableStatusCodes;
    NSSet *_acceptableContentTypes;
    NSError *_rkHTTPError;
}

+ (id)acceptableStatusCodes;
+ (id)acceptableContentTypes;
+ (BOOL)canProcessRequest:(id)arg1;
@property(retain, nonatomic) NSError *rkHTTPError; // @synthesize rkHTTPError=_rkHTTPError;
@property(retain, nonatomic) NSSet *acceptableContentTypes; // @synthesize acceptableContentTypes=_acceptableContentTypes;
@property(retain, nonatomic) NSIndexSet *acceptableStatusCodes; // @synthesize acceptableStatusCodes=_acceptableStatusCodes;
- (void).cxx_destruct;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (id)error;
- (BOOL)hasAcceptableContentType;
- (BOOL)hasAcceptableStatusCode;

@end

