//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFormatter.h"

#import "RKValueTransforming.h"

@class NSCalendar, NSDateFormatter, NSLocale, NSString, NSTimeZone;

@interface RKISO8601DateFormatter : NSFormatter <RKValueTransforming>
{
    BOOL _parsesStrictly;
    BOOL _includeTime;
    unsigned short _timeSeparator;
    NSTimeZone *_timeZone;
    NSLocale *_locale;
    unsigned int _format;
    NSCalendar *_parsingCalendar;
    NSCalendar *_unparsingCalendar;
    NSDateFormatter *_unparsingFormatter;
    NSString *_lastUsedFormatString;
}

+ (void)initialize;
+ (id)defaultISO8601DateFormatter;
@property(copy, nonatomic) NSString *lastUsedFormatString; // @synthesize lastUsedFormatString=_lastUsedFormatString;
@property(retain, nonatomic) NSDateFormatter *unparsingFormatter; // @synthesize unparsingFormatter=_unparsingFormatter;
@property(retain, nonatomic) NSCalendar *unparsingCalendar; // @synthesize unparsingCalendar=_unparsingCalendar;
@property(retain, nonatomic) NSCalendar *parsingCalendar; // @synthesize parsingCalendar=_parsingCalendar;
@property(nonatomic) unsigned short timeSeparator; // @synthesize timeSeparator=_timeSeparator;
@property(nonatomic) BOOL includeTime; // @synthesize includeTime=_includeTime;
@property(nonatomic) unsigned int format; // @synthesize format=_format;
@property(nonatomic) BOOL parsesStrictly; // @synthesize parsesStrictly=_parsesStrictly;
@property(retain, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
@property(retain, nonatomic) NSTimeZone *timeZone; // @synthesize timeZone=_timeZone;
- (void).cxx_destruct;
- (id)weekDateStringForDate:(id)arg1;
- (id)stringForObjectValue:(id)arg1;
- (id)stringFromDate:(id)arg1 formatString:(id)arg2;
- (id)stringFromDate:(id)arg1;
- (id)replaceColonsInString:(id)arg1 withTimeSeparator:(unsigned short)arg2;
- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;
- (id)dateFromString:(id)arg1 timeZone:(out id *)arg2 range:(out struct _NSRange *)arg3;
- (id)dateFromString:(id)arg1 timeZone:(out id *)arg2;
- (id)dateFromString:(id)arg1;
- (id)dateComponentsFromString:(id)arg1 timeZone:(out id *)arg2 range:(out struct _NSRange *)arg3;
- (id)dateComponentsFromString:(id)arg1 timeZone:(out id *)arg2;
- (id)dateComponentsFromString:(id)arg1;
- (id)newCalendar;
- (id)init;
- (BOOL)transformValue:(id)arg1 toValue:(id *)arg2 ofClass:(Class)arg3 error:(id *)arg4;
- (BOOL)validateTransformationFromClass:(Class)arg1 toClass:(Class)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

