//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RKObjectMappingMatcher.h"

@class NSString;

@interface RKKeyPathObjectMappingMatcher : RKObjectMappingMatcher
{
    NSString *_keyPath;
    id _expectedValue;
}

@property(retain, nonatomic) id expectedValue; // @synthesize expectedValue=_expectedValue;
@property(copy, nonatomic) NSString *keyPath; // @synthesize keyPath=_keyPath;
- (void).cxx_destruct;
- (id)description;
- (BOOL)matches:(id)arg1;
- (id)initWithKeyPath:(id)arg1 expectedValue:(id)arg2 objectMapping:(id)arg3;

@end

