//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, RKMappingOperation, RKObjectMapping, RKRelationshipMapping;

@protocol RKMappingOperationDataSource <NSObject>
- (id)mappingOperation:(RKMappingOperation *)arg1 targetObjectForRepresentation:(NSDictionary *)arg2 withMapping:(RKObjectMapping *)arg3 inRelationship:(RKRelationshipMapping *)arg4;

@optional
- (BOOL)mappingOperationShouldSkipPropertyMapping:(RKMappingOperation *)arg1;
- (BOOL)mappingOperationShouldSetUnchangedValues:(RKMappingOperation *)arg1;
- (BOOL)mappingOperation:(RKMappingOperation *)arg1 deleteExistingValueOfRelationshipWithMapping:(RKRelationshipMapping *)arg2 error:(id *)arg3;
- (BOOL)commitChangesForMappingOperation:(RKMappingOperation *)arg1 error:(id *)arg2;
@end

