//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSArray, NSDictionary, NSError, RKMapping, RKMappingInfo, RKObjectMapping;

@interface RKMappingOperation : NSOperation
{
    id _sourceObject;
    id _destinationObject;
    RKMapping *_mapping;
    RKObjectMapping *_objectMapping;
    NSDictionary *_metadata;
    id <RKMappingOperationDelegate> _delegate;
    id <RKMappingOperationDataSource> _dataSource;
    NSError *_error;
    RKMappingInfo *_mappingInfo;
    id _parentSourceObject;
    id _rootSourceObject;
    NSDictionary *_nestedAttributeSubstitution;
    NSArray *_nestedAttributeMappings;
}

@property(retain, nonatomic) NSArray *nestedAttributeMappings; // @synthesize nestedAttributeMappings=_nestedAttributeMappings;
@property(retain, nonatomic) NSDictionary *nestedAttributeSubstitution; // @synthesize nestedAttributeSubstitution=_nestedAttributeSubstitution;
@property(retain, nonatomic) id rootSourceObject; // @synthesize rootSourceObject=_rootSourceObject;
@property(retain, nonatomic) id parentSourceObject; // @synthesize parentSourceObject=_parentSourceObject;
@property(retain, nonatomic) RKMappingInfo *mappingInfo; // @synthesize mappingInfo=_mappingInfo;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) __weak id <RKMappingOperationDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <RKMappingOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) RKObjectMapping *objectMapping; // @synthesize objectMapping=_objectMapping;
@property(retain, nonatomic) RKMapping *mapping; // @synthesize mapping=_mapping;
@property(retain, nonatomic) id destinationObject; // @synthesize destinationObject=_destinationObject;
@property(retain, nonatomic) id sourceObject; // @synthesize sourceObject=_sourceObject;
- (void).cxx_destruct;
- (id)description;
- (BOOL)performMapping:(id *)arg1;
- (void)main;
- (void)cancel;
- (void)applyNestedMappings;
- (BOOL)applyRelationshipMappings;
- (BOOL)mapOneToManyRelationshipWithValue:(id)arg1 mapping:(id)arg2;
- (BOOL)mapCoreDataToManyRelationshipValue:(id)arg1 withMapping:(id)arg2;
- (BOOL)mapOneToOneRelationshipWithValue:(id)arg1 mapping:(id)arg2;
- (BOOL)applyReplaceAssignmentPolicyForRelationshipMapping:(id)arg1;
- (BOOL)mapNestedObject:(id)arg1 toObject:(id)arg2 withRelationshipMapping:(id)arg3 metadata:(id)arg4;
- (BOOL)applyAttributeMappings:(id)arg1;
- (BOOL)applyAttributeMapping:(id)arg1 withValue:(id)arg2;
- (BOOL)transformValue:(id)arg1 toValue:(id *)arg2 withPropertyMapping:(id)arg3 error:(id *)arg4;
- (id)relationshipMappings;
- (id)keyPathAttributeMappings;
- (id)simpleAttributeMappings;
- (id)applyNestingToMappings:(id)arg1;
- (BOOL)shouldSetValue:(id *)arg1 forKeyPath:(id)arg2 usingMapping:(id)arg3;
- (BOOL)validateValue:(id *)arg1 atKeyPath:(id)arg2;
- (id)destinationObjectForMappingRepresentation:(id)arg1 parentRepresentation:(id)arg2 withMapping:(id)arg3 inRelationship:(id)arg4;
- (id)parentObjectForRelationshipMapping:(id)arg1;
- (id)initWithSourceObject:(id)arg1 destinationObject:(id)arg2 mapping:(id)arg3;

@end

