//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString, RKMapperOperation, RKMappingOperation;

@protocol RKMapperOperationDelegate <NSObject>

@optional
- (void)mapper:(RKMapperOperation *)arg1 didFailMappingOperation:(RKMappingOperation *)arg2 forKeyPath:(NSString *)arg3 withError:(NSError *)arg4;
- (void)mapper:(RKMapperOperation *)arg1 didFinishMappingOperation:(RKMappingOperation *)arg2 forKeyPath:(NSString *)arg3;
- (void)mapper:(RKMapperOperation *)arg1 willStartMappingOperation:(RKMappingOperation *)arg2 forKeyPath:(NSString *)arg3;
- (void)mapper:(RKMapperOperation *)arg1 didNotFindRepresentationOrArrayOfRepresentationsAtKeyPath:(NSString *)arg2;
- (void)mapper:(RKMapperOperation *)arg1 didFindRepresentationOrArrayOfRepresentations:(id)arg2 atKeyPath:(NSString *)arg3;
- (void)mapperDidCancelMapping:(RKMapperOperation *)arg1;
- (void)mapperDidFinishMapping:(RKMapperOperation *)arg1;
- (void)mapperWillStartMapping:(RKMapperOperation *)arg1;
@end

