//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString, RKDynamicMapping, RKMappingOperation, RKObjectMapping, RKPropertyMapping;

@protocol RKMappingOperationDelegate <NSObject>

@optional
- (void)mappingOperation:(RKMappingOperation *)arg1 didSelectObjectMapping:(RKObjectMapping *)arg2 forDynamicMapping:(RKDynamicMapping *)arg3;
- (void)mappingOperation:(RKMappingOperation *)arg1 didFailWithError:(NSError *)arg2;
- (void)mappingOperation:(RKMappingOperation *)arg1 didNotSetUnchangedValue:(id)arg2 forKeyPath:(NSString *)arg3 usingMapping:(RKPropertyMapping *)arg4;
- (void)mappingOperation:(RKMappingOperation *)arg1 didSetValue:(id)arg2 forKeyPath:(NSString *)arg3 usingMapping:(RKPropertyMapping *)arg4;
- (BOOL)mappingOperation:(RKMappingOperation *)arg1 shouldSetValue:(id)arg2 forKeyPath:(NSString *)arg3 usingMapping:(RKPropertyMapping *)arg4;
- (void)mappingOperation:(RKMappingOperation *)arg1 didNotFindValueForKeyPath:(NSString *)arg2 mapping:(RKPropertyMapping *)arg3;
- (void)mappingOperation:(RKMappingOperation *)arg1 didFindValue:(id)arg2 forKeyPath:(NSString *)arg3 mapping:(RKPropertyMapping *)arg4;
@end

