//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface RKMappingResult : NSObject
{
    NSDictionary *_keyPathToMappedObjects;
}

@property(retain, nonatomic) NSDictionary *keyPathToMappedObjects; // @synthesize keyPathToMappedObjects=_keyPathToMappedObjects;
- (void).cxx_destruct;
- (unsigned int)count;
- (id)description;
- (id)firstObject;
- (id)set;
- (id)array;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1;

@end

