//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RKMapping : NSObject
{
    BOOL forceCollectionMapping;
}

@property(nonatomic) BOOL forceCollectionMapping; // @synthesize forceCollectionMapping;
- (BOOL)isEqualToMapping:(id)arg1;

@end

