//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RKMIMETypeSerializationRegistration : NSObject
{
    id _MIMETypeStringOrRegularExpression;
    Class _serializationClass;
}

@property(nonatomic) Class serializationClass; // @synthesize serializationClass=_serializationClass;
@property(retain, nonatomic) id MIMETypeStringOrRegularExpression; // @synthesize MIMETypeStringOrRegularExpression=_MIMETypeStringOrRegularExpression;
- (void).cxx_destruct;
- (id)description;
- (BOOL)matchesMIMEType:(id)arg1;
- (id)initWithMIMEType:(id)arg1 serializationClass:(Class)arg2;

@end

