//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPClient, NSArray, NSDictionary, NSMutableArray, NSOperationQueue, NSString, NSURL, RKObjectMapping, RKRouter;

@interface RKObjectManager : NSObject
{
    AFHTTPClient *_HTTPClient;
    NSOperationQueue *_operationQueue;
    RKRouter *_router;
    NSString *_requestSerializationMIMEType;
    RKObjectMapping *_paginationMapping;
    NSMutableArray *_mutableRequestDescriptors;
    NSMutableArray *_mutableResponseDescriptors;
    NSMutableArray *_mutableFetchRequestBlocks;
    NSMutableArray *_registeredHTTPRequestOperationClasses;
    NSMutableArray *_registeredObjectRequestOperationClasses;
    NSMutableArray *_registeredManagedObjectRequestOperationClasses;
}

+ (id)managerWithBaseURL:(id)arg1;
+ (void)setSharedManager:(id)arg1;
+ (id)sharedManager;
@property(retain, nonatomic) NSMutableArray *registeredManagedObjectRequestOperationClasses; // @synthesize registeredManagedObjectRequestOperationClasses=_registeredManagedObjectRequestOperationClasses;
@property(retain, nonatomic) NSMutableArray *registeredObjectRequestOperationClasses; // @synthesize registeredObjectRequestOperationClasses=_registeredObjectRequestOperationClasses;
@property(retain, nonatomic) NSMutableArray *registeredHTTPRequestOperationClasses; // @synthesize registeredHTTPRequestOperationClasses=_registeredHTTPRequestOperationClasses;
@property(retain, nonatomic) NSMutableArray *mutableFetchRequestBlocks; // @synthesize mutableFetchRequestBlocks=_mutableFetchRequestBlocks;
@property(retain, nonatomic) NSMutableArray *mutableResponseDescriptors; // @synthesize mutableResponseDescriptors=_mutableResponseDescriptors;
@property(retain, nonatomic) NSMutableArray *mutableRequestDescriptors; // @synthesize mutableRequestDescriptors=_mutableRequestDescriptors;
@property(retain, nonatomic) RKObjectMapping *paginationMapping; // @synthesize paginationMapping=_paginationMapping;
@property(retain, nonatomic) NSString *requestSerializationMIMEType; // @synthesize requestSerializationMIMEType=_requestSerializationMIMEType;
@property(retain, nonatomic) RKRouter *router; // @synthesize router=_router;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) AFHTTPClient *HTTPClient; // @synthesize HTTPClient=_HTTPClient;
- (void).cxx_destruct;
- (void)enqueueBatchOfObjectRequestOperations:(id)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)enqueueBatchOfObjectRequestOperationsWithRoute:(id)arg1 objects:(id)arg2 progress:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)cancelAllObjectRequestOperationsWithMethod:(int)arg1 matchingPathPattern:(id)arg2;
- (id)enqueuedObjectRequestOperationsWithMethod:(int)arg1 matchingPathPattern:(id)arg2;
- (void)enqueueObjectRequestOperation:(id)arg1;
- (void)removeResponseDescriptor:(id)arg1;
- (void)addResponseDescriptorsFromArray:(id)arg1;
- (void)addResponseDescriptor:(id)arg1;
@property(readonly, nonatomic) NSArray *responseDescriptors;
- (void)removeRequestDescriptor:(id)arg1;
- (void)addRequestDescriptorsFromArray:(id)arg1;
- (void)addRequestDescriptor:(id)arg1;
@property(readonly, nonatomic) NSArray *requestDescriptors;
- (id)paginatorWithPathPattern:(id)arg1;
- (void)deleteObject:(id)arg1 path:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)patchObject:(id)arg1 path:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)putObject:(id)arg1 path:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)postObject:(id)arg1 path:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getObject:(id)arg1 path:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getObjectsAtPath:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getObjectsAtPathForRouteNamed:(id)arg1 object:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getObjectsAtPathForRelationship:(id)arg1 ofObject:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)URLWithRoute:(id)arg1 object:(id)arg2 interpolatedParameters:(id *)arg3;
- (id)appropriateObjectRequestOperationWithObject:(id)arg1 method:(int)arg2 path:(id)arg3 parameters:(id)arg4;
- (id)objectRequestOperationWithRequest:(id)arg1 responseDescriptors:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)objectRequestOperationWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)copyStateFromHTTPClientToHTTPRequestOperation:(id)arg1;
- (Class)requestOperationClassForRequest:(id)arg1 fromRegisteredClasses:(id)arg2;
- (void)unregisterRequestOperationClass:(Class)arg1;
- (BOOL)registerRequestOperationClass:(Class)arg1;
- (id)multipartFormRequestWithObject:(id)arg1 method:(int)arg2 path:(id)arg3 parameters:(id)arg4 constructingBodyWithBlock:(CDUnknownBlockType)arg5;
- (id)requestWithObject:(id)arg1 method:(int)arg2 path:(id)arg3 parameters:(id)arg4;
- (id)mergedParametersWithObject:(id)arg1 method:(int)arg2 parameters:(id)arg3;
- (id)requestWithPathForRelationship:(id)arg1 ofObject:(id)arg2 method:(int)arg3 parameters:(id)arg4;
- (id)requestWithPathForRouteNamed:(id)arg1 object:(id)arg2 parameters:(id)arg3;
- (id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
@property(readonly, nonatomic) NSDictionary *defaultHeaders;
@property(readonly, nonatomic) NSURL *baseURL;
- (void)setAcceptHeaderWithMIMEType:(id)arg1;
- (id)initWithHTTPClient:(id)arg1;

@end

