//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RKMappingOperationDelegate.h"

@class NSString, RKObjectMapping, RKRequestDescriptor;

@interface RKObjectParameterization : NSObject <RKMappingOperationDelegate>
{
    id _object;
    RKRequestDescriptor *_requestDescriptor;
}

+ (id)parametersWithObject:(id)arg1 requestDescriptor:(id)arg2 error:(id *)arg3;
@property(retain, nonatomic) RKRequestDescriptor *requestDescriptor; // @synthesize requestDescriptor=_requestDescriptor;
@property(retain, nonatomic) id object; // @synthesize object=_object;
- (void).cxx_destruct;
- (BOOL)mappingOperation:(id)arg1 shouldSetValue:(id)arg2 forKeyPath:(id)arg3 usingMapping:(id)arg4;
- (void)mappingOperation:(id)arg1 didSetValue:(id)arg2 forKeyPath:(id)arg3 usingMapping:(id)arg4;
- (id)mapObjectToParameters:(id *)arg1;
@property(readonly, nonatomic) NSString *rootKeyPath;
@property(readonly, nonatomic) RKObjectMapping *mapping;
- (id)initWithObject:(id)arg1 requestDescriptor:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

