//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RKMapping.h"

#import "NSCopying.h"

@class NSArray, NSDictionary, NSFormatter, NSMutableArray;

@interface RKObjectMapping : RKMapping <NSCopying>
{
    BOOL _assignsDefaultValueForMissingAttributes;
    BOOL _assignsNilForMissingRelationships;
    BOOL _performsKeyValueValidation;
    Class _objectClass;
    id <RKValueTransforming> _valueTransformer;
    NSMutableArray *_mutablePropertyMappings;
    CDUnknownBlockType _sourceToDestinationKeyTransformationBlock;
}

+ (void)setDefaultSourceToDestinationKeyTransformationBlock:(CDUnknownBlockType)arg1;
+ (void)initialize;
+ (id)requestMapping;
+ (id)mappingForClass:(Class)arg1;
+ (void)setPreferredDateFormatter:(id)arg1;
+ (id)preferredDateFormatter;
+ (void)addDefaultDateFormatterForString:(id)arg1 inTimeZone:(id)arg2;
+ (void)addDefaultDateFormatter:(id)arg1;
+ (void)setDefaultDateFormatters:(id)arg1;
+ (id)defaultDateFormatters;
@property(copy, nonatomic) CDUnknownBlockType sourceToDestinationKeyTransformationBlock; // @synthesize sourceToDestinationKeyTransformationBlock=_sourceToDestinationKeyTransformationBlock;
@property(retain, nonatomic) NSMutableArray *mutablePropertyMappings; // @synthesize mutablePropertyMappings=_mutablePropertyMappings;
@property(retain, nonatomic) id <RKValueTransforming> valueTransformer; // @synthesize valueTransformer=_valueTransformer;
@property(nonatomic) BOOL performsKeyValueValidation; // @synthesize performsKeyValueValidation=_performsKeyValueValidation;
@property(nonatomic) BOOL assignsNilForMissingRelationships; // @synthesize assignsNilForMissingRelationships=_assignsNilForMissingRelationships;
@property(nonatomic) BOOL assignsDefaultValueForMissingAttributes; // @synthesize assignsDefaultValueForMissingAttributes=_assignsDefaultValueForMissingAttributes;
@property(nonatomic) __weak Class objectClass; // @synthesize objectClass=_objectClass;
- (void).cxx_destruct;
- (BOOL)isEqualToMapping:(id)arg1;
- (Class)classForKeyPath:(id)arg1;
- (Class)classForProperty:(id)arg1;
- (id)defaultValueForAttribute:(id)arg1;
- (id)mappingForRelationship:(id)arg1;
- (id)mappingForAttribute:(id)arg1;
- (void)addAttributeMappingToKeyOfRepresentationFromAttribute:(id)arg1;
- (void)addAttributeMappingFromKeyOfRepresentationToAttribute:(id)arg1;
- (id)inverseMapping;
- (id)inverseMappingWithPropertyMappingsPassingTest:(CDUnknownBlockType)arg1;
- (void)removePropertyMapping:(id)arg1;
- (void)addRelationshipMappingWithSourceKeyPath:(id)arg1 mapping:(id)arg2;
- (void)addAttributeMappingsFromArray:(id)arg1;
- (void)addAttributeMappingsFromDictionary:(id)arg1;
- (id)transformSourceKeyPath:(id)arg1;
- (id)mappingForDestinationKeyPath:(id)arg1;
- (id)mappingForSourceKeyPath:(id)arg1;
- (id)description;
- (void)addPropertyMappingsFromArray:(id)arg1;
- (void)addPropertyMapping:(id)arg1;
@property(readonly, nonatomic) NSArray *relationshipMappings;
@property(readonly, nonatomic) NSArray *attributeMappings;
@property(readonly, nonatomic) __weak NSArray *mappedKeyPaths;
@property(readonly, nonatomic) NSDictionary *propertyMappingsByDestinationKeyPath;
@property(readonly, nonatomic) NSDictionary *propertyMappingsBySourceKeyPath;
@property(readonly, nonatomic) NSArray *propertyMappings;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyPropertiesFromMapping:(id)arg1;
- (id)initWithClass:(Class)arg1;
@property(retain, nonatomic) NSArray *dateFormatters;
@property(retain, nonatomic) NSFormatter *preferredDateFormatter;
@property(nonatomic) BOOL performKeyValueValidation;
@property(nonatomic) BOOL setNilForMissingRelationships;
@property(nonatomic, getter=shouldSetDefaultValueForMissingAttributes) BOOL setDefaultValueForMissingAttributes;

@end

