//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RKObjectRequestOperationLogger : NSObject
{
}

+ (void)load;
+ (id)sharedLogger;
- (void)objectRequestOperationDidFinish:(id)arg1;
- (void)HTTPOperationDidFinish:(id)arg1;
- (void)HTTPOperationDidStart:(id)arg1;
- (void)objectRequestOperationDidStart:(id)arg1;
- (void)dealloc;
- (id)init;

@end

