//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RKObjectMapping;

@interface RKObjectMappingMatcher : NSObject
{
    RKObjectMapping *_objectMapping;
}

+ (id)matcherWithPredicate:(id)arg1 objectMapping:(id)arg2;
+ (id)matcherWithKeyPath:(id)arg1 expectedValue:(id)arg2 objectMapping:(id)arg3;
@property(retain, nonatomic) RKObjectMapping *objectMapping; // @synthesize objectMapping=_objectMapping;
- (void).cxx_destruct;
- (BOOL)matches:(id)arg1;
- (id)init;

@end

