//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperation, NSRecursiveLock, TKStateMachine;

@interface RKOperationStateMachine : NSObject
{
    BOOL _cancelled;
    NSOperation *_operation;
    struct dispatch_queue_s *_dispatchQueue;
    TKStateMachine *_stateMachine;
    CDUnknownBlockType _cancellationBlock;
    NSRecursiveLock *_lock;
}

@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(copy, nonatomic) CDUnknownBlockType cancellationBlock; // @synthesize cancellationBlock=_cancellationBlock;
@property(nonatomic, getter=isCancelled) BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(retain, nonatomic) TKStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(nonatomic) struct dispatch_queue_s *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(nonatomic) __weak NSOperation *operation; // @synthesize operation=_operation;
- (void).cxx_destruct;
- (void)performBlockWithLock:(CDUnknownBlockType)arg1;
- (id)description;
- (void)setFinalizationBlock:(CDUnknownBlockType)arg1;
- (void)setExecutionBlock:(CDUnknownBlockType)arg1;
- (void)cancel;
- (void)finish;
- (void)start;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isReady;
- (id)init;
- (id)initWithOperation:(id)arg1 dispatchQueue:(struct dispatch_queue_s *)arg2;

@end

