//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSError, NSNumber, NSOperationQueue, NSURL, NSURLRequest, RKMappingResult, RKObjectMapping, RKObjectRequestOperation;

@interface RKPaginator : NSObject
{
    BOOL _loaded;
    NSOperationQueue *_operationQueue;
    RKObjectRequestOperation *_objectRequestOperation;
    RKMappingResult *_mappingResult;
    NSError *_error;
    RKObjectMapping *_paginationMapping;
    unsigned int _perPage;
    unsigned int _currentPage;
    unsigned int _offset;
    unsigned int _pageCount;
    unsigned int _objectCount;
    NSURLRequest *_request;
    Class _HTTPOperationClass;
    NSArray *_responseDescriptors;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
}

@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) NSArray *responseDescriptors; // @synthesize responseDescriptors=_responseDescriptors;
@property(retain, nonatomic) Class HTTPOperationClass; // @synthesize HTTPOperationClass=_HTTPOperationClass;
@property(copy, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(nonatomic) unsigned int objectCount; // @synthesize objectCount=_objectCount;
@property(nonatomic) unsigned int pageCount; // @synthesize pageCount=_pageCount;
@property(nonatomic) unsigned int offset; // @synthesize offset=_offset;
@property(nonatomic) unsigned int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic, getter=isLoaded) BOOL loaded; // @synthesize loaded=_loaded;
@property(nonatomic) unsigned int perPage; // @synthesize perPage=_perPage;
@property(retain, nonatomic) RKObjectMapping *paginationMapping; // @synthesize paginationMapping=_paginationMapping;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) RKMappingResult *mappingResult; // @synthesize mappingResult=_mappingResult;
@property(retain, nonatomic) RKObjectRequestOperation *objectRequestOperation; // @synthesize objectRequestOperation=_objectRequestOperation;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void).cxx_destruct;
- (void)setOffsetNumber:(id)arg1;
- (id)offsetNumber;
@property(nonatomic) NSNumber *objectCountNumber;
@property(nonatomic) NSNumber *pageCountNumber;
@property(nonatomic) NSNumber *currentPageNumber;
@property(nonatomic) NSNumber *perPageNumber;
- (void)cancel;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)description;
- (void)waitUntilFinished;
- (void)loadPage:(unsigned int)arg1;
- (void)loadPreviousPage;
- (void)loadNextPage;
- (BOOL)hasPreviousPage;
- (BOOL)hasNextPage;
- (BOOL)hasObjectCount;
- (BOOL)hasPageCount;
- (BOOL)hasOffset;
- (BOOL)hasCurrentPage;
- (void)setCompletionBlockWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSURL *URL;
@property(readonly, nonatomic) NSURL *patternURL;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 paginationMapping:(id)arg2 responseDescriptors:(id)arg3;

@end

