//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDictionary, NSString, SOCPattern;

@interface RKPathMatcher : NSObject <NSCopying>
{
    NSDictionary *_queryParameters;
    SOCPattern *_socPattern;
    NSString *_patternString;
    NSString *_sourcePath;
    NSString *_rootPath;
}

+ (id)pathMatcherWithPath:(id)arg1;
+ (id)pathMatcherWithPattern:(id)arg1;
@property(copy, nonatomic) NSString *rootPath; // @synthesize rootPath=_rootPath;
@property(copy, nonatomic) NSString *sourcePath; // @synthesize sourcePath=_sourcePath;
@property(copy, nonatomic) NSString *patternString; // @synthesize patternString=_patternString;
@property(retain, nonatomic) SOCPattern *socPattern; // @synthesize socPattern=_socPattern;
@property(copy) NSDictionary *queryParameters; // @synthesize queryParameters=_queryParameters;
- (void).cxx_destruct;
- (id)pathFromObject:(id)arg1 addingEscapes:(BOOL)arg2 interpolatedParameters:(id *)arg3;
- (BOOL)matchesPath:(id)arg1 tokenizeQueryStrings:(BOOL)arg2 parsedArguments:(id *)arg3;
- (BOOL)matchesPattern:(id)arg1 tokenizeQueryStrings:(BOOL)arg2 parsedArguments:(id *)arg3;
- (BOOL)itMatchesAndHasParsedArguments:(id *)arg1 tokenizeQueryStrings:(BOOL)arg2;
- (BOOL)bifurcateSourcePathFromQueryParameters;
- (BOOL)matches;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

