//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface RKPropertyInspector : NSObject
{
    struct dispatch_queue_s *_queue;
    NSMutableDictionary *_inspectionCache;
}

+ (id)sharedInspector;
@property(retain, nonatomic) NSMutableDictionary *inspectionCache; // @synthesize inspectionCache=_inspectionCache;
@property(nonatomic) struct dispatch_queue_s *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (Class)classForPropertyNamed:(id)arg1 ofClass:(Class)arg2 isPrimitive:(char *)arg3;
- (id)propertyInspectionForClass:(Class)arg1;
- (void)dealloc;
- (id)init;

@end

