//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, RKMapping;

@interface RKRequestDescriptor : NSObject
{
    RKMapping *_mapping;
    Class _objectClass;
    NSString *_rootKeyPath;
    int _method;
}

+ (id)requestDescriptorWithMapping:(id)arg1 objectClass:(Class)arg2 rootKeyPath:(id)arg3 method:(int)arg4;
+ (id)requestDescriptorWithMapping:(id)arg1 objectClass:(Class)arg2 rootKeyPath:(id)arg3;
@property(nonatomic) int method; // @synthesize method=_method;
@property(copy, nonatomic) NSString *rootKeyPath; // @synthesize rootKeyPath=_rootKeyPath;
@property(retain, nonatomic) Class objectClass; // @synthesize objectClass=_objectClass;
@property(retain, nonatomic) RKMapping *mapping; // @synthesize mapping=_mapping;
- (void).cxx_destruct;
- (BOOL)isEqualToRequestDescriptor:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end

