//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexSet, NSString, NSURL, RKMapping;

@interface RKResponseDescriptor : NSObject
{
    RKMapping *_mapping;
    int _method;
    NSString *_pathPattern;
    NSString *_keyPath;
    NSIndexSet *_statusCodes;
    NSURL *_baseURL;
}

+ (id)responseDescriptorWithMapping:(id)arg1 method:(int)arg2 pathPattern:(id)arg3 keyPath:(id)arg4 statusCodes:(id)arg5;
+ (id)responseDescriptorWithMapping:(id)arg1 pathPattern:(id)arg2 keyPath:(id)arg3 statusCodes:(id)arg4;
@property(copy, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(copy, nonatomic) NSIndexSet *statusCodes; // @synthesize statusCodes=_statusCodes;
@property(copy, nonatomic) NSString *keyPath; // @synthesize keyPath=_keyPath;
@property(copy, nonatomic) NSString *pathPattern; // @synthesize pathPattern=_pathPattern;
@property(nonatomic) int method; // @synthesize method=_method;
@property(retain, nonatomic) RKMapping *mapping; // @synthesize mapping=_mapping;
- (void).cxx_destruct;
- (BOOL)isEqualToResponseDescriptor:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)matchesMethod:(int)arg1;
- (BOOL)matchesResponse:(id)arg1;
- (BOOL)matchesURL:(id)arg1;
- (BOOL)matchesPath:(id)arg1;
- (id)description;

@end

