//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSArray, NSData, NSDictionary, NSError, NSHTTPURLResponse, NSURLRequest, RKMapperOperation, RKMappingResult;

@interface RKResponseMapperOperation : NSOperation
{
    BOOL _treatsEmptyResponseAsSuccess;
    NSURLRequest *_request;
    NSHTTPURLResponse *_response;
    NSData *_data;
    NSArray *_responseDescriptors;
    id _targetObject;
    id <RKMapperOperationDelegate> _mapperDelegate;
    NSDictionary *_mappingMetadata;
    NSDictionary *_responseMappingsDictionary;
    NSArray *_matchingResponseDescriptors;
    RKMappingResult *_mappingResult;
    NSError *_error;
    RKMapperOperation *_mapperOperation;
    CDUnknownBlockType _willMapDeserializedResponseBlock;
    CDUnknownBlockType _didFinishMappingBlock;
}

+ (void)registerMappingOperationDataSourceClass:(Class)arg1;
+ (void)initialize;
@property(copy, nonatomic) CDUnknownBlockType didFinishMappingBlock; // @synthesize didFinishMappingBlock=_didFinishMappingBlock;
@property(copy, nonatomic) CDUnknownBlockType willMapDeserializedResponseBlock; // @synthesize willMapDeserializedResponseBlock=_willMapDeserializedResponseBlock;
@property(retain, nonatomic) RKMapperOperation *mapperOperation; // @synthesize mapperOperation=_mapperOperation;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) RKMappingResult *mappingResult; // @synthesize mappingResult=_mappingResult;
@property(retain, nonatomic) NSArray *matchingResponseDescriptors; // @synthesize matchingResponseDescriptors=_matchingResponseDescriptors;
@property(retain, nonatomic) NSDictionary *responseMappingsDictionary; // @synthesize responseMappingsDictionary=_responseMappingsDictionary;
@property(nonatomic) BOOL treatsEmptyResponseAsSuccess; // @synthesize treatsEmptyResponseAsSuccess=_treatsEmptyResponseAsSuccess;
@property(copy, nonatomic) NSDictionary *mappingMetadata; // @synthesize mappingMetadata=_mappingMetadata;
@property(nonatomic) __weak id <RKMapperOperationDelegate> mapperDelegate; // @synthesize mapperDelegate=_mapperDelegate;
@property(retain, nonatomic) id targetObject; // @synthesize targetObject=_targetObject;
@property(retain, nonatomic) NSArray *responseDescriptors; // @synthesize responseDescriptors=_responseDescriptors;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)main;
- (void)willFinish;
- (void)cancel;
- (BOOL)hasEmptyResponse;
- (id)performMappingWithObject:(id)arg1 error:(id *)arg2;
- (id)buildResponseMappingsDictionary;
- (id)buildMatchingResponseDescriptors;
- (id)parseResponseData:(id *)arg1;
- (id)initWithRequest:(id)arg1 response:(id)arg2 data:(id)arg3 responseDescriptors:(id)arg4;

@end

