//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RKPropertyMapping.h"

@class RKMapping;

@interface RKRelationshipMapping : RKPropertyMapping
{
    RKMapping *_mapping;
    int _assignmentPolicy;
}

+ (id)relationshipMappingFromKeyPath:(id)arg1 toKeyPath:(id)arg2 withMapping:(id)arg3;
@property(nonatomic) int assignmentPolicy; // @synthesize assignmentPolicy=_assignmentPolicy;
@property(retain, nonatomic) RKMapping *mapping; // @synthesize mapping=_mapping;
- (void).cxx_destruct;
- (BOOL)isEqualToMapping:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

