//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface RKRouteSet : NSObject
{
    NSMutableArray *_routes;
}

@property(retain, nonatomic) NSMutableArray *routes; // @synthesize routes=_routes;
- (void).cxx_destruct;
- (id)routeForObject:(id)arg1 method:(int)arg2;
- (id)routesForRelationship:(id)arg1 ofClass:(Class)arg2;
- (id)routesForObject:(id)arg1;
- (id)routesForClass:(Class)arg1;
- (id)routeForRelationship:(id)arg1 ofClass:(Class)arg2 method:(int)arg3;
- (id)routeForClass:(Class)arg1 method:(int)arg2;
- (id)routeForName:(id)arg1;
- (BOOL)containsRoute:(id)arg1;
- (void)removeRoute:(id)arg1;
- (void)addRoutes:(id)arg1;
- (void)addRoute:(id)arg1;
- (id)relationshipRoutes;
- (id)classRoutes;
- (id)namedRoutes;
- (id)allRoutes;
- (id)init;

@end

