//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, RKRouteSet;

@interface RKRouter : NSObject
{
    NSURL *_baseURL;
    RKRouteSet *_routeSet;
}

@property(retain, nonatomic) RKRouteSet *routeSet; // @synthesize routeSet=_routeSet;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void).cxx_destruct;
- (id)pathFromRoute:(id)arg1 forObject:(id)arg2;
- (id)URLWithRoute:(id)arg1 object:(id)arg2;
- (id)URLForRelationship:(id)arg1 ofObject:(id)arg2 method:(int)arg3;
- (id)URLForObject:(id)arg1 method:(int)arg2;
- (id)URLForRouteNamed:(id)arg1 method:(out int *)arg2 object:(id)arg3;
- (id)init;
- (id)initWithBaseURL:(id)arg1;

@end

