//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RKRoute : NSObject
{
    BOOL _shouldEscapePath;
    NSString *_name;
    Class _objectClass;
    int _method;
    NSString *_pathPattern;
}

+ (id)routeWithRelationshipName:(id)arg1 objectClass:(Class)arg2 pathPattern:(id)arg3 method:(int)arg4;
+ (id)routeWithClass:(Class)arg1 pathPattern:(id)arg2 method:(int)arg3;
+ (id)routeWithName:(id)arg1 pathPattern:(id)arg2 method:(int)arg3;
@property(nonatomic) BOOL shouldEscapePath; // @synthesize shouldEscapePath=_shouldEscapePath;
@property(retain, nonatomic) NSString *pathPattern; // @synthesize pathPattern=_pathPattern;
@property(nonatomic) int method; // @synthesize method=_method;
@property(retain, nonatomic) Class objectClass; // @synthesize objectClass=_objectClass;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (BOOL)isRelationshipRoute;
- (BOOL)isClassRoute;
- (BOOL)isNamedRoute;
- (id)init;

@end

