//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface RKStringTokenizer : NSObject
{
    NSSet *_stopWords;
}

@property(retain, nonatomic) NSSet *stopWords; // @synthesize stopWords=_stopWords;
- (void).cxx_destruct;
- (id)tokenize:(id)arg1;

@end

