//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RKValueTransforming.h"

@class NSString;

@interface RKValueTransformer : NSObject <RKValueTransforming>
{
}

+ (void)setDefaultValueTransformer:(id)arg1;
+ (id)defaultValueTransformer;
+ (id)keyOfDictionaryValueTransformer;
+ (id)mutableValueTransformer;
+ (id)objectToCollectionValueTransformer;
+ (id)stringValueTransformer;
+ (id)iso8601TimestampToDateValueTransformer;
+ (id)timeIntervalSince1970ToDateValueTransformer;
+ (id)keyedArchivingValueTransformer;
+ (id)nullValueTransformer;
+ (id)decimalNumberToNumberValueTransformer;
+ (id)decimalNumberToStringValueTransformer;
+ (id)arrayToSetValueTransformer;
+ (id)arrayToOrderedSetValueTransformer;
+ (id)numberToStringValueTransformer;
+ (id)stringToURLValueTransformer;
+ (id)identityValueTransformer;
+ (id)singletonValueTransformer:(id *)arg1 name:(id)arg2 onceToken:(int *)arg3 validationBlock:(CDUnknownBlockType)arg4 transformationBlock:(CDUnknownBlockType)arg5;
- (BOOL)transformValue:(id)arg1 toValue:(id *)arg2 ofClass:(Class)arg3 error:(id *)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

