//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol RKValueTransforming <NSObject>
- (BOOL)transformValue:(id)arg1 toValue:(id *)arg2 ofClass:(Class)arg3 error:(id *)arg4;

@optional
- (BOOL)validateTransformationFromClass:(Class)arg1 toClass:(Class)arg2;
@end

