//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSInputStream, NSOutputStream, NSString;

__attribute__((visibility("hidden")))
@interface ServerSocketStream : NSObject
{
    NSString *m_host;
    int m_port;
    _Bool m_isHttps;
    _Bool m_keepAlive;
    _Bool m_bProxyEnabled;
    NSInputStream *m_inputStream;
    NSOutputStream *m_outputStream;
}

@property(retain, nonatomic) NSOutputStream *m_outputStream; // @synthesize m_outputStream;
@property(retain, nonatomic) NSInputStream *m_inputStream; // @synthesize m_inputStream;
- (_Bool)ResolveWithHost:(id)arg1 port:(int)arg2 proxyHost:(id *)arg3 proxyPort:(int *)arg4 isSecure:(_Bool)arg5;
- (_Bool)CheckForProxy;
- (_Bool)GetKeepAlive;
- (int)ConvertChunkToNonChunked:(id *)arg1 length:(int *)arg2;
- (void)GetChunkedContent:(id *)arg1 length:(int *)arg2;
- (int)GetNonChunkedContent:(id *)arg1 restOfLength:(int)arg2;
- (_Bool)GetDataFromServer:(id *)arg1 length:(int *)arg2;
- (_Bool)SendDataToServer:(id)arg1 length:(int)arg2;
- (void)closeOutputStream;
- (void)closeInputStream;
- (void)close;
- (_Bool)open;
- (void)dealloc;
- (id)initWithServer:(id)arg1 port:(int)arg2 isSecure:(_Bool)arg3;
- (id)init;

@end

