//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSString, SpringStreams;

@interface SpringStreamRequestOperation : NSOperation
{
    NSString *request;
    SpringStreams *spring;
}

- (void)dealloc;
- (void)main;
- (id)initWithRequest:(id)arg1 spring:(id)arg2;

@end

