//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "StreamAdapter.h"

@class MPMoviePlayerController, Meta;

__attribute__((visibility("hidden")))
@interface SpringStreamsAdapter : NSObject <StreamAdapter>
{
    Meta *_meta;
    MPMoviePlayerController *_controller;
}

@property(nonatomic) __weak MPMoviePlayerController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) Meta *meta; // @synthesize meta=_meta;
- (void).cxx_destruct;
- (int)getHeight;
- (int)getWidth;
- (int)getDuration;
- (int)getPosition;
- (id)getMeta;
- (id)initWithAdapter:(id)arg1;

@end

