//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSOperationQueue;

@interface SpringStreams : NSObject
{
    NSOperationQueue *queue;
    unsigned int backgroundTask;
    NSMutableArray *syncrates;
    BOOL debug;
    BOOL tracking;
    BOOL offlineMode;
    int syncrate;
    int pausesync;
    int maxstates;
    double timeout;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)convertNumberToStringWithRadix:(long long)arg1 radix:(int)arg2;
+ (id)md5HexDigest:(id)arg1;
+ (id)getInstance;
+ (id)getInstance:(id)arg1 a:(id)arg2;
@property double timeout; // @synthesize timeout;
@property BOOL offlineMode; // @synthesize offlineMode;
@property BOOL tracking; // @synthesize tracking;
@property int maxstates; // @synthesize maxstates;
@property int pausesync; // @synthesize pausesync;
@property int syncrate; // @synthesize syncrate;
@property BOOL debug; // @synthesize debug;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setBufferSize:(int)arg1;
- (void)sf:(id)arg1 buf:(id)arg2;
- (id)sf:(id)arg1;
- (id)encode:(id)arg1;
- (id)escape:(id)arg1;
- (id)createRequest:(id)arg1;
- (_Bool)streamingSendRequestSynchron:(id)arg1;
- (void)steamingSendRequest:(id)arg1;
- (id)findSite:(id)arg1;
- (id)streamingGenerateEventObject:(id)arg1 v:(id)arg2;
- (void)trace:(id)arg1 error:(id)arg2;
- (void)trace:(id)arg1;
- (void)streamingDoSend:(id)arg1;
- (void)streamingSend:(id)arg1 what:(id)arg2;
- (long)getCurrentTime;
- (void)doSync:(id)arg1;
- (void)doUpdate:(id)arg1;
- (void)flush;
- (void)unload;
- (void)unregister:(id)arg1;
- (id)track:(id)arg1 atts:(id)arg2;
- (id)getMacAddress;
- (id)getIFV;
- (id)getAI;
- (id)getMacAddressId;
- (void)handleApplicationEvent:(id)arg1;
- (void)registerForApplicationEvents;
- (id)getSyncRates;
- (void)configureSyncrates:(id)arg1;
- (void)configure:(id)arg1;
- (id)getConfig;
- (void)dealloc;
- (id)writeIFV:(id)arg1 to:(id)arg2;
- (id)readIFV:(id)arg1;
- (BOOL)checkIFV:(id)arg1;
- (id)initWithSSL:(id)arg1 a:(id)arg2 ssl:(BOOL)arg3;
- (id)init:(id)arg1 a:(id)arg2;
- (id)init;

@end

