//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface StreamingKMSPersistentRingBuffer : NSObject
{
    int _size;
}

+ (void)print:(id)arg1 level:(int)arg2;
@property(getter=getSize) int size; // @synthesize size=_size;
- (void)readBuffer;
- (void)writeBuffer;
- (BOOL)isLast:(id)arg1;
- (void)appendTail:(id)arg1;
- (id)dropLast;
- (id)dropFirst:(id)arg1;
- (id)dropFirst;
- (BOOL)push:(id)arg1;
- (id)pop:(id)arg1;
- (id)pop;
- (id)peek;
- (void)clear;
- (long)size;
- (void)dealloc;
- (id)init:(int)arg1 streamingFile:(id)arg2 comparator:(id)arg3;
- (id)init:(int)arg1 streamingFile:(id)arg2;

@end

