//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "streamingKMSComparator.h"

@interface StreamingKMSStandardComparator : NSObject <streamingKMSComparator>
{
}

- (int)compare:(id)arg1 rh:(id)arg2;
- (id)init;

@end

