//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "TDXImageScaleAsset.h"

@class NSArray, NSDate, NSNumber, NSString, Program;

@protocol Streamable <NSObject, TDXImageScaleAsset>
- (NSArray *)decorations;
- (NSDate *)availableTo;
- (BOOL)soonNotAvailable;
- (NSString *)title;
- (NSNumber *)releaseYear;
- (NSString *)genresString;
- (NSString *)castString;
- (NSArray *)cast;
- (NSString *)directorsString;
- (NSArray *)directors;
- (NSString *)summary;
- (NSString *)largeCoverUrl;
- (BOOL)favoriteSupport;
- (NSString *)favoriteId;
- (int)favoriteType;
- (NSNumber *)lengthInMinutes;
- (double)duration;
- (NSString *)epgId;
- (Program *)currentProgram;
- (id)tvShowId;
- (id)id;
- (int)area;
@end

