//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray, NSMutableDictionary, NSObject<StreamAdapter>, NSString, SpringStreams;

@interface Stream : NSObject <NSCopying>
{
    NSString *uid;
    long start;
    long lastActivity;
    SpringStreams *collector;
    NSObject<StreamAdapter> *stream;
    NSMutableArray *playStates;
    NSMutableArray *state;
    int _pause;
    int lastSync;
    BOOL doSync;
    BOOL closed;
    int duration;
    BOOL modified;
    NSMutableDictionary *attributes;
}

@property BOOL modified; // @synthesize modified;
@property(retain) NSMutableDictionary *attributes; // @synthesize attributes;
- (_Bool)isValid;
- (void)stop;
- (void)flush;
- (void)sync:(double)arg1;
- (void)update:(double)arg1;
- (void)addState:(int)arg1;
- (void)addPlayState:(id)arg1 e:(id)arg2;
- (id)convertNumberToStringWithRadix:(long)arg1 radix:(int)arg2;
- (id)getCurrentTimeBase36;
- (long)getCurrentTime;
- (id)getStreamAdapter;
- (long)getLastActivity;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)switchSyncRate;
- (void)dealloc;
- (id)init:(id)arg1 sa:(id)arg2 a:(id)arg3;

@end

