//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"

@class NSString;

@interface StreamingBSWebViewUserAgent : NSObject <UIWebViewDelegate>
{
    NSString *userAgent;
}

@property(retain, nonatomic) NSString *userAgent; // @synthesize userAgent;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (id)userAgentString;

@end

