//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "TDXConnectionManagerDelegate.h"
#import "TDXLoginManagerDelegate.h"
#import "UIApplicationDelegate.h"

@class NSString, TDXLoginViewController, TDXRootViewController, TDXStackViewController, UIWindow;

__attribute__((visibility("hidden")))
@interface TDXAppDelegate : UIResponder <UIApplicationDelegate, TDXLoginManagerDelegate, TDXConnectionManagerDelegate>
{
    UIWindow *_window;
    UIWindow *_secondWindow;
    TDXStackViewController *_stackController;
    TDXLoginViewController *_loginViewController;
    TDXRootViewController *_rootViewController;
}

+ (id)sharedInstance;
@property(retain, nonatomic) TDXRootViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) TDXLoginViewController *loginViewController; // @synthesize loginViewController=_loginViewController;
@property(retain, nonatomic) TDXStackViewController *stackController; // @synthesize stackController=_stackController;
@property(retain, nonatomic) UIWindow *secondWindow; // @synthesize secondWindow=_secondWindow;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (id)buildNumString;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (BOOL)didCrashInLastSessionOnStartup;
- (void)handleScreenDidDisconnectOrEnterBackgroundNotification:(id)arg1;
- (void)checkAndSetupSecondaryScreen;
- (void)handleScreenDidConnectOrEnterForegroundNotification:(id)arg1;
- (id)topMostViewController;
- (void)loginDidChange:(id)arg1;
- (void)connectionDidChange:(id)arg1;
- (void)guestNetworkDidChange:(id)arg1;
- (void)didUpdateGeoBlocking:(id)arg1 hasChanged:(BOOL)arg2;
- (void)setSplashVisibility:(_Bool)arg1 showLogo:(_Bool)arg2 animatedRemoval:(_Bool)arg3;
- (void)showSplashAfterDelay:(float)arg1 logo:(_Bool)arg2;
- (void)performStartupLogin;
- (void)setupApplication;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

