//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Channel, NSMutableArray;

__attribute__((visibility("hidden")))
@interface TDXBrowseChannelViewModel : NSObject
{
    Channel *_channel;
    NSMutableArray *_completePrograms;
    float _programWidth;
    int _selectedItem;
}

@property(nonatomic) int selectedItem; // @synthesize selectedItem=_selectedItem;
@property(readonly, nonatomic) float programWidth; // @synthesize programWidth=_programWidth;
@property(retain, nonatomic) NSMutableArray *completePrograms; // @synthesize completePrograms=_completePrograms;
@property(readonly, nonatomic) Channel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (void)fetchCompleteProgram:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)initWithChannel:(id)arg1 selectedItem:(int)arg2 programWidth:(float)arg3;

@end

