//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSIndexPath, TDXBrowseChannelViewModel;

__attribute__((visibility("hidden")))
@interface TDXBrowseChannelComponentViewController : UICollectionViewController
{
    TDXBrowseChannelViewModel *_viewModel;
    NSIndexPath *_indexPathBeforeScroll;
}

@property(retain, nonatomic) NSIndexPath *indexPathBeforeScroll; // @synthesize indexPathBeforeScroll=_indexPathBeforeScroll;
@property(retain, nonatomic) TDXBrowseChannelViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)willMoveToParentViewController:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)updateViewConstraints;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1;

@end

