//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class TDXGuideViewModel, UIImageView;

__attribute__((visibility("hidden")))
@interface TDXCurrentTimeOverlayView : UIScrollView
{
    TDXGuideViewModel *_viewModel;
    UIImageView *_timeIndicatorLine;
}

@property(retain, nonatomic) UIImageView *timeIndicatorLine; // @synthesize timeIndicatorLine=_timeIndicatorLine;
@property(retain, nonatomic) TDXGuideViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithViewModel:(id)arg1;

@end

