//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

__attribute__((visibility("hidden")))
@interface TDXCollectionView : UICollectionView
{
}

+ (id)collectionViewWithFrame:(struct CGRect)arg1 layout:(id)arg2 dataSource:(id)arg3 delegate:(id)arg4 cellClasses:(id)arg5 reuseIdentifiers:(id)arg6;
- (void)reloadSections:(id)arg1;

@end

