//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "TDXCell.h"

@class NSString, UILabel;

__attribute__((visibility("hidden")))
@interface TDXCMSTextCell : UICollectionViewCell <TDXCell>
{
    UILabel *_headline;
    UILabel *_content;
}

+ (id)identifier;
@property(retain, nonatomic) UILabel *content; // @synthesize content=_content;
@property(retain, nonatomic) UILabel *headline; // @synthesize headline=_headline;
- (void).cxx_destruct;
- (void)configureForObject:(id)arg1;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

