//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSTimer, Reachability, TDXGeoInfo, TDXXmppData;

__attribute__((visibility("hidden")))
@interface TDXConnectionManager : NSObject
{
    Reachability *internetReach;
    Reachability *wifiReach;
    CDStruct_c7634f6b lastConfiguration;
    BOOL guestLoginConnection;
    BOOL notificationHasBeenScheduled;
    _Bool guestRequestInProgress;
    _Bool lastPingSucceeded;
    _Bool connectionErrorMessage;
    NSTimer *pingTimer;
    TDXGeoInfo *geoInfo;
    id <TDXConnectionManagerDelegate> _delegate;
    TDXXmppData *_guestXmppData;
    NSString *_connectionErrorMessage;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *connectionErrorMessage; // @synthesize connectionErrorMessage=_connectionErrorMessage;
@property(retain, nonatomic) TDXXmppData *guestXmppData; // @synthesize guestXmppData=_guestXmppData;
@property(nonatomic) id <TDXConnectionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)connectionConfigurationHasChanged;
- (BOOL)compareConfiguration:(CDStruct_c7634f6b)arg1 withConfiguration:(CDStruct_c7634f6b)arg2;
- (void)sendNetworkChangedMessage;
- (void)reachabilityChangedNotificationListener:(id)arg1;
@property(readonly, nonatomic) BOOL isGeoBlocked;
@property(readonly, nonatomic) BOOL isGuestLoginConnection;
@property(readonly, nonatomic) BOOL isYouSeeApiAvailable; // @dynamic isYouSeeApiAvailable;
@property(readonly, nonatomic) BOOL hasActiveConnection; // @dynamic hasActiveConnection;
- (void)stopPingingYouSeeAPI;
- (void)startPingYouSeeApi;
- (void)checkForGuestLoginConnectionWithCompletion:(CDUnknownBlockType)arg1;
- (void)checkIfGeoBlockedAsync;
- (void)pingAPI;
- (void)changePingIntervalWithSuccessfulPing:(BOOL)arg1;
- (void)HTTPOperationDidFinish:(id)arg1;
- (id)init;

@end

