//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXCredentials : NSObject
{
    NSString *_username;
    NSString *_password;
}

+ (id)instanceWithUsername:(id)arg1 password:(id)arg2;
@property(readonly, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *encryptedPassword; // @dynamic encryptedPassword;
@property(readonly, nonatomic) BOOL valid;
- (id)initWithUsername:(id)arg1 password:(id)arg2;

@end

