//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TDXGuideLayoutDataSource.h"
#import "UICollectionViewDataSource.h"

@class NSString, TDXGuideViewModel;

__attribute__((visibility("hidden")))
@interface TDXChannelsDataSource : NSObject <UICollectionViewDataSource, TDXGuideLayoutDataSource>
{
    TDXGuideViewModel *_viewModel;
}

@property(retain, nonatomic) TDXGuideViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (int)numberOfSections;
- (id)collectionView:(id)arg1 objectForIndexPath:(id)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

