//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class TDXConnectionManager;

@protocol TDXConnectionManagerDelegate
- (void)didUpdateGeoBlocking:(TDXConnectionManager *)arg1 hasChanged:(BOOL)arg2;
- (void)guestNetworkDidChange:(TDXConnectionManager *)arg1;
- (void)connectionDidChange:(TDXConnectionManager *)arg1;
@end

