//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TDXDecorations : NSObject
{
    NSNumber *_widthPercent;
    NSString *_url;
    NSString *_position;
}

@property(readonly, nonatomic) NSString *position; // @synthesize position=_position;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSNumber *widthPercent; // @synthesize widthPercent=_widthPercent;
- (void).cxx_destruct;

@end

