//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXDatePickerButton : UIButton
{
    UILabel *_numLabel;
    UILabel *_dayLabel;
    UIImageView *_circleImage;
    int _datePickerButtonType;
}

@property(nonatomic) int datePickerButtonType; // @synthesize datePickerButtonType=_datePickerButtonType;
@property(retain, nonatomic) UIImageView *circleImage; // @synthesize circleImage=_circleImage;
@property(retain, nonatomic) UILabel *dayLabel; // @synthesize dayLabel=_dayLabel;
@property(retain, nonatomic) UILabel *numLabel; // @synthesize numLabel=_numLabel;
- (void).cxx_destruct;
- (void)setDayNumber:(id)arg1 andWeekDay:(id)arg2;
- (void)setSelected:(BOOL)arg1;
- (void)updateConstraints;
- (struct CGSize)intrinsicContentSize;
- (id)initWithType:(int)arg1;

@end

