//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, TDXDatePickerButton, TDXGuideViewModel, UIScrollView;

__attribute__((visibility("hidden")))
@interface TDXDatePickerView : UIView
{
    id <TDXDatePickerViewProtocol> _datePickerDelegate;
    TDXDatePickerButton *_currentlySelectedButton;
    NSMutableArray *_drawnDates;
    UIScrollView *_containerView;
    TDXGuideViewModel *_viewModel;
}

@property(retain, nonatomic) TDXGuideViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UIScrollView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSMutableArray *drawnDates; // @synthesize drawnDates=_drawnDates;
@property(retain, nonatomic) TDXDatePickerButton *currentlySelectedButton; // @synthesize currentlySelectedButton=_currentlySelectedButton;
@property(nonatomic) __weak id <TDXDatePickerViewProtocol> datePickerDelegate; // @synthesize datePickerDelegate=_datePickerDelegate;
- (void).cxx_destruct;
- (void)drawDates;
- (void)didPressDateButton:(id)arg1;
- (void)setOffsetForSelectedDay:(int)arg1;
- (void)layoutSubviews;
- (id)initWithViewModel:(id)arg1;

@end

