//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TDXError : NSObject
{
    NSNumber *_code;
    NSString *_errorMessage;
    NSString *_presentableError;
}

@property(copy, nonatomic) NSString *presentableError; // @synthesize presentableError=_presentableError;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(copy, nonatomic) NSNumber *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (id)description;
- (id)initWithPresentMessage:(id)arg1 code:(id)arg2;
- (id)initWithJsonBody:(id)arg1;
- (id)initWithResponseData:(id)arg1;

@end

