//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, TDXWebView;

__attribute__((visibility("hidden")))
@interface TDXFrontPageWebViewController : UIViewController
{
    NSString *_action;
    TDXWebView *_webView;
}

@property(retain, nonatomic) TDXWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
- (void).cxx_destruct;
- (void)updateViewConstraints;
- (void)viewDidAppear:(BOOL)arg1;
- (void)loadView;
- (id)initWithURL:(id)arg1 andFrontPageDelegate:(id)arg2 andSectionHeaderDelegate:(id)arg3;

@end

