//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class CAGradientLayer, UIButton, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXFrontPagePromoSupplementaryView : UICollectionReusableView
{
    UIImageView *_teaserImageView;
    CAGradientLayer *_maskLayer;
    CAGradientLayer *_toneDownLayer;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_playButton;
    UIView *_tapView;
    CDUnknownBlockType _play;
}

+ (id)kind;
+ (id)identifier;
@property(copy, nonatomic) CDUnknownBlockType play; // @synthesize play=_play;
@property(retain, nonatomic) UIView *tapView; // @synthesize tapView=_tapView;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) CAGradientLayer *toneDownLayer; // @synthesize toneDownLayer=_toneDownLayer;
@property(retain, nonatomic) CAGradientLayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) UIImageView *teaserImageView; // @synthesize teaserImageView=_teaserImageView;
- (void).cxx_destruct;
- (void)configureWithStreamable:(id)arg1 andPlayBlock:(CDUnknownBlockType)arg2;
- (void)updateConstraints;
- (void)layoutSubviews;
- (id)createTeaserImageMaskLayer;
- (id)createTeaserImageToneDownLayer;
- (void)handleTap;
- (id)initWithFrame:(struct CGRect)arg1;

@end

