//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXFilterRequestManager : NSObject
{
}

+ (id)sharedInstance;
- (id)generateStoreKeyFor:(id)arg1;
- (void)saveFilterRequestIndex:(unsigned int)arg1 forMenuItemRequest:(id)arg2;
- (unsigned int)retrieveSavedFilterRequestIndexForMenuItemRequest:(id)arg1;

@end

