//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, TDXMenuItem, UIImageView, UIScrollView;

__attribute__((visibility("hidden")))
@interface TDXFrontPagePagerView : UIView
{
    NSArray *_menuItems;
    NSMutableArray *_labels;
    UIScrollView *_scrollview;
    TDXMenuItem *_selectedMenuItem;
    UIView *_dotsContainerView;
    NSMutableArray *_dotImageViews;
    UIImageView *_circleImageView;
}

@property(retain, nonatomic) UIImageView *circleImageView; // @synthesize circleImageView=_circleImageView;
@property(retain, nonatomic) NSMutableArray *dotImageViews; // @synthesize dotImageViews=_dotImageViews;
@property(retain, nonatomic) UIView *dotsContainerView; // @synthesize dotsContainerView=_dotsContainerView;
@property(retain, nonatomic) TDXMenuItem *selectedMenuItem; // @synthesize selectedMenuItem=_selectedMenuItem;
@property(retain, nonatomic) UIScrollView *scrollview; // @synthesize scrollview=_scrollview;
@property(retain, nonatomic) NSMutableArray *labels; // @synthesize labels=_labels;
@property(retain, nonatomic) NSArray *menuItems; // @synthesize menuItems=_menuItems;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateDots;
- (void)setSelectedSecondaryMenuItem:(id)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

