//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface TDXFrontPageOnboardingView : UIView
{
    UILabel *_headingLabel;
    UILabel *_bodyTextLabel;
    float _viewWidth;
}

@property(nonatomic) float viewWidth; // @synthesize viewWidth=_viewWidth;
@property(retain, nonatomic) UILabel *bodyTextLabel; // @synthesize bodyTextLabel=_bodyTextLabel;
@property(retain, nonatomic) UILabel *headingLabel; // @synthesize headingLabel=_headingLabel;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

