//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, TDXMenuItem, TDXTopMenuButton, UIScrollView;

__attribute__((visibility("hidden")))
@interface TDXFrontPageTopMenuView : UIView
{
    BOOL _isTopMenuCentered;
    TDXMenuItem *_selectedMenuItem;
    NSArray *_menuItems;
    UIScrollView *_containerScrollView;
    NSMutableArray *_menuButtonViews;
    UIView *_selectedButtonIndicator;
    TDXTopMenuButton *_selectedMenuButton;
    TDXTopMenuButton *_savedMenuButtonForIndicatorWidth;
    float _topMenuLeftEdgeOffset;
    CDUnknownBlockType _didTapItemAtIndexCallback;
    CDUnknownBlockType _menuItemDidChangeCallback;
}

@property(nonatomic) BOOL isTopMenuCentered; // @synthesize isTopMenuCentered=_isTopMenuCentered;
@property(copy, nonatomic) CDUnknownBlockType menuItemDidChangeCallback; // @synthesize menuItemDidChangeCallback=_menuItemDidChangeCallback;
@property(copy, nonatomic) CDUnknownBlockType didTapItemAtIndexCallback; // @synthesize didTapItemAtIndexCallback=_didTapItemAtIndexCallback;
@property(nonatomic) float topMenuLeftEdgeOffset; // @synthesize topMenuLeftEdgeOffset=_topMenuLeftEdgeOffset;
@property(retain, nonatomic) TDXTopMenuButton *savedMenuButtonForIndicatorWidth; // @synthesize savedMenuButtonForIndicatorWidth=_savedMenuButtonForIndicatorWidth;
@property(retain, nonatomic) TDXTopMenuButton *selectedMenuButton; // @synthesize selectedMenuButton=_selectedMenuButton;
@property(retain, nonatomic) UIView *selectedButtonIndicator; // @synthesize selectedButtonIndicator=_selectedButtonIndicator;
@property(retain, nonatomic) NSMutableArray *menuButtonViews; // @synthesize menuButtonViews=_menuButtonViews;
@property(retain, nonatomic) UIScrollView *containerScrollView; // @synthesize containerScrollView=_containerScrollView;
@property(retain, nonatomic) NSArray *menuItems; // @synthesize menuItems=_menuItems;
@property(retain, nonatomic) TDXMenuItem *selectedMenuItem; // @synthesize selectedMenuItem=_selectedMenuItem;
- (void).cxx_destruct;
- (void)setSelectedSecondaryMenuItem:(id)arg1 animated:(BOOL)arg2 swiping:(BOOL)arg3;
- (void)updateButtonsWithSelectedMenuItem:(id)arg1;
- (void)setContentOffsetForMenuButton:(id)arg1 percentageScrolled:(float)arg2;
- (float)buttonIndicatorWidthForScrollView:(id)arg1 percentageScrolled:(float)arg2;
- (float)buttonIndicatorOriginXForScrollView:(id)arg1 percentageScrolled:(float)arg2;
- (void)frontpageContentDidScroll:(id)arg1;
- (void)layoutSubviews;
- (id)initWithButtonTapCallback:(CDUnknownBlockType)arg1 andMenuItemDidChangeCallBack:(CDUnknownBlockType)arg2;

@end

