//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UILabel;

__attribute__((visibility("hidden")))
@interface TDXFavoritePopUpView : UIView
{
    UILabel *_titleLabel;
    NSString *_uniqueKeyString;
}

@property(retain, nonatomic) NSString *uniqueKeyString; // @synthesize uniqueKeyString=_uniqueKeyString;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)hidePopUp;
- (void)showAndHidePopUp;
- (struct CGSize)intrinsicContentSize;
- (void)updateConstraints;
- (id)initWithUniqueID:(id)arg1;

@end

