//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TDXFavoriteList : NSObject
{
    NSNumber *_id;
    NSString *_name;
    NSString *_type;
    NSArray *_items;
}

@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSNumber *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)description;
- (BOOL)hasItemId:(id)arg1;

@end

