//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TDXMenuItemRequest;

@protocol TDXFrontPageDelegate <NSObject>
- (void)openOverlayWithRequest:(TDXMenuItemRequest *)arg1 reloadEnabled:(BOOL)arg2;
- (void)openPlayerWithStreamable:(id <Streamable>)arg1;
@end

