//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, TDXMenuItemRequest, UIButton, UILabel, UIPopoverController, UITapGestureRecognizer;

__attribute__((visibility("hidden")))
@interface TDXFrontPageSectionHeaderSupplementaryView : UICollectionReusableView <UITableViewDataSource, UITableViewDelegate, UIPickerViewDataSource, UIPickerViewDelegate>
{
    UILabel *_headerTitleLabel;
    UITapGestureRecognizer *_headerTitleTapGestureRecognizer;
    UIButton *_showAllBtn;
    UIButton *_filterBtn;
    UIPopoverController *_popoverController;
    TDXMenuItemRequest *_request;
    unsigned int _selectedFilterIndex;
    id <TDXFrontPageSectionHeaderViewDelegate> _delegate;
}

+ (id)kind;
+ (id)identifier;
@property(nonatomic) __weak id <TDXFrontPageSectionHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int selectedFilterIndex; // @synthesize selectedFilterIndex=_selectedFilterIndex;
@property(retain, nonatomic) TDXMenuItemRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) UIPopoverController *popoverController; // @synthesize popoverController=_popoverController;
@property(retain, nonatomic) UIButton *filterBtn; // @synthesize filterBtn=_filterBtn;
@property(retain, nonatomic) UIButton *showAllBtn; // @synthesize showAllBtn=_showAllBtn;
@property(retain, nonatomic) UITapGestureRecognizer *headerTitleTapGestureRecognizer; // @synthesize headerTitleTapGestureRecognizer=_headerTitleTapGestureRecognizer;
@property(retain, nonatomic) UILabel *headerTitleLabel; // @synthesize headerTitleLabel=_headerTitleLabel;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)pickerView:(id)arg1 viewForRow:(int)arg2 forComponent:(int)arg3 reusingView:(id)arg4;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)configureWithMenuItemRequest:(id)arg1 andSelectedFilterRequest:(id)arg2 andForceHideSectionTitle:(BOOL)arg3 andForceHideShowAllButton:(BOOL)arg4 withDelegate:(id)arg5;
- (void)didPressFilterButton;
- (void)didPressShowAll;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

