//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "TDXCell.h"

@class NSString, UIImageViewAligned;

__attribute__((visibility("hidden")))
@interface TDXFrontPageChannelCell : UICollectionViewCell <TDXCell>
{
    UIImageViewAligned *_channelLogoImg;
    struct CGSize _channelLogoSize;
}

+ (id)identifier;
@property(nonatomic) struct CGSize channelLogoSize; // @synthesize channelLogoSize=_channelLogoSize;
@property(retain, nonatomic) UIImageViewAligned *channelLogoImg; // @synthesize channelLogoImg=_channelLogoImg;
- (void).cxx_destruct;
- (void)configureForObject:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

