//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXGeoInfo : NSObject
{
    _Bool _isBlocked;
    NSString *_countryCode;
    NSString *_ipAdress;
}

@property(retain, nonatomic) NSString *ipAdress; // @synthesize ipAdress=_ipAdress;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(nonatomic) _Bool isBlocked; // @synthesize isBlocked=_isBlocked;
- (void).cxx_destruct;
- (id)description;

@end

