//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSMutableArray;

__attribute__((visibility("hidden")))
@interface TDXGuideViewModel : NSObject
{
    NSArray *_channels;
    int _activityState;
    NSDate *_firstProgramStart;
    NSDate *_lastProgramEnd;
    NSArray *_guidePages;
    NSDate *_scheduleToday;
    int _pageOffset;
    NSMutableArray *_loadedPages;
}

@property(retain, nonatomic) NSMutableArray *loadedPages; // @synthesize loadedPages=_loadedPages;
@property(nonatomic) int pageOffset; // @synthesize pageOffset=_pageOffset;
@property(readonly, nonatomic) NSDate *scheduleToday; // @synthesize scheduleToday=_scheduleToday;
@property(retain, nonatomic) NSArray *guidePages; // @synthesize guidePages=_guidePages;
@property(retain, nonatomic) NSDate *lastProgramEnd; // @synthesize lastProgramEnd=_lastProgramEnd;
@property(retain, nonatomic) NSDate *firstProgramStart; // @synthesize firstProgramStart=_firstProgramStart;
@property(nonatomic) int activityState; // @synthesize activityState=_activityState;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
- (void).cxx_destruct;
@property(readonly, nonatomic) float contentSize;
- (id)programForIndexPath:(id)arg1;
- (id)channelForSection:(int)arg1;
- (BOOL)isPageLoaded:(int)arg1;
- (void)ensurePageIsLoaded:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fillEmptyTVGuideDataSlots:(id)arg1;
- (void)mergePrograms:(id)arg1 intoChannels:(id)arg2;
- (void)fetchProgramsForChannels:(id)arg1 scheduleStart:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchInitialProgramsForChannels:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)setScheduleToday:(id)arg1;
- (BOOL)arePagesInitialized;
- (void)initializePages;
- (id)init;

@end

