//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface TDXGuideLayout : UICollectionViewLayout
{
    NSMutableDictionary *_layoutInfo;
    CDUnknownBlockType _itemAttributesForObject;
    id <TDXGuideLayoutDataSource> _dataSource;
    int _zoomedSection;
}

+ (id)channelsLayoutWithDataSource:(id)arg1;
+ (id)zoomedLayout:(id)arg1 section:(int)arg2;
@property(nonatomic) int zoomedSection; // @synthesize zoomedSection=_zoomedSection;
@property(nonatomic) __weak id <TDXGuideLayoutDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(copy, nonatomic) CDUnknownBlockType itemAttributesForObject; // @synthesize itemAttributesForObject=_itemAttributesForObject;
@property(retain, nonatomic) NSMutableDictionary *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
- (void).cxx_destruct;
- (struct CGSize)collectionViewContentSize;
- (id)attributesForIndexPath:(id)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (BOOL)isZoomed;
- (void)prepareLayout;
- (id)initWithItemAttributesBlock:(CDUnknownBlockType)arg1 dataSource:(id)arg2;

@end

