//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TDXGridLayoutAttributes : NSObject
{
    NSArray *_attributesClasses;
    float _itemWidthPortrait;
    float _itemHeightLandscape;
    float _itemHeightPortrait;
    float _itemWidthLandscape;
    int _columnsPortrait;
    int _columnsLandscape;
    float _sectionSpacePortrait;
    float _sectionSpaceLandscape;
    float _totalWidthPortrait;
    float _totalWidthLandscape;
    float _vertPaddingPortrait;
    float _vertPaddingLandscape;
}

@property(nonatomic) float vertPaddingLandscape; // @synthesize vertPaddingLandscape=_vertPaddingLandscape;
@property(nonatomic) float vertPaddingPortrait; // @synthesize vertPaddingPortrait=_vertPaddingPortrait;
@property(nonatomic) float totalWidthLandscape; // @synthesize totalWidthLandscape=_totalWidthLandscape;
@property(nonatomic) float totalWidthPortrait; // @synthesize totalWidthPortrait=_totalWidthPortrait;
@property(nonatomic) float sectionSpaceLandscape; // @synthesize sectionSpaceLandscape=_sectionSpaceLandscape;
@property(nonatomic) float sectionSpacePortrait; // @synthesize sectionSpacePortrait=_sectionSpacePortrait;
@property(nonatomic) int columnsLandscape; // @synthesize columnsLandscape=_columnsLandscape;
@property(nonatomic) int columnsPortrait; // @synthesize columnsPortrait=_columnsPortrait;
@property(nonatomic) float itemWidthLandscape; // @synthesize itemWidthLandscape=_itemWidthLandscape;
@property(nonatomic) float itemHeightPortrait; // @synthesize itemHeightPortrait=_itemHeightPortrait;
@property(nonatomic) float itemHeightLandscape; // @synthesize itemHeightLandscape=_itemHeightLandscape;
@property(nonatomic) float itemWidthPortrait; // @synthesize itemWidthPortrait=_itemWidthPortrait;
@property(retain, nonatomic) NSArray *attributesClasses; // @synthesize attributesClasses=_attributesClasses;
- (void).cxx_destruct;
- (float)totalWidth;
- (float)sectionSpace;
- (float)verticalItemPadding;
- (float)horizontalItemPadding;
- (int)itemColumns;
@property(readonly, nonatomic) float itemHeight;
@property(readonly, nonatomic) float itemWidth;
- (void)setLandscape:(int)arg1 totalWidth:(float)arg2 itemWidth:(float)arg3 itemHeight:(float)arg4 sectionSpace:(float)arg5 verticalPadding:(float)arg6;
- (void)setPortrait:(int)arg1 totalWidth:(float)arg2 itemWidth:(float)arg3 itemHeight:(float)arg4 sectionSpace:(float)arg5 verticalPadding:(float)arg6;
- (id)initWithClasses:(Class)arg1;

@end

