//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSIndexPath, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface TDXGuideZoomedSectionLayout : UICollectionViewLayout
{
    NSMutableDictionary *_layoutInfo;
    float _itemWidth;
    NSIndexPath *_moveToIndexPath;
}

+ (id)zoomedSectionLayoutWithItemWidth:(float)arg1;
@property(retain, nonatomic) NSIndexPath *moveToIndexPath; // @synthesize moveToIndexPath=_moveToIndexPath;
@property(nonatomic) float itemWidth; // @synthesize itemWidth=_itemWidth;
@property(retain, nonatomic) NSMutableDictionary *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
- (void).cxx_destruct;
- (struct CGSize)collectionViewContentSize;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;
- (id)attributesForIndexPath:(id)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (void)moveToindexPathAfterReLayout:(id)arg1;
- (id)init;

@end

