//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSArray, NSMutableDictionary, UICollectionViewLayoutAttributes;

__attribute__((visibility("hidden")))
@interface TDXGridContentLayout : UICollectionViewLayout
{
    BOOL _skipHeaders;
    NSMutableDictionary *_cellLayoutInfo;
    NSMutableDictionary *_headerLayoutInfo;
    UICollectionViewLayoutAttributes *_teaserLayoutAttributes;
    id <TDXGridLayoutDataSource> _dataSource;
    NSArray *_layoutAttributes;
    int _layoutType;
    id <TDXTeaserDelegate> _teaserDelegate;
}

@property(nonatomic) __weak id <TDXTeaserDelegate> teaserDelegate; // @synthesize teaserDelegate=_teaserDelegate;
@property(nonatomic) int layoutType; // @synthesize layoutType=_layoutType;
@property(retain, nonatomic) NSArray *layoutAttributes; // @synthesize layoutAttributes=_layoutAttributes;
@property(nonatomic) __weak id <TDXGridLayoutDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UICollectionViewLayoutAttributes *teaserLayoutAttributes; // @synthesize teaserLayoutAttributes=_teaserLayoutAttributes;
@property(retain, nonatomic) NSMutableDictionary *headerLayoutInfo; // @synthesize headerLayoutInfo=_headerLayoutInfo;
@property(retain, nonatomic) NSMutableDictionary *cellLayoutInfo; // @synthesize cellLayoutInfo=_cellLayoutInfo;
@property(nonatomic) BOOL skipHeaders; // @synthesize skipHeaders=_skipHeaders;
- (void).cxx_destruct;
- (id)collectionLayoutAttributesForItemAtIndexPath:(id)arg1;
- (float)sectionSpace:(id)arg1;
- (struct CGSize)collectionViewContentSize;
- (struct CGRect)frameForTitleHeaderAtIndexPath:(id)arg1;
- (id)teaserAttributesForIndexPath:(id)arg1;
- (id)headerAttributesForIndexPath:(id)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (float)heightOfNonCroppedTeaserWithWidth:(float)arg1;
- (float)heightOfCroppedTeaser;
- (float)heightAdjustmentForTeaser;
- (struct CGRect)frameForObjectAtIndexPath:(id)arg1;
- (id)cellAttributesForIndexPath:(id)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (id)initWithDataSource:(id)arg1 andLayoutAttributes:(id)arg2 andLayoutType:(int)arg3 andTeaserDelegate:(id)arg4;
- (id)initWithDataSource:(id)arg1 andLayoutAttributes:(id)arg2 andLayoutType:(int)arg3;

@end

