//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, NSString;

@protocol TDXGridLayoutDataSource <NSObject>
- (id <Streamable>)streamableItemForElementWithIndexPath:(NSIndexPath *)arg1;
- (NSString *)titleOfSectionWithIndex:(unsigned int)arg1;
- (unsigned int)numberOfSections;
- (unsigned int)numberOfItemsInSection:(int)arg1;

@optional
- (float)sectionSpaceWhenNoSectionInfo;
- (BOOL)hasSectionInfo:(unsigned int)arg1;
@end

