//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXGoogleAnalyticsTracker : NSObject
{
    id <GAITracker> _tracker;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <GAITracker> tracker; // @synthesize tracker=_tracker;
- (void).cxx_destruct;
- (BOOL)trackingEnabled;
- (void)customEventWithCategory:(id)arg1 andAction:(id)arg2 andLabel:(id)arg3 andValue:(id)arg4;
- (void)screenEvent:(id)arg1;
- (id)init;

@end

