//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "TDXCell.h"

@class NSString, Program, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXHorizontalGuideProgramCell : UICollectionViewCell <TDXCell>
{
    UIImageView *_playIcon;
    UIImageView *_pvrIcon;
    UILabel *_airTimeLabel;
    UILabel *_titleLabel;
    Program *_program;
}

@property(retain, nonatomic) Program *program; // @synthesize program=_program;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *airTimeLabel; // @synthesize airTimeLabel=_airTimeLabel;
@property(retain, nonatomic) UIImageView *pvrIcon; // @synthesize pvrIcon=_pvrIcon;
@property(retain, nonatomic) UIImageView *playIcon; // @synthesize playIcon=_playIcon;
- (void).cxx_destruct;
- (void)updateBackgroundColors;
- (void)configureForObject:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

