//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDXOverlayViewController.h"

#import "TDXDatePickerViewProtocol.h"
#import "TDXGuideLayoutDataSource.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDelegate.h"

@class MASConstraint, NSArray, NSString, TDXBrowseChannelComponentViewController, TDXChannelsDataSource, TDXCurrentTimeOverlayView, TDXDatePickerButton, TDXDatePickerView, TDXGuideDatePickerCollectionViewDelegate, TDXGuideLayout, TDXGuideViewModel, TDXModalActivityView, TDXTimeBarView, UICollectionView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXHorizontalGuideViewController : TDXOverlayViewController <TDXDatePickerViewProtocol, UIScrollViewDelegate, UITableViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource, TDXGuideLayoutDataSource>
{
    BOOL _isDatePickerShown;
    UICollectionView *_guideCollectionView;
    TDXGuideViewModel *_viewModel;
    UIView *_guideContainerView;
    int _guideState;
    UIView *_fadeView;
    TDXBrowseChannelComponentViewController *_browseChannelViewController;
    TDXGuideLayout *_defaultLayout;
    TDXChannelsDataSource *_channelsDataSource;
    UICollectionView *_channelsCollectionView;
    TDXTimeBarView *_timeBarView;
    TDXCurrentTimeOverlayView *_currentTimeView;
    TDXDatePickerButton *_navBarDatePickerBtn;
    TDXDatePickerView *_datePickerView;
    MASConstraint *_datePickerBottomConstraint;
    TDXGuideDatePickerCollectionViewDelegate *_datePickerCollectionViewDelegate;
    int _pageOffset;
    UILabel *_channelsTopLabel;
    TDXModalActivityView *_activityView;
    NSArray *_timeIndicatorViews;
    NSArray *_savedVisibleChannelIndexPaths;
    struct CGSize _sizeOfScrollViewBeforeRotation;
}

@property(retain, nonatomic) NSArray *savedVisibleChannelIndexPaths; // @synthesize savedVisibleChannelIndexPaths=_savedVisibleChannelIndexPaths;
@property(nonatomic) struct CGSize sizeOfScrollViewBeforeRotation; // @synthesize sizeOfScrollViewBeforeRotation=_sizeOfScrollViewBeforeRotation;
@property(retain, nonatomic) NSArray *timeIndicatorViews; // @synthesize timeIndicatorViews=_timeIndicatorViews;
@property(retain, nonatomic) TDXModalActivityView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UILabel *channelsTopLabel; // @synthesize channelsTopLabel=_channelsTopLabel;
@property(nonatomic) int pageOffset; // @synthesize pageOffset=_pageOffset;
@property(retain, nonatomic) TDXGuideDatePickerCollectionViewDelegate *datePickerCollectionViewDelegate; // @synthesize datePickerCollectionViewDelegate=_datePickerCollectionViewDelegate;
@property(retain, nonatomic) MASConstraint *datePickerBottomConstraint; // @synthesize datePickerBottomConstraint=_datePickerBottomConstraint;
@property(nonatomic) BOOL isDatePickerShown; // @synthesize isDatePickerShown=_isDatePickerShown;
@property(retain, nonatomic) TDXDatePickerView *datePickerView; // @synthesize datePickerView=_datePickerView;
@property(retain, nonatomic) TDXDatePickerButton *navBarDatePickerBtn; // @synthesize navBarDatePickerBtn=_navBarDatePickerBtn;
@property(retain, nonatomic) TDXCurrentTimeOverlayView *currentTimeView; // @synthesize currentTimeView=_currentTimeView;
@property(retain, nonatomic) TDXTimeBarView *timeBarView; // @synthesize timeBarView=_timeBarView;
@property(retain, nonatomic) UICollectionView *channelsCollectionView; // @synthesize channelsCollectionView=_channelsCollectionView;
@property(retain, nonatomic) TDXChannelsDataSource *channelsDataSource; // @synthesize channelsDataSource=_channelsDataSource;
@property(retain, nonatomic) TDXGuideLayout *defaultLayout; // @synthesize defaultLayout=_defaultLayout;
@property(retain, nonatomic) TDXBrowseChannelComponentViewController *browseChannelViewController; // @synthesize browseChannelViewController=_browseChannelViewController;
@property(retain, nonatomic) UIView *fadeView; // @synthesize fadeView=_fadeView;
@property(nonatomic) int guideState; // @synthesize guideState=_guideState;
@property(retain, nonatomic) UIView *guideContainerView; // @synthesize guideContainerView=_guideContainerView;
@property(retain, nonatomic) TDXGuideViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UICollectionView *guideCollectionView; // @synthesize guideCollectionView=_guideCollectionView;
- (void).cxx_destruct;
- (float)tvGuideWidth:(id)arg1;
- (int)numberOfSections;
- (id)collectionView:(id)arg1 objectForIndexPath:(id)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)freshGuideCollectionView;
- (int)calcPageIndex;
- (void)closeBrowseChannel;
- (void)closeZoomedView:(id)arg1;
- (void)toggleDatePickerVisibility;
- (void)scheduledRecordingsDidReload;
- (void)overlayWillClose:(id)arg1;
- (void)handleNetworkChanges;
- (void)dismissPresentedViewControllerWithIndexPath:(id)arg1;
- (void)presentLandscapeViewController;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didChangePhysicalOrientation:(id)arg1;
- (void)updateViewConstraints;
- (void)setActive;
- (void)viewDidAppear:(BOOL)arg1;
- (void)createGUI;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1;
- (void)didTapDateWithOffset:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

