//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "TDXCell.h"

@class NSString, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface TDXHorizontalGuideChannelCell : UICollectionViewCell <TDXCell>
{
    UIView *_channelLogoContainer;
    UIImageView *_channelLogoImg;
    UIView *_rightBorder;
    UIView *_fadeView;
}

@property(retain, nonatomic) UIView *fadeView; // @synthesize fadeView=_fadeView;
@property(retain, nonatomic) UIView *rightBorder; // @synthesize rightBorder=_rightBorder;
@property(retain, nonatomic) UIImageView *channelLogoImg; // @synthesize channelLogoImg=_channelLogoImg;
@property(retain, nonatomic) UIView *channelLogoContainer; // @synthesize channelLogoContainer=_channelLogoContainer;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)configureForObject:(id)arg1;
- (void)setFaded:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

