//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXKeychainWrapper : NSObject
{
}

+ (void)deleteItemFromKeychainWithIdentifier:(id)arg1;
+ (BOOL)updateKeychainValue:(id)arg1 forIdentifier:(id)arg2;
+ (BOOL)createKeychainValue:(id)arg1 forIdentifier:(id)arg2;
+ (id)keychainStringFromMatchingIdentifier:(id)arg1;
+ (id)searchKeychainCopyMatchingIdentifier:(id)arg1;
+ (id)setupSearchDirectoryForIdentifier:(id)arg1;

@end

