//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TDXKeepAliveStatus : NSObject
{
    NSString *_status;
    NSString *_expires;
    NSNumber *_expiresInHours;
}

@property(readonly, nonatomic) NSNumber *expiresInHours; // @synthesize expiresInHours=_expiresInHours;
@property(readonly, nonatomic) NSString *expires; // @synthesize expires=_expires;
@property(readonly, nonatomic) NSString *status; // @synthesize status=_status;
- (void).cxx_destruct;

@end

