//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "UIAlertViewDelegate.h"

@class TDXLoginManager;

@protocol TDXLoginManagerDelegate <NSObject, UIAlertViewDelegate>
- (void)loginDidChange:(TDXLoginManager *)arg1;
@end

