//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSTimer, TDXSession, UIAlertView, UIViewController, UserInfo;

__attribute__((visibility("hidden")))
@interface TDXLoginManager : NSObject
{
    _Bool _isRPVREnabled;
    _Bool _isReloginOnErrorsAllowed;
    id <TDXLoginManagerDelegate> _delegate;
    TDXSession *_session;
    UserInfo *_userInfo;
    NSString *_userNameForLogin;
    int _loginState;
    NSTimer *_expiryTimer;
    UIAlertView *_invalidSessionAlert;
    UIViewController *_destinationController;
}

+ (BOOL)isUserSession;
+ (id)sharedInstance;
@property(retain, nonatomic) UIViewController *destinationController; // @synthesize destinationController=_destinationController;
@property(retain, nonatomic) UIAlertView *invalidSessionAlert; // @synthesize invalidSessionAlert=_invalidSessionAlert;
@property(retain, nonatomic) NSTimer *expiryTimer; // @synthesize expiryTimer=_expiryTimer;
@property(nonatomic) int loginState; // @synthesize loginState=_loginState;
@property(nonatomic) _Bool isReloginOnErrorsAllowed; // @synthesize isReloginOnErrorsAllowed=_isReloginOnErrorsAllowed;
@property(nonatomic) _Bool isRPVREnabled; // @synthesize isRPVREnabled=_isRPVREnabled;
@property(copy, nonatomic) NSString *userNameForLogin; // @synthesize userNameForLogin=_userNameForLogin;
@property(readonly, nonatomic) UserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(readonly, nonatomic) TDXSession *session; // @synthesize session=_session;
@property(nonatomic) id <TDXLoginManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)isChannelAllowedForDVR:(id)arg1;
- (BOOL)isRPVRAvailableForStreamable:(id)arg1;
- (void)reloadUserInfoAsyncLogoutOnError:(_Bool)arg1;
- (void)sessionDidExpire;
- (void)setSessionAndCompleteLogin:(id)arg1 xmpp:(id)arg2;
- (void)loginUsingGuestLoginWithCompletion:(CDUnknownBlockType)arg1;
- (void)loginWithCredentials:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)performStartupLoginProcedureWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)cancelInitialLogin;
- (void)setToWaitForInitialLoginState;
- (void)handleGuestLoginChanges;
- (void)logoutCallServer:(_Bool)arg1;
- (void)logout;
- (id)getAndClearUserNameForLogin;
- (void)keepUserNameForLogin;
- (void)startKeepAliveTimer;
- (void)stopKeepAliveTimer;
- (void)setReloginOnErrorsAllowed:(BOOL)arg1;
- (BOOL)isLoggedIn;
- (BOOL)isAutoLoginInProgress;
@property(readonly, nonatomic) BOOL guestLoginSupported;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)HTTPOperationDidFinish:(id)arg1;
- (id)init;

@end

