//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TDXMenuDelegate.h"

@class NSArray, NSMutableArray, NSString, TDXMenuItem, TDXPrimaryMenuTableView;

__attribute__((visibility("hidden")))
@interface TDXMenuViewController : UIViewController <TDXMenuDelegate>
{
    NSMutableArray *buttons;
    TDXMenuItem *_selectedPrimaryMenuItem;
    TDXMenuItem *_selectedSecondaryMenuItem;
    NSArray *_secondaryMenuItems;
    id <TDXMenuDelegate> _delegate;
    TDXPrimaryMenuTableView *_primaryMenuTableView;
    NSArray *_primaryMenuItems;
}

@property(retain, nonatomic) NSArray *primaryMenuItems; // @synthesize primaryMenuItems=_primaryMenuItems;
@property(retain, nonatomic) TDXPrimaryMenuTableView *primaryMenuTableView; // @synthesize primaryMenuTableView=_primaryMenuTableView;
@property(nonatomic) __weak id <TDXMenuDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *secondaryMenuItems; // @synthesize secondaryMenuItems=_secondaryMenuItems;
@property(retain, nonatomic) TDXMenuItem *selectedSecondaryMenuItem; // @synthesize selectedSecondaryMenuItem=_selectedSecondaryMenuItem;
@property(retain, nonatomic) TDXMenuItem *selectedPrimaryMenuItem; // @synthesize selectedPrimaryMenuItem=_selectedPrimaryMenuItem;
- (void).cxx_destruct;
- (void)setupWithMenuItems:(id)arg1;
- (void)primaryMenuItemWasPressed:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

