//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class TDXMainContentView, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface TDXMainContentViewController : UIViewController
{
    int topBarStyle;
    UIPanGestureRecognizer *panGesture;
    UITapGestureRecognizer *tapGesture;
    UIView *modalView;
    float startWindowOffset;
    struct CGPoint startDragPoint;
}

- (void).cxx_destruct;
- (void)removeBlockerView;
- (void)addBlockerView;
- (void)didSelectStreamableItemNotification:(id)arg1;
- (void)didTapModalView:(id)arg1;
- (void)panDidTrigger:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)loadView;
- (void)overlayWillClose:(id)arg1;
- (id)initWithStyle:(int)arg1;
- (id)init;
@property(readonly, nonatomic) TDXMainContentView *mainContentView;

@end

