//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UIActivityIndicatorView, UITextView;

__attribute__((visibility("hidden")))
@interface TDXModalActivityView : UIView
{
    UIActivityIndicatorView *_activityIndicatorView;
    UITextView *_messageView;
    NSTimer *_messageTimer;
}

@property(retain, nonatomic) NSTimer *messageTimer; // @synthesize messageTimer=_messageTimer;
@property(retain, nonatomic) UITextView *messageView; // @synthesize messageView=_messageView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
- (void).cxx_destruct;
- (void)startSpinnerAfterDelayInSec:(float)arg1;
- (void)hideMessage;
- (void)showMessage:(id)arg1;
- (void)showCurrentMessage;
- (void)showMessage:(id)arg1 afterSec:(float)arg2;
- (void)updateConstraints;
- (id)initWithGrayedOutView:(BOOL)arg1;
- (id)init;

@end

