//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXMainContentView : UIView
{
    UIImageView *_topBarView;
    UIImageView *_contentView;
    UIButton *_burgerBtn;
    UILabel *_titleLabel;
    UIButton *_closeBtn;
}

@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *burgerBtn; // @synthesize burgerBtn=_burgerBtn;
@property(retain, nonatomic) UIImageView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImageView *topBarView; // @synthesize topBarView=_topBarView;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)addStandardUI;
- (void)addCloseButtonWithRACCommand:(id)arg1;
- (void)addBurgerButtonWithRACCommand:(id)arg1;
- (id)init;

@end

