//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TDXMenuItem : NSObject
{
    _Bool _enabled;
    NSString *_title;
    NSString *_typeName;
    NSNumber *_position;
    NSString *_guid;
    NSString *_action;
    NSArray *_requests;
    NSArray *_children;
}

@property(copy, nonatomic) NSArray *children; // @synthesize children=_children;
@property(retain, nonatomic) NSArray *requests; // @synthesize requests=_requests;
@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) NSNumber *position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) unsigned int type;

@end

