//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TDXNowAndNext : NSObject
{
    NSArray *_nowPrograms;
    NSArray *_nextPrograms;
}

@property(readonly, nonatomic) NSArray *nextPrograms; // @synthesize nextPrograms=_nextPrograms;
@property(readonly, nonatomic) NSArray *nowPrograms; // @synthesize nowPrograms=_nowPrograms;
- (void).cxx_destruct;
- (id)nextProgram;
- (id)currentProgram;

@end

