//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDXOverlayViewController.h"

@class NSURL, TDXWebView;

__attribute__((visibility("hidden")))
@interface TDXOverlayWebViewController : TDXOverlayViewController
{
    TDXWebView *_webView;
    NSURL *_webViewURL;
}

@property(copy, nonatomic) NSURL *webViewURL; // @synthesize webViewURL=_webViewURL;
@property(retain, nonatomic) TDXWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)updateViewConstraints;
- (void)viewDidLoad;
- (id)initWithURLString:(id)arg1;

@end

