//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPageViewControllerDataSource.h"
#import "UIPageViewControllerDelegate.h"

@class NSMutableArray, NSString, UIButton, UIPageControl, UIPageViewController;

__attribute__((visibility("hidden")))
@interface TDXOnboardingViewController : UIViewController <UIPageViewControllerDataSource, UIPageViewControllerDelegate>
{
    UIButton *_closeButton;
    UIPageControl *_pageControl;
    UIPageViewController *_pageViewController;
    NSMutableArray *_onboardingViewControllers;
}

@property(retain, nonatomic) NSMutableArray *onboardingViewControllers; // @synthesize onboardingViewControllers=_onboardingViewControllers;
@property(retain, nonatomic) UIPageViewController *pageViewController; // @synthesize pageViewController=_pageViewController;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)pageViewController:(id)arg1 didFinishAnimating:(BOOL)arg2 previousViewControllers:(id)arg3 transitionCompleted:(BOOL)arg4;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidAppear:(BOOL)arg1;
- (id)urlForPage:(int)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

