//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSArray, NSString, UIButton;

__attribute__((visibility("hidden")))
@interface TDXPickerModalView : UIView <UIPickerViewDataSource, UIPickerViewDelegate>
{
    NSArray *_items;
    UIView *_pickerContainerView;
    UIButton *_pickerOkButton;
    UIView *_dstView;
}

@property(retain, nonatomic) UIView *dstView; // @synthesize dstView=_dstView;
@property(retain, nonatomic) UIButton *pickerOkButton; // @synthesize pickerOkButton=_pickerOkButton;
@property(retain, nonatomic) UIView *pickerContainerView; // @synthesize pickerContainerView=_pickerContainerView;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (id)pickerView:(id)arg1 viewForRow:(int)arg2 forComponent:(int)arg3 reusingView:(id)arg4;
- (void)show;
- (id)initWithItems:(id)arg1 andInitialSelectionIndex:(unsigned int)arg2 andSelectionCompletedBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

