//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TDXMenuItem, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXPrimaryMenuCell : UITableViewCell
{
    TDXMenuItem *_menuItem;
    UILabel *_titleLabel;
    UIImageView *_menuImageNormal;
    UIImageView *_menuImageSelected;
    UIView *_leftBorder;
    UIView *_rightBorder;
}

+ (id)identifier;
@property(retain, nonatomic) UIView *rightBorder; // @synthesize rightBorder=_rightBorder;
@property(retain, nonatomic) UIView *leftBorder; // @synthesize leftBorder=_leftBorder;
@property(retain, nonatomic) UIImageView *menuImageSelected; // @synthesize menuImageSelected=_menuImageSelected;
@property(retain, nonatomic) UIImageView *menuImageNormal; // @synthesize menuImageNormal=_menuImageNormal;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) TDXMenuItem *menuItem; // @synthesize menuItem=_menuItem;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)configureWithItem:(id)arg1 andImage:(id)arg2 andSelectedImage:(id)arg3;
- (void)updateConstraints;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

