//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TDXPlayerControlViewDelegate.h"

@class MPMoviePlayerController, NSDate, NSMutableDictionary, NSString, SpringStreamsAdapter, Stream, TDXModalActivityView, TDXPlayerBottomControlView, TDXPlayerTopControlView, TDXPlayerViewModel, TDXTouchForwarderView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXPlayerComponentViewController : UIViewController <TDXPlayerControlViewDelegate>
{
    BOOL _startInFullScreen;
    id <Streamable> _streamingItem;
    TDXPlayerViewModel *_viewModel;
    MPMoviePlayerController *_moviePlayerController;
    TDXPlayerBottomControlView *_bottomControlView;
    TDXPlayerTopControlView *_topControlView;
    TDXTouchForwarderView *_touchForwarderView;
    NSDate *_dateWhenStartedOverStreamStarted;
    TDXModalActivityView *_playerActivityView;
    TDXModalActivityView *_prePlayingActivityView;
    CDUnknownBlockType _endPlayAction;
    SpringStreamsAdapter *_springStreamsAdapter;
    NSMutableDictionary *_springStreamsAttributes;
    Stream *_springStreamsStream;
    id <TDXPlayerContainerFullScreenDelegate> _fullScreenDelegate;
    UILabel *_airPlayMessage;
}

@property(retain, nonatomic) UILabel *airPlayMessage; // @synthesize airPlayMessage=_airPlayMessage;
@property(nonatomic) __weak id <TDXPlayerContainerFullScreenDelegate> fullScreenDelegate; // @synthesize fullScreenDelegate=_fullScreenDelegate;
@property(retain, nonatomic) Stream *springStreamsStream; // @synthesize springStreamsStream=_springStreamsStream;
@property(retain, nonatomic) NSMutableDictionary *springStreamsAttributes; // @synthesize springStreamsAttributes=_springStreamsAttributes;
@property(retain, nonatomic) SpringStreamsAdapter *springStreamsAdapter; // @synthesize springStreamsAdapter=_springStreamsAdapter;
@property(copy, nonatomic) CDUnknownBlockType endPlayAction; // @synthesize endPlayAction=_endPlayAction;
@property(retain, nonatomic) TDXModalActivityView *prePlayingActivityView; // @synthesize prePlayingActivityView=_prePlayingActivityView;
@property(retain, nonatomic) TDXModalActivityView *playerActivityView; // @synthesize playerActivityView=_playerActivityView;
@property(retain, nonatomic) NSDate *dateWhenStartedOverStreamStarted; // @synthesize dateWhenStartedOverStreamStarted=_dateWhenStartedOverStreamStarted;
@property(retain, nonatomic) TDXTouchForwarderView *touchForwarderView; // @synthesize touchForwarderView=_touchForwarderView;
@property(retain, nonatomic) TDXPlayerTopControlView *topControlView; // @synthesize topControlView=_topControlView;
@property(retain, nonatomic) TDXPlayerBottomControlView *bottomControlView; // @synthesize bottomControlView=_bottomControlView;
@property(retain, nonatomic) MPMoviePlayerController *moviePlayerController; // @synthesize moviePlayerController=_moviePlayerController;
@property(nonatomic) __weak TDXPlayerViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) BOOL startInFullScreen; // @synthesize startInFullScreen=_startInFullScreen;
@property(retain, nonatomic) id <Streamable> streamingItem; // @synthesize streamingItem=_streamingItem;
- (void).cxx_destruct;
- (void)dealloc;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)movieMediaTypesAvailable:(id)arg1;
- (void)movieMediaLoadStateChanged:(id)arg1;
- (void)movieMediaPlayStateChanged:(id)arg1;
- (void)playbackDidFinish:(id)arg1;
- (void)moviePlayerReadyForDisplayDidChange:(id)arg1;
- (void)handleScreenDisconnectOrEnteredBackgroundNotification:(id)arg1;
- (void)handleScreenConnectOrEnteredForegroundNotification:(id)arg1;
- (void)failedGettingStreamUrl:(id)arg1;
- (void)playbackDidFinishWithError:(id)arg1;
- (void)controlViewDidPressSkipForwardBtn:(id)arg1;
- (void)controlViewDidPressSkipBackBtn:(id)arg1;
- (void)controlViewDidPressStartOverBtn:(id)arg1;
- (void)controlViewDidPressFullScreenBtn:(id)arg1;
- (void)controlViewDidPressPlayPauseBtn:(id)arg1;
- (void)controlViewDidPressAnyButton:(id)arg1;
- (BOOL)isPlayerFullscreen;
- (void)updateTimeLabels;
- (id)springStreamLiveID;
- (id)springStreamOnDemandID;
- (id)createTouchForwarderView;
- (void)resetPlaybackTime;
- (void)prepareResettingPlaybackTime:(id)arg1;
- (void)startCurrentStreamOver;
- (BOOL)streamHasReachedEnd;
- (void)saveProgressWithCompletion:(CDUnknownBlockType)arg1;
- (void)handleEnterForeground;
- (void)handleNetworkChanges;
- (void)exitFullScreenWithCompletion:(CDUnknownBlockType)arg1;
- (void)goToFullScreen;
- (void)didChangePhysicalOrientation:(id)arg1;
- (void)updateViewConstraints;
- (void)playerOverlayWillClose;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidLoad;
- (void)setupPlayerWithURL:(id)arg1 startedOver:(BOOL)arg2;
- (id)initWithViewModel:(id)arg1 andEndPlayAction:(CDUnknownBlockType)arg2 andFullScreenDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

