//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface TDXProgramVerticalView : UIView
{
    UILabel *_airTimeAndTitleLabel;
}

+ (BOOL)requiresConstraintBasedLayout;
@property(retain, nonatomic) UILabel *airTimeAndTitleLabel; // @synthesize airTimeAndTitleLabel=_airTimeAndTitleLabel;
- (void).cxx_destruct;
- (void)configureWithProgram:(id)arg1;
- (id)init;

@end

