//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@protocol TDXPlayerControlViewDelegate <NSObject>
- (BOOL)isPlayerFullscreen;
- (void)controlViewDidPressAnyButton:(UIView *)arg1;
- (void)controlViewDidPressSkipForwardBtn:(UIView *)arg1;
- (void)controlViewDidPressSkipBackBtn:(UIView *)arg1;
- (void)controlViewDidPressStartOverBtn:(UIView *)arg1;
- (void)controlViewDidPressFullScreenBtn:(UIView *)arg1;
- (void)controlViewDidPressPlayPauseBtn:(UIView *)arg1;
@end

