//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface TDXProgressManager : NSObject
{
    NSMutableDictionary *_progressForMoviesAndTvShowEpisodes;
    NSMutableDictionary *_progressForPrograms;
}

+ (BOOL)progressEnabled;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *progressForPrograms; // @synthesize progressForPrograms=_progressForPrograms;
@property(retain, nonatomic) NSMutableDictionary *progressForMoviesAndTvShowEpisodes; // @synthesize progressForMoviesAndTvShowEpisodes=_progressForMoviesAndTvShowEpisodes;
- (void).cxx_destruct;
- (void)clearProgress;
- (void)updateProgressCacheForStreambleId:(id)arg1 withType:(int)arg2 progress:(id)arg3;
- (void)setProgressInSeconds:(int)arg1 forStreamable:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)refreshProgressForStreamableId:(id)arg1 withType:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)refreshProgressForStreamable:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)progressForStreamable:(id)arg1;
- (void)prefetchProgress;

@end

