//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MPVolumeView, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXPlayerTopControlView : UIView
{
    id <TDXPlayerControlViewDelegate> _delegate;
    MPVolumeView *_volumeView;
    UIView *_containerView;
    UIButton *_backBtn;
    UILabel *_titleLabel;
    UIImageView *_volumeIcon;
    UIView *_statusBarView;
    UIImageView *_volumeSliderThumbBackground;
}

@property(retain, nonatomic) UIImageView *volumeSliderThumbBackground; // @synthesize volumeSliderThumbBackground=_volumeSliderThumbBackground;
@property(retain, nonatomic) UIView *statusBarView; // @synthesize statusBarView=_statusBarView;
@property(retain, nonatomic) UIImageView *volumeIcon; // @synthesize volumeIcon=_volumeIcon;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MPVolumeView *volumeView; // @synthesize volumeView=_volumeView;
@property(nonatomic) __weak id <TDXPlayerControlViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)delayHidingWithSeconds:(double)arg1;
- (void)configureWithStreamable:(id)arg1;
- (void)hide;
- (void)show;
- (void)updateControls;
- (void)didTapBackButton;
- (void)updateConstraints;
- (void)layoutSubviews;
- (struct CGRect)thumbAlignedForSlider:(id)arg1 andSourceSize:(struct CGSize)arg2;
- (void)setup;
- (id)init;

@end

