//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSAttributedString, NSDictionary;

__attribute__((visibility("hidden")))
@interface TDXProgressView : UIView
{
    NSAttributedString *_stringLeft;
    NSAttributedString *_stringRight;
    NSDictionary *_fontAttributes;
    float _progressFactor;
    float _progressHeight;
}

@property(nonatomic) float progressHeight; // @synthesize progressHeight=_progressHeight;
@property(nonatomic) float progressFactor; // @synthesize progressFactor=_progressFactor;
@property(retain, nonatomic) NSDictionary *fontAttributes; // @synthesize fontAttributes=_fontAttributes;
@property(copy, nonatomic) NSAttributedString *stringRight; // @synthesize stringRight=_stringRight;
@property(copy, nonatomic) NSAttributedString *stringLeft; // @synthesize stringLeft=_stringLeft;
- (void).cxx_destruct;
- (void)setProgress:(id)arg1 andTotalLengthInMinutes:(id)arg2 leftLabel:(id)arg3 rightLabel:(id)arg4;
- (void)setProgress:(id)arg1 andTotalLengthInMinutes:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)setUp;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initForLandscapeCoverWithWidth:(float)arg1;
- (id)initForMovieCoverWithWidth:(float)arg1;

@end

