//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDXOverlayViewController.h"

#import "TDXPlayerContainerFullScreenDelegate.h"
#import "TDXSynopsisViewDelegate.h"

@class NSArray, NSString, RACDisposable, TDXCoverComponentViewController, TDXModalActivityView, TDXPlayerComponentViewController, TDXPlayerViewModel, TDXSidebarComponentViewController, TDXSynopsisComponentViewController, UIScrollView, UIView;

__attribute__((visibility("hidden")))
@interface TDXPlayerContainerViewController : TDXOverlayViewController <TDXPlayerContainerFullScreenDelegate, TDXSynopsisViewDelegate>
{
    TDXPlayerViewModel *_viewModel;
    TDXSidebarComponentViewController *_sidebarComponentViewController;
    TDXPlayerComponentViewController *_playerComponentViewController;
    TDXSynopsisComponentViewController *_synopsisComponentViewController;
    TDXCoverComponentViewController *_coverComponentViewController;
    UIScrollView *_containerView;
    UIView *_playerCoverView;
    UIView *_synopsisView;
    UIView *_relatedView;
    TDXModalActivityView *_scheduleRecordingActivityView;
    NSArray *_constraints;
    id <Streamable> _previousStreamingItem;
    RACDisposable *_liveTvUpdateSubscription;
}

@property(retain, nonatomic) RACDisposable *liveTvUpdateSubscription; // @synthesize liveTvUpdateSubscription=_liveTvUpdateSubscription;
@property(retain, nonatomic) id <Streamable> previousStreamingItem; // @synthesize previousStreamingItem=_previousStreamingItem;
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
@property(retain, nonatomic) TDXModalActivityView *scheduleRecordingActivityView; // @synthesize scheduleRecordingActivityView=_scheduleRecordingActivityView;
@property(retain, nonatomic) UIView *relatedView; // @synthesize relatedView=_relatedView;
@property(retain, nonatomic) UIView *synopsisView; // @synthesize synopsisView=_synopsisView;
@property(retain, nonatomic) UIView *playerCoverView; // @synthesize playerCoverView=_playerCoverView;
@property(retain, nonatomic) UIScrollView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) TDXCoverComponentViewController *coverComponentViewController; // @synthesize coverComponentViewController=_coverComponentViewController;
@property(retain, nonatomic) TDXSynopsisComponentViewController *synopsisComponentViewController; // @synthesize synopsisComponentViewController=_synopsisComponentViewController;
@property(retain, nonatomic) TDXPlayerComponentViewController *playerComponentViewController; // @synthesize playerComponentViewController=_playerComponentViewController;
@property(retain, nonatomic) TDXSidebarComponentViewController *sidebarComponentViewController; // @synthesize sidebarComponentViewController=_sidebarComponentViewController;
@property(retain, nonatomic) TDXPlayerViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)didFinishSchedulingRecording:(id)arg1;
- (void)didInitiateRecordingChange:(id)arg1;
- (void)dealloc;
- (void)handleBingeViewing;
- (void)setChildViewController:(id)arg1 targetView:(id)arg2;
- (void)removeChildViewControllerFromContainer:(id)arg1;
- (void)stopPlayingAndDisplayNewCover;
- (void)playItemInFullScreen:(BOOL)arg1;
- (BOOL)isPlayerActive;
- (void)handleEnterForeground;
- (void)handleNetworkChanges;
- (void)overlayWillClose:(id)arg1;
- (id)addLandscapeConstraints;
- (id)addPortraitConstraints;
- (void)updateViewConstraints;
- (void)dismissFullScreenViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentFullScreenViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)startListeningForChangesToViewModel;
- (void)reloadLiveTVInformation;
- (void)setUpWithStreamable:(id)arg1;
- (void)setStreamableItem:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

