//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UIImage, UIImageView, UILabel, UISlider, UISwipeGestureRecognizer;

__attribute__((visibility("hidden")))
@interface TDXPlayerBottomControlView : UIView
{
    UISlider *_playbackProgressSlider;
    UILabel *_playbackTimeLabel;
    UILabel *_playbackTimeLeftLabel;
    id <TDXPlayerControlViewDelegate> _delegate;
    float _controlHeight;
    int _playerControlsState;
    UISwipeGestureRecognizer *_playbackProgressSliderSwipeRecognizer;
    UIView *_sliderBlockerView;
    UIImageView *_playbackProgressSliderThumbBackground;
    UIButton *_playPauseBtn;
    UIButton *_fullScreenBtn;
    UIButton *_startOverBtn;
    UIButton *_skipBackBtn;
    UIButton *_skipForwardBtn;
    UIView *_containerView;
}

@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *skipForwardBtn; // @synthesize skipForwardBtn=_skipForwardBtn;
@property(retain, nonatomic) UIButton *skipBackBtn; // @synthesize skipBackBtn=_skipBackBtn;
@property(retain, nonatomic) UIButton *startOverBtn; // @synthesize startOverBtn=_startOverBtn;
@property(retain, nonatomic) UIButton *fullScreenBtn; // @synthesize fullScreenBtn=_fullScreenBtn;
@property(retain, nonatomic) UIButton *playPauseBtn; // @synthesize playPauseBtn=_playPauseBtn;
@property(retain, nonatomic) UIImageView *playbackProgressSliderThumbBackground; // @synthesize playbackProgressSliderThumbBackground=_playbackProgressSliderThumbBackground;
@property(retain, nonatomic) UIView *sliderBlockerView; // @synthesize sliderBlockerView=_sliderBlockerView;
@property(retain, nonatomic) UISwipeGestureRecognizer *playbackProgressSliderSwipeRecognizer; // @synthesize playbackProgressSliderSwipeRecognizer=_playbackProgressSliderSwipeRecognizer;
@property(nonatomic) int playerControlsState; // @synthesize playerControlsState=_playerControlsState;
@property(nonatomic) float controlHeight; // @synthesize controlHeight=_controlHeight;
@property(nonatomic) __weak id <TDXPlayerControlViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *playbackTimeLeftLabel; // @synthesize playbackTimeLeftLabel=_playbackTimeLeftLabel;
@property(retain, nonatomic) UILabel *playbackTimeLabel; // @synthesize playbackTimeLabel=_playbackTimeLabel;
@property(retain, nonatomic) UISlider *playbackProgressSlider; // @synthesize playbackProgressSlider=_playbackProgressSlider;
- (void).cxx_destruct;
- (void)delayHidingWithSeconds:(double)arg1;
- (void)hide;
- (void)show;
- (void)updateControls;
@property(retain, nonatomic) UIImage *playbackTimeSliderThumbImage;
@property(copy, nonatomic) NSString *playPauseBtnTitle;
- (void)playbackProgressSliderPressedWhenNotAllowed;
- (BOOL)showPlaybackProgressSliderThumbBackground;
- (void)updateConstraints;
- (float)currentHeight;
- (struct CGRect)thumbAlignedForSlider:(id)arg1 andSourceSize:(struct CGSize)arg2;
- (void)setup;
- (id)init;

@end

