//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class StreamURL, TVShow;

__attribute__((visibility("hidden")))
@interface TDXPlayerViewModel : NSObject
{
    BOOL _bingeViewing;
    BOOL _liveTvAutoPlay;
    id <Streamable> _currentStreamingItem;
    TVShow *_tvShow;
    StreamURL *_currentStreamUrl;
}

@property(nonatomic) BOOL liveTvAutoPlay; // @synthesize liveTvAutoPlay=_liveTvAutoPlay;
@property(nonatomic) BOOL bingeViewing; // @synthesize bingeViewing=_bingeViewing;
@property(retain, nonatomic) StreamURL *currentStreamUrl; // @synthesize currentStreamUrl=_currentStreamUrl;
@property(retain, nonatomic) TVShow *tvShow; // @synthesize tvShow=_tvShow;
@property(retain, nonatomic) id <Streamable> currentStreamingItem; // @synthesize currentStreamingItem=_currentStreamingItem;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL canUserStartOver;
@property(readonly, nonatomic) struct CGSize playerCoverSize;
- (BOOL)shouldAutoPlayLiveTv;
- (BOOL)canBingeCurrentStreamingItem;
- (BOOL)isPlayableItem;
- (id)streamableTitle;

@end

