//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface TDXPrimaryMenuTableView : UITableView <UITableViewDataSource, UITableViewDelegate>
{
    NSArray *_primaryMenuItems;
    id <TDXMenuDelegate> _menuDelegate;
    NSMutableDictionary *_menuImagesDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *menuImagesDictionary; // @synthesize menuImagesDictionary=_menuImagesDictionary;
@property(nonatomic) __weak id <TDXMenuDelegate> menuDelegate; // @synthesize menuDelegate=_menuDelegate;
@property(retain, nonatomic) NSArray *primaryMenuItems; // @synthesize primaryMenuItems=_primaryMenuItems;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)layoutSubviews;
- (void)updateConstraints;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

