//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TDXRequest.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXRequestTVShow : NSObject <TDXRequest>
{
}

+ (void)tvShowProgressFor:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)tvShowInfoForSearchResult:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)tvShowInfoForId:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)tvShowInfoFor:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (id)responseDescriptor;
+ (id)basePath;
+ (id)objectMapping;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

