//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TDXRequest.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXRequestBookmarks : NSObject <TDXRequest>
{
}

+ (id)stringForType:(int)arg1;
+ (id)paramsWithProgressType:(int)arg1;
+ (void)requestBookmarkWithType:(int)arg1 forId:(id)arg2 andCompletion:(CDUnknownBlockType)arg3;
+ (void)requestBookmarksWithType:(int)arg1 andCompletion:(CDUnknownBlockType)arg2;
+ (void)postBookmarkForType:(int)arg1 withContentId:(id)arg2 andSeconds:(int)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)responseDescriptor;
+ (id)basePath;
+ (id)objectMapping;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

