//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TDXRequest.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXRequestTVGuidePrograms : NSObject <TDXRequest>
{
}

+ (void)tvguideProgramsForChannels:(id)arg1 scheduleStart:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)tvguideInitialProgramsForChannels:(id)arg1 scheduleStart:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)mapProgramsFromResponse:(id)arg1;
+ (id)mapToProgram:(id)arg1;
+ (id)channelsIdsParameterValue:(id)arg1;
+ (id)parametersWithChannels:(id)arg1 andScheduleStart:(id)arg2;
+ (id)initialPageParametersWithChannels:(id)arg1 andScheduleStart:(id)arg2;
+ (id)responseDescriptor;
+ (id)basePath;
+ (id)objectMapping;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

