//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TDXRequest.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXRequestFavoriteList : NSObject <TDXRequest>
{
}

+ (id)favoriteTypeAsString:(int)arg1;
+ (void)removeFavoriteItem:(id)arg1 withType:(int)arg2 completion:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)favoriteItem:(id)arg1 withType:(int)arg2 completion:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)favoritesForType:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (id)parametersWithType:(id)arg1;
+ (id)responseDescriptor;
+ (id)objectMapping;
+ (id)basePath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

