//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface TDXRPVRManager : NSObject
{
    NSTimer *_delayTimer;
    int _delayedModeToSchedule;
    NSString *_delayedEPGIdToSchedule;
    NSMutableDictionary *_schedulesPrograms;
    NSMutableDictionary *_schedulesSeries;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *schedulesSeries; // @synthesize schedulesSeries=_schedulesSeries;
@property(retain, nonatomic) NSMutableDictionary *schedulesPrograms; // @synthesize schedulesPrograms=_schedulesPrograms;
@property(retain, nonatomic) NSString *delayedEPGIdToSchedule; // @synthesize delayedEPGIdToSchedule=_delayedEPGIdToSchedule;
@property(nonatomic) int delayedModeToSchedule; // @synthesize delayedModeToSchedule=_delayedModeToSchedule;
@property(retain, nonatomic) NSTimer *delayTimer; // @synthesize delayTimer=_delayTimer;
- (void).cxx_destruct;
- (void)clearScheduleRecordings;
- (void)delayTimerWasTriggeredSucces:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)scheduleRecordingWithEPGId:(id)arg1 andRecordingMode:(int)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (int)getScheduledRecordingModeForProgramWithEPGID:(id)arg1;
- (void)reloadScheduleRecordings;

@end

