//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXRequestTVGuideProgram : NSObject
{
}

+ (void)programInfoFor:(id)arg1 withSuccess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)responseDescriptor;
+ (id)objectMapping;
+ (id)basePath;

@end

