//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXRestrictionView : UIView
{
    UIImageView *_restrictionImageView;
    UILabel *_restrictionLabel;
    float _fontSize;
    int _imageSize;
}

@property(nonatomic) int imageSize; // @synthesize imageSize=_imageSize;
@property(nonatomic) float fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) UILabel *restrictionLabel; // @synthesize restrictionLabel=_restrictionLabel;
@property(retain, nonatomic) UIImageView *restrictionImageView; // @synthesize restrictionImageView=_restrictionImageView;
- (void).cxx_destruct;
- (void)updateConstraints;
- (BOOL)showLimitedToHome:(id)arg1 andProgram:(id)arg2;
- (void)configureWithStreamable:(id)arg1;
- (id)initWithRestrictionImageSize:(int)arg1 andFontSize:(float)arg2;

@end

