//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSTimer, TDXSplashScreenView;

__attribute__((visibility("hidden")))
@interface TDXRootViewController : UIViewController
{
    _Bool _showLogoOnSplash;
    TDXSplashScreenView *_splashView;
    NSTimer *_splashTimer;
}

@property(retain, nonatomic) NSTimer *splashTimer; // @synthesize splashTimer=_splashTimer;
@property(nonatomic) _Bool showLogoOnSplash; // @synthesize showLogoOnSplash=_showLogoOnSplash;
@property(retain, nonatomic) TDXSplashScreenView *splashView; // @synthesize splashView=_splashView;
- (void).cxx_destruct;
- (void)setSplashVisibility:(_Bool)arg1 showLogo:(_Bool)arg2 animatedRemoval:(_Bool)arg3;
- (void)showSplashWithUserInfo:(id)arg1;
- (void)showSplashAfterDelay:(float)arg1 logo:(_Bool)arg2;
- (void)didEnterBackground;
- (void)didReceiveMemoryWarning;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (id)init;

@end

