//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXRequestCMSText : NSObject
{
}

+ (id)mapCMSTextFromResponse:(id)arg1;
+ (id)removeUnusedTags:(id)arg1;
+ (void)requestCMSTextForUrl:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

