//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TDXGridLayoutDataSource.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface TDXSearchViewModel : NSObject <TDXGridLayoutDataSource>
{
    NSString *_currentSearchString;
    NSDictionary *_searchResults;
}

@property(retain, nonatomic) NSDictionary *searchResults; // @synthesize searchResults=_searchResults;
@property(copy, nonatomic) NSString *currentSearchString; // @synthesize currentSearchString=_currentSearchString;
- (void).cxx_destruct;
- (int)numberOfAllItems;
- (id)keyForSectionIndex:(int)arg1;
- (float)heightForHeaderInSection:(int)arg1;
- (id)titleOfSectionWithIndex:(unsigned int)arg1;
- (id)streamableItemForElementWithIndexPath:(id)arg1;
- (unsigned int)numberOfSections;
- (unsigned int)numberOfItemsInSection:(int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

