//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TDXFavoritePopUpView, TDXRecordingModeSelectionView, TDXSynopsisBottomView, TDXSynopsisComponentViewController, TDXSynopsisSummaryView, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXSynopsisView : UIView
{
    id <TDXSynopsisViewDelegate> _synopsViewDelegate;
    TDXSynopsisComponentViewController *_controller;
    UIImageView *_channelLogoImg;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_recordButton;
    int _recordButtonState;
    UIButton *_favoriteButton;
    TDXSynopsisSummaryView *_summaryView;
    TDXSynopsisBottomView *_bottomView;
    id <Streamable> _streamable;
    TDXRecordingModeSelectionView *_recordingModeSelectionView;
    TDXFavoritePopUpView *_favoritePopUp;
}

@property(retain, nonatomic) TDXFavoritePopUpView *favoritePopUp; // @synthesize favoritePopUp=_favoritePopUp;
@property(retain, nonatomic) TDXRecordingModeSelectionView *recordingModeSelectionView; // @synthesize recordingModeSelectionView=_recordingModeSelectionView;
@property(retain, nonatomic) id <Streamable> streamable; // @synthesize streamable=_streamable;
@property(retain, nonatomic) TDXSynopsisBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) TDXSynopsisSummaryView *summaryView; // @synthesize summaryView=_summaryView;
@property(retain, nonatomic) UIButton *favoriteButton; // @synthesize favoriteButton=_favoriteButton;
@property(nonatomic) int recordButtonState; // @synthesize recordButtonState=_recordButtonState;
@property(retain, nonatomic) UIButton *recordButton; // @synthesize recordButton=_recordButton;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *channelLogoImg; // @synthesize channelLogoImg=_channelLogoImg;
@property(nonatomic) __weak TDXSynopsisComponentViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) id <TDXSynopsisViewDelegate> synopsViewDelegate; // @synthesize synopsViewDelegate=_synopsViewDelegate;
- (void).cxx_destruct;
- (void)favoriteButtonClicked;
- (void)updateFavorite:(BOOL)arg1;
- (void)configureWithMovie:(id)arg1;
- (void)configureWithTvShowEpisode:(id)arg1;
- (void)configureWithProgram:(id)arg1;
- (void)configureWithStreamable:(id)arg1;
- (void)updateConstraints;
- (void)alignChannelImage;
- (void)didPressRecordButton;
- (void)setup;
- (id)initWithViewController:(id)arg1;

@end

