//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UIButton, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXServiceMessageViewController : UIViewController
{
    UIImageView *icon;
    UILabel *label;
    UIButton *btnClose;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *text;
- (void)animateDismiss;
- (void)animateShow;
- (void)updateViewConstraints;
- (void)loadView;
- (id)init;

@end

