//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Streamable.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface TDXSearchResult : NSObject <Streamable>
{
    NSString *_id;
    NSString *_title;
    NSString *_mediaType;
    NSString *_coverUrl;
    NSString *_channelLogoUrl;
    NSString *_subtitle;
    NSArray *_tags;
    NSArray *_tvShowRequests;
}

@property(readonly, copy, nonatomic) NSArray *tvShowRequests; // @synthesize tvShowRequests=_tvShowRequests;
@property(readonly, copy, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *channelLogoUrl; // @synthesize channelLogoUrl=_channelLogoUrl;
@property(readonly, copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(readonly, copy, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)assetScaleId;
- (int)assetScaleType;
- (id)availableTo;
- (BOOL)soonNotAvailable;
- (id)cast;
- (id)directors;
- (id)decorations;
- (id)releaseYear;
- (id)genresString;
- (id)castString;
- (id)directorsString;
- (id)summary;
- (id)largeCoverUrl;
- (id)favoriteId;
- (id)lengthInMinutes;
- (id)epgId;
- (id)tvShowId;
- (BOOL)favoriteSupport;
- (int)favoriteType;
- (double)duration;
- (id)currentProgram;
- (int)area;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

