//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class TDXSidebarProgressView, TVShowEpisode, UIButton, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXSidebarEpisodeCell : UICollectionViewCell
{
    UILabel *_episodeNumberLabel;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_playButton;
    TDXSidebarProgressView *_progressView;
    UIView *_lineSeparatorTop;
    TVShowEpisode *_tvShowEpisode;
    CDUnknownBlockType _onClickHandler;
    UIView *_lineSeparatorBottom;
}

+ (id)identifier;
@property(retain, nonatomic) UIView *lineSeparatorBottom; // @synthesize lineSeparatorBottom=_lineSeparatorBottom;
@property(copy, nonatomic) CDUnknownBlockType onClickHandler; // @synthesize onClickHandler=_onClickHandler;
@property(retain, nonatomic) TVShowEpisode *tvShowEpisode; // @synthesize tvShowEpisode=_tvShowEpisode;
@property(retain, nonatomic) UIView *lineSeparatorTop; // @synthesize lineSeparatorTop=_lineSeparatorTop;
@property(retain, nonatomic) TDXSidebarProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *episodeNumberLabel; // @synthesize episodeNumberLabel=_episodeNumberLabel;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)configureForObject:(id)arg1 onClickHandler:(CDUnknownBlockType)arg2 isLastCell:(BOOL)arg3;
- (void)setSelected:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

