//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXSatelliteButton : UIButton
{
    UIImageView *_tdx_headerImage;
    UILabel *_tdx_titleLabel;
}

@property(retain, nonatomic) UILabel *tdx_titleLabel; // @synthesize tdx_titleLabel=_tdx_titleLabel;
@property(retain, nonatomic) UIImageView *tdx_headerImage; // @synthesize tdx_headerImage=_tdx_headerImage;
- (void).cxx_destruct;
- (void)updateConstraints;
- (struct UIEdgeInsets)alignmentRectInsets;
- (id)createHighlightLayer;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)init;

@end

