//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, TDXModalActivityView, TDXSearchViewModel, UIButton, UIImageView, UISearchBar, UISwipeGestureRecognizer, UITableView, UITapGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface TDXSearchPageViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UIScrollViewDelegate>
{
    UIImageView *_mainTopBar;
    UISearchBar *_searchBar;
    UIView *_searchViewContainer;
    UITableView *_tableView;
    UIButton *_closeBtn;
    TDXModalActivityView *_activityView;
    TDXSearchViewModel *_searchViewModel;
    NSString *_searchText;
    UITapGestureRecognizer *_hideKeyboardTapGestureRecognizer;
    UISwipeGestureRecognizer *_hideKeyboardSwipeGestureRecognizer;
    NSMutableArray *_constraintsToReset;
    CDUnknownBlockType _hideSearchCallback;
}

@property(copy, nonatomic) CDUnknownBlockType hideSearchCallback; // @synthesize hideSearchCallback=_hideSearchCallback;
@property(retain, nonatomic) NSMutableArray *constraintsToReset; // @synthesize constraintsToReset=_constraintsToReset;
@property(retain, nonatomic) UISwipeGestureRecognizer *hideKeyboardSwipeGestureRecognizer; // @synthesize hideKeyboardSwipeGestureRecognizer=_hideKeyboardSwipeGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *hideKeyboardTapGestureRecognizer; // @synthesize hideKeyboardTapGestureRecognizer=_hideKeyboardTapGestureRecognizer;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(retain, nonatomic) TDXSearchViewModel *searchViewModel; // @synthesize searchViewModel=_searchViewModel;
@property(retain, nonatomic) TDXModalActivityView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *searchViewContainer; // @synthesize searchViewContainer=_searchViewContainer;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UIImageView *mainTopBar; // @synthesize mainTopBar=_mainTopBar;
- (void).cxx_destruct;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)hideSearch;
- (void)hidePlayer;
- (void)tapCellAtIndexPath:(id)arg1;
- (void)hideKeyboard:(id)arg1;
- (void)handleNetworkChanges;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)updateViewConstraints;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithHideSearchCallback:(CDUnknownBlockType)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

