//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXSettingsTableViewCell : UITableViewCell
{
    UILabel *_mainLabel;
    UIImageView *_disclosureIndicatorStandard;
    UIImageView *_disclosureIndicatorText;
    UIView *_bottomLineSeparator;
    UIView *_topLineSeparator;
}

+ (id)identifier;
@property(retain, nonatomic) UIView *topLineSeparator; // @synthesize topLineSeparator=_topLineSeparator;
@property(retain, nonatomic) UIView *bottomLineSeparator; // @synthesize bottomLineSeparator=_bottomLineSeparator;
@property(retain, nonatomic) UIImageView *disclosureIndicatorText; // @synthesize disclosureIndicatorText=_disclosureIndicatorText;
@property(retain, nonatomic) UIImageView *disclosureIndicatorStandard; // @synthesize disclosureIndicatorStandard=_disclosureIndicatorStandard;
@property(retain, nonatomic) UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
- (void).cxx_destruct;
- (void)configureForObject:(id)arg1 isBottomCell:(BOOL)arg2;
- (void)updateConstraints;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

