//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface TDXSynopsisSummaryView : UIView
{
    UILabel *_summaryLabel;
    UILabel *_moreLabel;
}

@property(retain, nonatomic) UILabel *moreLabel; // @synthesize moreLabel=_moreLabel;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)layoutSubviews;
- (void)showMoreText;
- (void)configureWithStreamable:(id)arg1;
- (id)init;

@end

