//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "TDXCell.h"

@class NSString, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXSearchResultTableViewCell : UITableViewCell <TDXCell>
{
    UILabel *_titleLabel;
    UIImageView *_coverImg;
    UILabel *_subtitleLabel;
    UILabel *_tagsLabel;
    UIImageView *_channelImg;
}

+ (id)identifier;
@property(retain, nonatomic) UIImageView *channelImg; // @synthesize channelImg=_channelImg;
@property(retain, nonatomic) UILabel *tagsLabel; // @synthesize tagsLabel=_tagsLabel;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UIImageView *coverImg; // @synthesize coverImg=_coverImg;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)configureForObject:(id)arg1;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)updateConstraints;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

