//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TDXSidebarViewModel, UITableView;

__attribute__((visibility("hidden")))
@interface TDXSidebarSectionSelectionView : UIView
{
    UITableView *_tableView;
    TDXSidebarViewModel *_viewModel;
}

@property(retain, nonatomic) TDXSidebarViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (struct CGSize)contentSize;
- (void)setSelected;
- (id)initWithViewModel:(id)arg1 delegate:(id)arg2 datasource:(id)arg3;

@end

