//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDXOverlayViewController.h"

#import "TDXFrontPageSectionHeaderViewDelegate.h"

@class NSString, TDXFrontPageContentViewController;

__attribute__((visibility("hidden")))
@interface TDXShowAllOverlayViewController : TDXOverlayViewController <TDXFrontPageSectionHeaderViewDelegate>
{
    id <TDXFrontPageDelegate><TDXFrontPageSectionHeaderViewDelegate> _delegate;
    TDXFrontPageContentViewController *_frontPageContentViewController;
}

@property(retain, nonatomic) TDXFrontPageContentViewController *frontPageContentViewController; // @synthesize frontPageContentViewController=_frontPageContentViewController;
@property __weak id <TDXFrontPageDelegate><TDXFrontPageSectionHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)setActive;
- (void)overlayWillClose:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 andFrontPageDelegate:(id)arg2 andTitle:(id)arg3;
- (BOOL)hideSectionTitle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

