//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXSidebarChannelCell : UICollectionViewCell
{
    UIImageView *_channelImg;
    UILabel *_currentProgramLabel;
    UILabel *_nextProgramLabel;
    UIView *_lineSeparatorTop;
    UIView *_lineSeparatorBottom;
}

+ (id)identifier;
@property(retain, nonatomic) UIView *lineSeparatorBottom; // @synthesize lineSeparatorBottom=_lineSeparatorBottom;
@property(retain, nonatomic) UIView *lineSeparatorTop; // @synthesize lineSeparatorTop=_lineSeparatorTop;
@property(retain, nonatomic) UILabel *nextProgramLabel; // @synthesize nextProgramLabel=_nextProgramLabel;
@property(retain, nonatomic) UILabel *currentProgramLabel; // @synthesize currentProgramLabel=_currentProgramLabel;
@property(retain, nonatomic) UIImageView *channelImg; // @synthesize channelImg=_channelImg;
- (void).cxx_destruct;
- (void)configureForObject:(id)arg1 isLastCell:(BOOL)arg2;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

