//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface TDXSearchResults : NSObject
{
    int _total;
    NSString *_searchSection;
    NSArray *_upcomingItems;
    NSArray *_rentItems;
    NSArray *_watchNowItems;
    NSArray *_items;
}

@property(readonly, copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, copy, nonatomic) NSArray *watchNowItems; // @synthesize watchNowItems=_watchNowItems;
@property(readonly, copy, nonatomic) NSArray *rentItems; // @synthesize rentItems=_rentItems;
@property(readonly, copy, nonatomic) NSArray *upcomingItems; // @synthesize upcomingItems=_upcomingItems;
@property(readonly, copy, nonatomic) NSString *searchSection; // @synthesize searchSection=_searchSection;
@property(readonly, nonatomic) int total; // @synthesize total=_total;
- (void).cxx_destruct;

@end

