//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface TDXSidebarProgressView : UIView
{
    UIView *_barBackground;
    UIView *_progressBar;
    UILabel *_rightLabel;
    float _progressFactor;
}

@property(nonatomic) float progressFactor; // @synthesize progressFactor=_progressFactor;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UIView *progressBar; // @synthesize progressBar=_progressBar;
@property(retain, nonatomic) UIView *barBackground; // @synthesize barBackground=_barBackground;
- (void).cxx_destruct;
- (void)setProgress:(id)arg1 andTotalLengthInMinutes:(id)arg2;
- (void)updateConstraints;
- (id)init;

@end

