//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TDXGridLayoutDataSource.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, TDXModalActivityView, TDXPlayerContainerViewController, TDXPlayerViewModel, TDXSidebarSectionSelectionView, TDXSidebarViewModel, UIButton, UICollectionView, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXSidebarComponentViewController : UIViewController <TDXGridLayoutDataSource, UICollectionViewDelegate, UICollectionViewDataSource, UITableViewDataSource, UITableViewDelegate>
{
    TDXSidebarViewModel *_sideBarViewModel;
    TDXPlayerViewModel *_playerViewModel;
    TDXPlayerContainerViewController *_parentPlayerViewController;
    UICollectionView *_sidebarCollectionView;
    UIView *_sidebarHeaderLandscape;
    UILabel *_sidebarHeaderLandscapeLabel;
    UIButton *_sidebarHeaderLandscapeSectionSelectionButton;
    UIImageView *_sidebarHeaderLandscapeSectionSelectionViewArrow;
    UIView *_sidebarHeaderPortrait;
    UILabel *_sidebarHeaderPortraitLabel;
    UIButton *_sidebarHeaderPortraitSectionSelectionButton;
    UIImageView *_sidebarHeaderPortraitSectionSelectionViewArrow;
    TDXModalActivityView *_activityView;
    TDXSidebarSectionSelectionView *_sideBarSectionSelectionView;
    NSArray *_constraints;
    CDUnknownBlockType _selectStreamableItemAction;
    CDUnknownBlockType _playAction;
}

@property(copy, nonatomic) CDUnknownBlockType playAction; // @synthesize playAction=_playAction;
@property(copy, nonatomic) CDUnknownBlockType selectStreamableItemAction; // @synthesize selectStreamableItemAction=_selectStreamableItemAction;
@property(retain, nonatomic) NSArray *constraints; // @synthesize constraints=_constraints;
@property(retain, nonatomic) TDXSidebarSectionSelectionView *sideBarSectionSelectionView; // @synthesize sideBarSectionSelectionView=_sideBarSectionSelectionView;
@property(retain, nonatomic) TDXModalActivityView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIImageView *sidebarHeaderPortraitSectionSelectionViewArrow; // @synthesize sidebarHeaderPortraitSectionSelectionViewArrow=_sidebarHeaderPortraitSectionSelectionViewArrow;
@property(retain, nonatomic) UIButton *sidebarHeaderPortraitSectionSelectionButton; // @synthesize sidebarHeaderPortraitSectionSelectionButton=_sidebarHeaderPortraitSectionSelectionButton;
@property(retain, nonatomic) UILabel *sidebarHeaderPortraitLabel; // @synthesize sidebarHeaderPortraitLabel=_sidebarHeaderPortraitLabel;
@property(retain, nonatomic) UIView *sidebarHeaderPortrait; // @synthesize sidebarHeaderPortrait=_sidebarHeaderPortrait;
@property(retain, nonatomic) UIImageView *sidebarHeaderLandscapeSectionSelectionViewArrow; // @synthesize sidebarHeaderLandscapeSectionSelectionViewArrow=_sidebarHeaderLandscapeSectionSelectionViewArrow;
@property(retain, nonatomic) UIButton *sidebarHeaderLandscapeSectionSelectionButton; // @synthesize sidebarHeaderLandscapeSectionSelectionButton=_sidebarHeaderLandscapeSectionSelectionButton;
@property(retain, nonatomic) UILabel *sidebarHeaderLandscapeLabel; // @synthesize sidebarHeaderLandscapeLabel=_sidebarHeaderLandscapeLabel;
@property(retain, nonatomic) UIView *sidebarHeaderLandscape; // @synthesize sidebarHeaderLandscape=_sidebarHeaderLandscape;
@property(retain, nonatomic) UICollectionView *sidebarCollectionView; // @synthesize sidebarCollectionView=_sidebarCollectionView;
@property(nonatomic) __weak TDXPlayerContainerViewController *parentPlayerViewController; // @synthesize parentPlayerViewController=_parentPlayerViewController;
@property(nonatomic) __weak TDXPlayerViewModel *playerViewModel; // @synthesize playerViewModel=_playerViewModel;
@property(retain, nonatomic) TDXSidebarViewModel *sideBarViewModel; // @synthesize sideBarViewModel=_sideBarViewModel;
- (void).cxx_destruct;
- (void)dealloc;
- (struct CGSize)sideBarContentSize;
- (void)toggleSeasonSelector;
- (id)createSignalFor:(id)arg1;
- (void)loadSidebar;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)updateViewConstraints;
- (void)updatePortraitHeader;
- (void)viewDidLoad;
- (void)updateLandscapeHeader;
- (void)updateViews;
- (void)scrollToSelectedItem;
- (id)createHeaderSectionSelectionButton;
- (id)createHeaderSectionSelectionArrowImageView;
- (id)initWithViewModel:(id)arg1 parentViewController:(id)arg2 andSelectStreamableAction:(CDUnknownBlockType)arg3 andPlayAction:(CDUnknownBlockType)arg4;
- (float)sectionSpaceWhenNoSectionInfo;
- (BOOL)hasSectionInfo:(unsigned int)arg1;
- (id)streamableItemForElementWithIndexPath:(id)arg1;
- (unsigned int)numberOfItemsInSection:(int)arg1;
- (id)titleOfSectionWithIndex:(unsigned int)arg1;
- (unsigned int)numberOfSections;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

