//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface TDXSecondaryScreenViewController : UIViewController
{
    UIImageView *_logoView;
}

@property(retain, nonatomic) UIImageView *logoView; // @synthesize logoView=_logoView;
- (void).cxx_destruct;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (void)updateViewConstraints;
- (void)viewDidLoad;

@end

