//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface TDXSidebarViewModel : NSObject
{
    BOOL _initialLoad;
    id <Streamable> _streamingItem;
    NSMutableArray *_streamablesForSelectedSection;
    int _activityState;
    NSArray *_allStreamables;
    NSArray *_sections;
    NSString *_selectedSection;
}

@property(retain, nonatomic) NSString *selectedSection; // @synthesize selectedSection=_selectedSection;
@property(retain, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) NSArray *allStreamables; // @synthesize allStreamables=_allStreamables;
@property(nonatomic) BOOL initialLoad; // @synthesize initialLoad=_initialLoad;
@property(nonatomic) int activityState; // @synthesize activityState=_activityState;
@property(retain, nonatomic) NSMutableArray *streamablesForSelectedSection; // @synthesize streamablesForSelectedSection=_streamablesForSelectedSection;
@property(retain, nonatomic) id <Streamable> streamingItem; // @synthesize streamingItem=_streamingItem;
- (void).cxx_destruct;
- (id)sectionTitles;
@property(readonly, nonatomic) BOOL smoothReload;
- (id)nextEpisode;
- (id)indexPathForStreamable:(id)arg1;
- (BOOL)isStreamableLastItemInSection:(id)arg1;
- (int)selectedSectionIndex;
- (id)sectionTitleForIndex:(unsigned int)arg1;
- (int)numberOfSections;
- (BOOL)contentHasSections:(id)arg1;
@property(readonly, nonatomic) BOOL contentHasSections;
@property(readonly, nonatomic) NSString *sectionTitle;
- (void)changeSection:(id)arg1;
- (id)createSections:(id)arg1;
- (void)updateModelWithItem:(id)arg1 andStreamables:(id)arg2;
- (void)fetchChannels;
- (void)loadSidebar;
- (id)tvShowSignalFor:(id)arg1;
- (id)tvShowEpisodeSignalFor:(id)arg1;
- (id)relatedArchiveProgramsSignalFor:(id)arg1;
- (id)relatedMoviesSignalFor:(id)arg1;
- (id)liveTVAllowedChannelsSignalFor;
- (int)areaForStreamable;
- (int)areaForStreamable:(id)arg1;
- (id)createSignalFor:(id)arg1;
- (id)init;

@end

