//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class TDXModalActivityView, TDXPlayerViewModel, TDXSynopsisView;

__attribute__((visibility("hidden")))
@interface TDXSynopsisComponentViewController : UIViewController
{
    TDXSynopsisView *_synopsisView;
    TDXPlayerViewModel *_viewModel;
    TDXModalActivityView *_activityView;
    id <Streamable> _streamable;
}

@property(retain, nonatomic) id <Streamable> streamable; // @synthesize streamable=_streamable;
@property(retain, nonatomic) TDXModalActivityView *activityView; // @synthesize activityView=_activityView;
@property(nonatomic) __weak TDXPlayerViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) TDXSynopsisView *synopsisView; // @synthesize synopsisView=_synopsisView;
- (void).cxx_destruct;
- (void)favoriteProgram:(id)arg1 type:(int)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)deleteFavorite:(id)arg1 type:(int)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)updateViewConstraints;
- (void)handleNetworkChanges;
- (void)loadView;
- (id)initWithViewModel:(id)arg1;

@end

