//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TDXMenuDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSMutableArray, NSString, TDXConfiguration, TDXMenuItem, TDXMenuViewController, TDXServiceMessageViewController, UIImageView, UITapGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface TDXStackViewController : UIViewController <UIGestureRecognizerDelegate, TDXMenuDelegate>
{
    _Bool _showSecondaryMenu;
    TDXMenuItem *_selectedPrimaryMenuItem;
    TDXServiceMessageViewController *_serviceMessageViewController;
    TDXConfiguration *_configuration;
    TDXMenuViewController *_menuViewController;
    NSMutableArray *_viewControllerStack;
    NSArray *_menuItems;
    UITapGestureRecognizer *_tapToCloseSecondaryMenuTapGestureRecognizer;
    NSMutableArray *_modalViews;
    UIView *_dimmedSearchBackground;
    UIImageView *_backgroundImageView;
}

@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIView *dimmedSearchBackground; // @synthesize dimmedSearchBackground=_dimmedSearchBackground;
@property(retain, nonatomic) NSMutableArray *modalViews; // @synthesize modalViews=_modalViews;
@property(retain, nonatomic) UITapGestureRecognizer *tapToCloseSecondaryMenuTapGestureRecognizer; // @synthesize tapToCloseSecondaryMenuTapGestureRecognizer=_tapToCloseSecondaryMenuTapGestureRecognizer;
@property(retain, nonatomic) NSArray *menuItems; // @synthesize menuItems=_menuItems;
@property(retain, nonatomic) NSMutableArray *viewControllerStack; // @synthesize viewControllerStack=_viewControllerStack;
@property(retain, nonatomic) TDXMenuViewController *menuViewController; // @synthesize menuViewController=_menuViewController;
@property(retain, nonatomic) TDXConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) TDXServiceMessageViewController *serviceMessageViewController; // @synthesize serviceMessageViewController=_serviceMessageViewController;
@property(retain, nonatomic) TDXMenuItem *selectedPrimaryMenuItem; // @synthesize selectedPrimaryMenuItem=_selectedPrimaryMenuItem;
@property(nonatomic) _Bool showSecondaryMenu; // @synthesize showSecondaryMenu=_showSecondaryMenu;
- (void).cxx_destruct;
- (void)hideSearch;
- (id)peek;
- (void)serviceMessageReceived:(id)arg1;
- (void)didSelectStreamableItemNotification:(id)arg1;
- (void)primaryMenuItemWasPressed:(id)arg1;
- (void)drawLeftEdgeShadowOnViewController:(id)arg1;
- (void)setContentViewControllerHorizontalOffset:(float)arg1;
- (void)handleEnterForeground;
- (void)handleNetworkChanges;
- (void)updateConstraintsToOnScreenPosition:(id)arg1;
- (void)updateConstraintsToOffScreenPosition:(id)arg1;
- (void)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)pushModalViewController:(id)arg1 usingNativeMethod:(BOOL)arg2;
- (void)removeStackedViewController:(id)arg1;
- (void)setRootViewController:(id)arg1 animateOverlayClosure:(BOOL)arg2;
- (id)defaultMenuItem;
- (id)lastSelectedMenuItemOrDefault;
- (void)closeSecondaryMenuTapped:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)removeFromParentViewController;
- (void)updateViewConstraints;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

