//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, TDXCredentials;

__attribute__((visibility("hidden")))
@interface TDXSession : NSObject
{
    TDXCredentials *_credentials;
    NSString *_sessionId;
    NSDate *_expiryDate;
    NSString *_networkName;
}

+ (id)unwrap:(id)arg1;
+ (void)clearStoredSession;
+ (id)retrieveSession;
+ (void)storeSession:(id)arg1;
@property(retain, nonatomic) NSString *networkName; // @synthesize networkName=_networkName;
@property(retain, nonatomic) NSDate *expiryDate; // @synthesize expiryDate=_expiryDate;
@property(readonly, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(readonly, nonatomic) TDXCredentials *credentials; // @synthesize credentials=_credentials;
- (void).cxx_destruct;
- (id)wrap;
- (id)initWithCredentials:(id)arg1 sessionId:(id)arg2;
- (void)refreshWithSucces:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)logout;
- (BOOL)isExpired;
- (BOOL)isGuestSession;
- (BOOL)isUserSession;
- (void)clear;
- (void)disable;
- (void)loginWithCredentials:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (_Bool)isNetworkNameDifferentFromCurrent;
- (void)setNameToCurrentNetwork;
- (id)nameOfCurrentNetwork;
- (id)initWithCredentials:(id)arg1;
- (id)init;
- (void)setSessionId:(id)arg1;

@end

