//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDXMainContentViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UILabel, UITableView;

__attribute__((visibility("hidden")))
@interface TDXSettingsPageViewController : TDXMainContentViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_settingsTableView;
    NSArray *_tableViewData;
    UILabel *_settingsTitle;
}

@property(retain, nonatomic) UILabel *settingsTitle; // @synthesize settingsTitle=_settingsTitle;
@property(retain, nonatomic) NSArray *tableViewData; // @synthesize tableViewData=_tableViewData;
@property(retain, nonatomic) UITableView *settingsTableView; // @synthesize settingsTableView=_settingsTableView;
- (void).cxx_destruct;
- (id)aboutURL;
- (id)faqURL;
- (void)viewDidAppear:(BOOL)arg1;
- (void)updateViewConstraints;
- (void)viewDidLoad;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

