//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "TDXCell.h"

@class NSString, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface TDXSidebarSeasonSelectionCell : UITableViewCell <TDXCell>
{
    UILabel *_sectionLabel;
}

+ (id)identifier;
@property(retain, nonatomic) UILabel *sectionLabel; // @synthesize sectionLabel=_sectionLabel;
- (void).cxx_destruct;
- (void)deselect;
- (void)select;
- (void)configureForObject:(id)arg1;
- (void)updateConstraints;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(retain, nonatomic) UIView *backgroundView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

