//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXStreamUrlManager : NSObject
{
}

- (id)deviceIdBase64;
- (id)deviceId;
- (id)testUrlForItem:(id)arg1;
- (id)parametersForStreamable:(id)arg1;
- (id)urlAsStringForStreamable:(id)arg1 wantStreamingURL:(BOOL)arg2;
- (void)streamUrlForItem:(id)arg1 asStartOver:(BOOL)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)testStreamUrl:(id)arg1 succes:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;

@end

