//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface TDXSynopsisBottomView : UIView
{
    UILabel *_directorsLabel;
    UILabel *_castLabel;
    UILabel *_availableToLabel;
    struct UIEdgeInsets _labelMargins;
}

@property(nonatomic) struct UIEdgeInsets labelMargins; // @synthesize labelMargins=_labelMargins;
@property(retain, nonatomic) UILabel *availableToLabel; // @synthesize availableToLabel=_availableToLabel;
@property(retain, nonatomic) UILabel *castLabel; // @synthesize castLabel=_castLabel;
@property(retain, nonatomic) UILabel *directorsLabel; // @synthesize directorsLabel=_directorsLabel;
- (void).cxx_destruct;
- (void)configureWithStreamable:(id)arg1;
- (void)updateConstraints;
- (void)setup;
- (id)init;

@end

