//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDXFrontPageViewModel.h"

@class TDXMenuItemRequest;

__attribute__((visibility("hidden")))
@interface TDXShowAllOverlayViewModel : TDXFrontPageViewModel
{
    TDXMenuItemRequest *_baseRequest;
    TDXMenuItemRequest *_expandRequest;
}

@property(retain, nonatomic) TDXMenuItemRequest *expandRequest; // @synthesize expandRequest=_expandRequest;
@property(retain, nonatomic) TDXMenuItemRequest *baseRequest; // @synthesize baseRequest=_baseRequest;
- (void).cxx_destruct;
- (void)setSelectedFilterRequest:(id)arg1;
- (void)fetchStreamables;
- (id)initWithBaseRequest:(id)arg1 andExpandRequest:(id)arg2 reloadEnabled:(BOOL)arg3;

@end

