//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface TDXTextAndLineButton : UIButton
{
    UILabel *_textLabel;
    float _textWidth;
    UILabel *_underLineTextLabel;
    float _underLineTextWidth;
    UIImageView *_underLineImage;
}

@property(retain, nonatomic) UIImageView *underLineImage; // @synthesize underLineImage=_underLineImage;
@property(nonatomic) float underLineTextWidth; // @synthesize underLineTextWidth=_underLineTextWidth;
@property(retain, nonatomic) UILabel *underLineTextLabel; // @synthesize underLineTextLabel=_underLineTextLabel;
@property(nonatomic) float textWidth; // @synthesize textWidth=_textWidth;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)setLabelSizeToTextSize:(id)arg1;
- (id)initWithText:(id)arg1 underLineText:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

