//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Channel.h"

@class NSArray, NSMutableSet, TDXUserTVGuideChannel;

__attribute__((visibility("hidden")))
@interface TDXTVGuideChannel : Channel
{
    TDXUserTVGuideChannel *_channel;
    NSMutableSet *_programIds;
    NSArray *_fillerPrograms;
}

@property(retain, nonatomic) NSArray *fillerPrograms; // @synthesize fillerPrograms=_fillerPrograms;
@property(retain, nonatomic) NSMutableSet *programIds; // @synthesize programIds=_programIds;
@property(retain, nonatomic) TDXUserTVGuideChannel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (void)addFillerPrograms:(id)arg1;
- (void)addPrograms:(id)arg1;
- (id)id;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) NSArray *programs;

@end

