//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface TDXTopMenuButton : UIView
{
    UILabel *_textLabel;
    CDUnknownBlockType _onTapAction;
}

@property(copy, nonatomic) CDUnknownBlockType onTapAction; // @synthesize onTapAction=_onTapAction;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)didTapButton;
- (void)updateConstraints;
- (id)initWithTapAction:(CDUnknownBlockType)arg1;

@end

