//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface TDXTimer : NSObject
{
    NSTimer *_timer;
    id _target;
    SEL _theSelector;
}

+ (id)scheduledAutoInvalidatingTimerWithTimeInterval:(double)arg1 target:(id)arg2 selector:(SEL)arg3 repeats:(BOOL)arg4;
@property(nonatomic) SEL theSelector; // @synthesize theSelector=_theSelector;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (void)timerDidFire:(id)arg1;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 seconds:(double)arg3 repeats:(BOOL)arg4;

@end

