//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

__attribute__((visibility("hidden")))
@interface TDXTouchForwarderView : UIView
{
    CDUnknownBlockType _showHideControlsHandler;
    CDUnknownBlockType _fullscreenOpenCloseHandler;
    CDUnknownBlockType _fullscreenToggleHandler;
}

@property(copy, nonatomic) CDUnknownBlockType fullscreenToggleHandler; // @synthesize fullscreenToggleHandler=_fullscreenToggleHandler;
@property(copy, nonatomic) CDUnknownBlockType fullscreenOpenCloseHandler; // @synthesize fullscreenOpenCloseHandler=_fullscreenOpenCloseHandler;
@property(copy, nonatomic) CDUnknownBlockType showHideControlsHandler; // @synthesize showHideControlsHandler=_showHideControlsHandler;
- (void).cxx_destruct;
- (void)updateConstraints;
- (void)doubleTapped;
- (void)singleTapped;
- (void)pinched:(id)arg1;
- (id)init;

@end

