//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"

@class NSArray, NSString, TDXGuideViewModel, UICollectionView;

__attribute__((visibility("hidden")))
@interface TDXTimeBarView : UIView <UICollectionViewDataSource>
{
    TDXGuideViewModel *_viewModel;
    UICollectionView *_timeBarCollectionView;
    int _currentHour;
    NSArray *_hours;
}

@property(retain, nonatomic) NSArray *hours; // @synthesize hours=_hours;
@property(nonatomic) int currentHour; // @synthesize currentHour=_currentHour;
@property(retain, nonatomic) UICollectionView *timeBarCollectionView; // @synthesize timeBarCollectionView=_timeBarCollectionView;
@property(retain, nonatomic) TDXGuideViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)updateConstraints;
- (void)setup;
- (void)createDataModel;
- (id)initWithViewModel:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

