//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TDXUserTVGuideChannel : NSObject
{
    NSNumber *_channelId;
    NSString *_name;
    NSString *_logoSmallUrl;
    NSString *_logoLargeUrl;
}

@property(readonly, nonatomic) NSString *logoLargeUrl; // @synthesize logoLargeUrl=_logoLargeUrl;
@property(readonly, nonatomic) NSString *logoSmallUrl; // @synthesize logoSmallUrl=_logoSmallUrl;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSNumber *channelId; // @synthesize channelId=_channelId;
- (void).cxx_destruct;

@end

