//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TDXUserAllowedChannel : NSObject
{
    BOOL _isStreamable;
    NSString *_channelId;
}

@property(readonly, nonatomic) BOOL isStreamable; // @synthesize isStreamable=_isStreamable;
@property(readonly, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
- (void).cxx_destruct;

@end

