//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TDXUtil : NSObject
{
}

+ (id)splitArray:(id)arg1 componentsPerSegment:(unsigned int)arg2;
+ (id)expiresStringForAvailableToDate:(id)arg1;
+ (int)streamingType:(int)arg1;
+ (id)captureScreenshotOfView:(id)arg1;
+ (id)stringByConcatenatingStrings:(id)arg1 withSeperator:(id)arg2;
+ (BOOL)hasDifferentStreamingContent:(id)arg1 otherStreamable:(id)arg2;

@end

