//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TDXVerticalTableViewCell : UITableViewCell
{
    NSArray *_programViews;
}

@property(retain, nonatomic) NSArray *programViews; // @synthesize programViews=_programViews;
- (void).cxx_destruct;
- (void)configureWithPrograms:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

