//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIWebViewDelegate.h"

@class NSMutableArray, NSString, TDXModalActivityView, UILabel, UIWebView;

__attribute__((visibility("hidden")))
@interface TDXWebView : UIView <UIWebViewDelegate>
{
    UIWebView *_webView;
    UILabel *_errorLabel;
    NSMutableArray *_javaScriptEvaluations;
    TDXModalActivityView *_modalActivityView;
}

@property(retain, nonatomic) TDXModalActivityView *modalActivityView; // @synthesize modalActivityView=_modalActivityView;
@property(retain, nonatomic) NSMutableArray *javaScriptEvaluations; // @synthesize javaScriptEvaluations=_javaScriptEvaluations;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)javaScriptDidFinishEvaluating;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)setWebviewWidthWithJS:(id)arg1;
- (void)addJavaScriptForEvaluation:(id)arg1;
- (void)loadRequest:(id)arg1;
- (void)layoutSubviews;
- (void)updateConstraints;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

