//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TeaserData : NSObject
{
    NSString *_header;
    NSString *_subheader;
    NSString *_teaserCoverUrl;
}

@property(readonly, copy, nonatomic) NSString *teaserCoverUrl; // @synthesize teaserCoverUrl=_teaserCoverUrl;
@property(readonly, copy, nonatomic) NSString *subheader; // @synthesize subheader=_subheader;
@property(readonly, copy, nonatomic) NSString *header; // @synthesize header=_header;
- (void).cxx_destruct;

@end

