//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface TestConstructors : NSObject
{
}

+ (id)fakeChannel;
+ (id)fakeProgram;
+ (id)programWithBegin:(id)arg1 end:(id)arg2 title:(id)arg3;
+ (id)program;
+ (id)channel;
+ (id)programWithId:(int)arg1;
+ (id)channelWithId:(int)arg1;

@end

