//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Streamable.h"

@class NSArray, NSDate, NSNumber, NSString, TeaserData;

__attribute__((visibility("hidden")))
@interface TVShowEpisode : NSObject <Streamable>
{
    NSString *_id;
    NSNumber *_episodeNo;
    NSNumber *_seasonNo;
    NSString *_title;
    NSString *_tvShowId;
    NSString *_episodeName;
    NSString *_seasonName;
    NSString *_tvShowName;
    NSString *_summary;
    NSString *_coverUrl;
    NSArray *_cast;
    NSArray *_directors;
    NSNumber *_lengthInMinutes;
    NSNumber *_year;
    NSDate *_availableFrom;
    NSDate *_availableTo;
    NSArray *_decorations;
    TeaserData *_teaserData;
    NSString *_urlId;
}

@property(copy, nonatomic) NSString *urlId; // @synthesize urlId=_urlId;
@property(readonly, copy, nonatomic) TeaserData *teaserData; // @synthesize teaserData=_teaserData;
@property(readonly, copy, nonatomic) NSArray *decorations; // @synthesize decorations=_decorations;
@property(readonly, nonatomic) NSDate *availableTo; // @synthesize availableTo=_availableTo;
@property(readonly, nonatomic) NSDate *availableFrom; // @synthesize availableFrom=_availableFrom;
@property(readonly, nonatomic) NSNumber *year; // @synthesize year=_year;
@property(readonly, nonatomic) NSNumber *lengthInMinutes; // @synthesize lengthInMinutes=_lengthInMinutes;
@property(readonly, copy, nonatomic) NSArray *directors; // @synthesize directors=_directors;
@property(readonly, copy, nonatomic) NSArray *cast; // @synthesize cast=_cast;
@property(readonly, copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(readonly, copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(readonly, copy, nonatomic) NSString *tvShowName; // @synthesize tvShowName=_tvShowName;
@property(readonly, copy, nonatomic) NSString *seasonName; // @synthesize seasonName=_seasonName;
@property(readonly, copy, nonatomic) NSString *episodeName; // @synthesize episodeName=_episodeName;
@property(readonly, copy, nonatomic) NSString *tvShowId; // @synthesize tvShowId=_tvShowId;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSNumber *seasonNo; // @synthesize seasonNo=_seasonNo;
@property(retain, nonatomic) NSNumber *episodeNo; // @synthesize episodeNo=_episodeNo;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)assetScaleId;
- (int)assetScaleType;
- (BOOL)isEqual:(id)arg1;
- (id)epgId;
- (id)releaseYear;
- (id)genresString;
- (id)castString;
- (id)directorsString;
- (id)largeCoverUrl;
- (BOOL)favoriteSupport;
- (id)favoriteId;
- (int)favoriteType;
- (id)durationHumanReadable;
- (double)duration;
- (id)currentProgram;
- (int)area;
- (BOOL)soonNotAvailable;
- (int)availableForDays;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

