//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "Streamable.h"

@class NSArray, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface TVShow : NSObject <Streamable>
{
    NSString *_tvShowId;
    NSString *_name;
    NSString *_coverUrl;
    NSString *_summary;
    NSArray *_packages;
    NSArray *_decorations;
    NSArray *_directors;
    NSArray *_cast;
    NSNumber *_year;
}

@property(readonly, copy, nonatomic) NSNumber *year; // @synthesize year=_year;
@property(readonly, copy, nonatomic) NSArray *cast; // @synthesize cast=_cast;
@property(readonly, copy, nonatomic) NSArray *directors; // @synthesize directors=_directors;
@property(readonly, copy, nonatomic) NSArray *decorations; // @synthesize decorations=_decorations;
@property(readonly, copy, nonatomic) NSArray *packages; // @synthesize packages=_packages;
@property(readonly, copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(readonly, copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *tvShowId; // @synthesize tvShowId=_tvShowId;
- (void).cxx_destruct;
- (id)assetScaleId;
- (int)assetScaleType;
- (id)seasonsString;
- (id)availableTo;
- (BOOL)soonNotAvailable;
- (id)lengthInMinutes;
- (id)favoriteId;
- (id)epgId;
- (id)id;
- (id)releaseYear;
- (id)genresString;
- (id)castString;
- (id)directorsString;
- (double)duration;
- (id)largeCoverUrl;
- (BOOL)favoriteSupport;
- (int)favoriteType;
- (id)currentProgram;
- (id)title;
- (int)area;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

