//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface UIApplication (Util)
+ (void)logErrorInCrittercismWithMessage:(id)arg1;
+ (void)logErrorInCrittercismWithOperation:(id)arg1;
+ (id)prepareStringForCucumberAutomation:(id)arg1;
+ (void)leaveCrittercismBreadCrumb:(id)arg1;
+ (BOOL)readyToMirrorFullScreenOnSecondaryScreen;
+ (BOOL)showAirPlayInFullScreen;
+ (BOOL)isTargetSimulator;
+ (BOOL)isAppStoreBuild;
+ (BOOL)isHockeyBetaBuild;
+ (BOOL)isHockeyOrAppStoreBuild;
+ (BOOL)isDebug;
+ (BOOL)isBuildYouSee;
+ (BOOL)isPhone6Plus;
+ (BOOL)isPhone6;
+ (BOOL)isPhone4Inch;
+ (BOOL)isPhone;
+ (BOOL)isPortrait;
@end

