//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@interface UICollectionViewLayout (LayoutHelper)
- (int)rowInSectionForItemNumber:(int)arg1 andColumns:(int)arg2;
- (float)heightForRows:(int)arg1 withAttributes:(id)arg2;
- (float)contentWidthForLayoutAttributes:(id)arg1;
- (float)heightForRowsInSectionWithItems:(int)arg1 withAttributes:(id)arg2;
- (float)yPosForRowsInSectionWithItems:(int)arg1 withAttributes:(id)arg2;
- (float)xPosForItemNumber:(int)arg1 andAttributes:(id)arg2;
@end

