//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (CASAdditions)
+ (id)cas_colorWithHex:(id)arg1;
- (id)cas_hexValueWithAlpha:(BOOL)arg1;
- (id)cas_hexValue;
@end

