//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (ThemeColors)
+ (id)serviceMessageBackgroundColor;
+ (id)listGuideBackgroundOddColor;
+ (id)listGuideBackgroundEvenColor;
+ (id)guideChannelsTopBarColor;
+ (id)guideProgramTextColorPast;
+ (id)guideProgramTextColor;
+ (id)guidePresentProgramBackgroundColor;
+ (id)guideBackgroundColor;
+ (id)tdx_playerControlsBackgroundColor;
+ (id)tertiaryFontColor;
+ (id)secondaryFontColor;
+ (id)primaryFontColor;
+ (id)contentBackgroundColor;
+ (id)mainTopBarDarkColor;
+ (id)mainTopBarColor;
+ (id)secondaryMenuBackgroundColor;
+ (id)mainContentBackgroundColor;
+ (id)mainBackgroundColor;
+ (id)favoritePopUpBackgroundColor;
+ (id)progressBarBackgroundColor;
+ (id)progressBarProgressColor;
+ (id)frontPageCellTextBackgroundColor;
+ (id)sidebarHeaderBackgroundColor;
+ (id)sidebarSeasonSelectionSelectedTextColor;
+ (id)sidebarSeasonSelectionSeparatorColor;
+ (id)sidebarSeasonSelectionTextColor;
+ (id)sidebarLineSeparatorColor;
+ (id)sidebarSeasonSelectionSelectedBackground;
+ (id)sidebarSeasonSelectionBackground;
+ (id)sidebarBackground;
+ (id)sidebarSelectedBackground;
+ (id)guideTimeBarFontColor;
+ (id)guideTimeBarSeparator;
+ (id)guideChannelsTopBarBackgroundColor;
+ (id)guideCellPastFutureFontColor;
+ (id)guideCellPastFutureBackgroundColor;
+ (id)guideCellPresentBackgroundColor;
+ (id)guideChannelCellBorderColor;
+ (id)guideDatePickerSelectedDayNumLabelColor;
+ (id)guideDatePickerSelectedWeekdayLabelColor;
+ (id)guideDatePickerDeselectedColor;
+ (id)guideDatePickerBackgroundColor;
+ (id)frontPageTeaserToneDownColor;
+ (id)frontPageChannelLogoBackgroundColor;
+ (id)topMenuButtonDeselectedFontColor;
+ (id)topMenuButtonSelectedFontColor;
+ (id)primaryMenuSeparatorColor;
+ (id)primaryMenuSelectedFontColor;
+ (id)selectedBackgroundColor;
+ (id)satelliteButtonTextColor;
+ (id)primaryMenuDeselectedFontColor;
@end

