//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (ThemeFonts)
+ (id)tdx_cmsContentFont;
+ (id)tdx_cmsHeadlineFont;
+ (id)tdx_mediumFontWithSize:(float)arg1;
+ (id)tdx_fontWithSize:(float)arg1;
@end

