//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Mockup)
+ (id)circleWithDiameter:(float)arg1 color:(id)arg2;
+ (id)rectWithDimensions:(struct CGSize)arg1 color:(id)arg2;
+ (id)createImageWithRect:(struct CGSize)arg1 do:(CDUnknownBlockType)arg2;
@end

