//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

__attribute__((visibility("hidden")))
@interface UIImageViewAligned : UIImageView
{
    BOOL _enableScaleUp;
    BOOL _enableScaleDown;
    int _alignment;
    UIImageView *_realImageView;
}

@property(readonly, nonatomic) UIImageView *realImageView; // @synthesize realImageView=_realImageView;
@property(nonatomic) BOOL enableScaleDown; // @synthesize enableScaleDown=_enableScaleDown;
@property(nonatomic) BOOL enableScaleUp; // @synthesize enableScaleUp=_enableScaleUp;
@property(nonatomic) int alignment; // @synthesize alignment=_alignment;
- (void).cxx_destruct;
@property(nonatomic) BOOL alignBottom;
@property(nonatomic) BOOL alignTop;
@property(nonatomic) BOOL alignRight;
@property(nonatomic) BOOL alignLeft;
- (struct CGSize)realContentSize;
- (void)layoutSubviews;
- (void)setContentMode:(int)arg1;
- (void)setImage:(id)arg1;
- (id)image;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithImage:(id)arg1 highlightedImage:(id)arg2;
- (id)initWithImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

