//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (TDXImageCache)
- (void)tdx_setImageForURL:(id)arg1 placeHolderImage:(id)arg2 options:(unsigned int)arg3 completed:(CDUnknownBlockType)arg4;
- (void)tdx_setImageForURL:(id)arg1 andCompletion:(CDUnknownBlockType)arg2;
- (void)tdx_setImageForURL:(id)arg1 andPlaceholder:(id)arg2;
- (void)tdx_setImageForURL:(id)arg1;
- (void)tdx_setScaledImageForStreamable:(id)arg1;
@end

