//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UILabel (ThemeLabels)
+ (id)tdx_promoViewSubtitleLabel;
+ (id)tdx_promoViewTitleLabel;
+ (id)tdx_labelWithSize:(float)arg1;
+ (id)tdx_mediumLabel;
+ (id)tdx_smallLabel;
@end

