//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScreen.h"

@interface UIScreen (Util)
+ (struct CGSize)sizeInOrientation:(int)arg1;
+ (struct CGSize)currentScreenSize;
+ (struct CGSize)currentAppFrameSize;
+ (float)sizeRelativeTo4InchPhone:(float)arg1;
@end

