//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface UITextField (CASAdditions)
+ (void)load;
- (struct CGRect)cas_editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)cas_textRectForBounds:(struct CGRect)arg1;
@property(nonatomic) struct UIEdgeInsets cas_textEdgeInsets;
@end

