//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface UserInfo : NSObject
{
    BOOL _hasSVOD;
    BOOL _hasPIN;
    BOOL _hasPaymentMethod;
    BOOL _hasDVR;
    BOOL _hasFacebookToken;
    BOOL _hasArchive;
    BOOL _hasStartOver;
    NSString *_firstName;
    NSString *_lastName;
    NSString *_email;
    NSString *_userName;
    NSString *_tdcExternalId;
    NSString *_personId;
    NSArray *_DVRRecordableChannels;
    NSArray *_allowedChannels;
    NSDictionary *_allowedChannelsDictionary;
    NSArray *_tvGuideChannels;
}

@property(retain, nonatomic) NSArray *tvGuideChannels; // @synthesize tvGuideChannels=_tvGuideChannels;
@property(retain, nonatomic) NSDictionary *allowedChannelsDictionary; // @synthesize allowedChannelsDictionary=_allowedChannelsDictionary;
@property(retain, nonatomic) NSArray *allowedChannels; // @synthesize allowedChannels=_allowedChannels;
@property(retain, nonatomic) NSArray *DVRRecordableChannels; // @synthesize DVRRecordableChannels=_DVRRecordableChannels;
@property(nonatomic) BOOL hasStartOver; // @synthesize hasStartOver=_hasStartOver;
@property(nonatomic) BOOL hasArchive; // @synthesize hasArchive=_hasArchive;
@property(nonatomic) BOOL hasFacebookToken; // @synthesize hasFacebookToken=_hasFacebookToken;
@property(nonatomic) BOOL hasDVR; // @synthesize hasDVR=_hasDVR;
@property(nonatomic) BOOL hasPaymentMethod; // @synthesize hasPaymentMethod=_hasPaymentMethod;
@property(nonatomic) BOOL hasPIN; // @synthesize hasPIN=_hasPIN;
@property(nonatomic) BOOL hasSVOD; // @synthesize hasSVOD=_hasSVOD;
@property(retain, nonatomic) NSString *personId; // @synthesize personId=_personId;
@property(retain, nonatomic) NSString *tdcExternalId; // @synthesize tdcExternalId=_tdcExternalId;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(retain, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
- (void).cxx_destruct;
- (BOOL)streamingLimitedToHomeForChannel:(id)arg1;
- (BOOL)streamingAllowedForChannel:(id)arg1;

@end

