//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface ViewRightSecurity : NSObject
{
    NSTimer *m_pTimer;
    _Bool m_bAllowMirroring;
    id <VRSecurityCallback> m_SecurityCallbackDelegate;
}

- (_Bool)isDeviceMirrored;
- (_Bool)isMirroringAllowed;
- (void)ConfigureOutputControlSettings:(struct OutputControls)arg1;
- (void)enableMirrorChecking:(_Bool)arg1;
- (void)mirrorCheck:(id)arg1;

@end

