//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

__attribute__((visibility("hidden")))
@interface ViewRightProtocol : NSURLProtocol
{
}

+ (id)canonicalRequestForRequest:(id)arg1;
+ (void)setViewRightSecurity:(id)arg1;
+ (BOOL)canInitWithRequest:(id)arg1;
+ (void)registerViewRightProtocol;
+ (id)viewRightProtocolScheme;
- (void)stopLoading;
- (void)startLoading;

@end

