//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPModule.h"

@interface XMPPBandwidthMonitor : XMPPModule
{
    struct dispatch_source_s *timer;
    unsigned long long lastNumberOfBytesSent;
    unsigned long long lastNumberOfBytesReceived;
    double smoothedAverageOutgoingBandwidth;
    double smoothedAverageIncomingBandwidth;
}

- (void)xmppStreamDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)xmppStreamDidConnect:(id)arg1;
- (void)deactivate;
- (BOOL)activate:(id)arg1;
- (void)stopTimer;
- (void)startTimer;
- (void)updateBandwidth;
@property(readonly) double incomingBandwidth;
@property(readonly) double outgoingBandwidth;

@end

