//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DDXMLElement.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface XMPPElement : DDXMLElement <NSCoding, NSCopying>
{
}

- (BOOL)isTo:(id)arg1 from:(id)arg2 options:(int)arg3;
- (BOOL)isTo:(id)arg1 from:(id)arg2;
- (BOOL)isToOrFrom:(id)arg1 options:(int)arg2;
- (BOOL)isToOrFrom:(id)arg1;
- (BOOL)isFrom:(id)arg1 options:(int)arg2;
- (BOOL)isFrom:(id)arg1;
- (BOOL)isTo:(id)arg1 options:(int)arg2;
- (BOOL)isTo:(id)arg1;
- (id)from;
- (id)to;
- (id)fromStr;
- (id)toStr;
- (id)elementID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

