//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DDXMLElement.h"

@interface XMPPResultSet : DDXMLElement
{
}

+ (id)resultSetWithMax:(int)arg1 firstIndex:(int)arg2 after:(id)arg3 before:(id)arg4;
+ (id)resultSetWithMax:(int)arg1 before:(id)arg2;
+ (id)resultSetWithMax:(int)arg1 after:(id)arg2;
+ (id)resultSetWithMax:(int)arg1 firstIndex:(int)arg2;
+ (id)resultSetWithMax:(int)arg1;
+ (id)resultSet;
+ (id)resultSetFromElement:(id)arg1;
+ (void)initialize;
- (id)last;
- (id)first;
- (int)count;
- (id)before;
- (id)after;
- (int)firstIndex;
- (int)max;
- (id)initWithXMLString:(id)arg1 error:(id *)arg2;
- (id)initWithMax:(int)arg1 firstIndex:(int)arg2 after:(id)arg3 before:(id)arg4;
- (id)initWithMax:(int)arg1 before:(id)arg2;
- (id)initWithMax:(int)arg1 after:(id)arg2;
- (id)initWithMax:(int)arg1 firstIndex:(int)arg2;
- (id)initWithMax:(int)arg1;
- (id)init;

@end

