//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPModule.h"

@class DDList, NSMutableArray, XMPPIDTracker;

@interface XMPPRoster : XMPPModule
{
    id <XMPPRosterStorage> xmppRosterStorage;
    XMPPIDTracker *xmppIDTracker;
    unsigned char config;
    unsigned char flags;
    NSMutableArray *earlyPresenceElements;
    DDList *mucModules;
}

- (void).cxx_destruct;
- (void)xmppvCardAvatarModule:(id)arg1 didReceivePhoto:(id)arg2 forJID:(id)arg3;
- (void)xmppStream:(id)arg1 willUnregisterModule:(id)arg2;
- (void)xmppStream:(id)arg1 didRegisterModule:(id)arg2;
- (void)xmppStreamDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)xmppStream:(id)arg1 didSendPresence:(id)arg2;
- (void)xmppStream:(id)arg1 didReceivePresence:(id)arg2;
- (BOOL)xmppStream:(id)arg1 didReceiveIQ:(id)arg2;
- (void)xmppStreamDidAuthenticate:(id)arg1;
- (void)handleFetchRosterQueryIQ:(id)arg1 withInfo:(id)arg2;
- (void)fetchRoster;
- (void)rejectPresenceSubscriptionRequestFrom:(id)arg1;
- (void)acceptPresenceSubscriptionRequestFrom:(id)arg1 andAddToRoster:(BOOL)arg2;
- (void)removeUser:(id)arg1;
- (void)revokePresencePermissionFromUser:(id)arg1;
- (void)unsubscribePresenceFromUser:(id)arg1;
- (void)subscribePresenceToUser:(id)arg1;
- (void)setNickname:(id)arg1 forUser:(id)arg2;
- (void)addUser:(id)arg1 withNickname:(id)arg2 groups:(id)arg3 subscribeToPresence:(BOOL)arg4;
- (void)addUser:(id)arg1 withNickname:(id)arg2 groups:(id)arg3;
- (void)addUser:(id)arg1 withNickname:(id)arg2;
- (BOOL)isRosterItem:(id)arg1;
- (void)_addRosterItems:(id)arg1;
- (void)_setPopulatingRoster:(BOOL)arg1;
- (BOOL)_populatingRoster;
- (void)_setHasRoster:(BOOL)arg1;
- (BOOL)_hasRoster;
- (void)_setRequestedRoster:(BOOL)arg1;
- (BOOL)_requestedRoster;
@property(readonly, getter=isPopulating) BOOL populating;
@property(readonly, getter=hasRequestedRoster) BOOL requestedRoster;
@property BOOL allowRosterlessOperation;
@property BOOL autoAcceptKnownPresenceSubscriptionRequests;
@property BOOL autoClearAllUsersAndResources;
@property BOOL autoFetchRoster;
@property(readonly) id <XMPPRosterStorage> xmppRosterStorage;
- (id)multicastDelegate;
- (void)deactivate;
- (BOOL)activate:(id)arg1;
- (id)initWithRosterStorage:(id)arg1 dispatchQueue:(struct dispatch_queue_s *)arg2;
- (id)initWithRosterStorage:(id)arg1;
- (id)initWithDispatchQueue:(struct dispatch_queue_s *)arg1;
- (id)init;

@end

